var e;var g;g||(g=typeof Module !== 'undefined' ? Module : {});var l={},n;for(n in g)g.hasOwnProperty(n)&&(l[n]=g[n]);var p=[],aa="./this.program";function r(a,b){throw b;}var t=!1,v=!1,w=!1,ba=!1,ca=!1;t="object"===typeof window;v="function"===typeof importScripts;w=(ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!t&&!v;ca=!t&&!w&&!v;var y="",da,ea,z,fa,ha;
if(w)y=__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},z=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),p=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",A),r=function(a){process.exit(a)},
g.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),z=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?p=scriptArgs:"undefined"!=typeof arguments&&(p=arguments),"function"===typeof quit&&(r=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(t||v)v?y=self.location.href:document.currentScript&&(y=document.currentScript.src),y=0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=g.print||console.log.bind(console),B=g.printErr||console.warn.bind(console);for(n in l)l.hasOwnProperty(n)&&(g[n]=l[n]);l=null;g.arguments&&(p=g.arguments);g.thisProgram&&(aa=g.thisProgram);g.quit&&(r=g.quit);function ma(a){na||(na={});na[a]||(na[a]=1,B(a))}var na,C;g.wasmBinary&&(C=g.wasmBinary);var D;g.noExitRuntime&&(D=g.noExitRuntime);
"object"!==typeof WebAssembly&&B("no native wasm support detected");var E,oa=new WebAssembly.Table({initial:7004,maximum:7004,element:"anyfunc"}),F=!1;function assert(a,b){a||A("Assertion failed: "+b)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function ra(){var a=G();return a?qa(sa,a,void 0):""}
function ta(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var m=a.charCodeAt(++h);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function va(a){var b=ua(a)+1,c=wa(b);ta(a,H,c,b);return c}var buffer,H,sa,xa,J,ya=g.TOTAL_MEMORY||16777216;g.wasmMemory?E=g.wasmMemory:E=new WebAssembly.Memory({initial:ya/65536,maximum:ya/65536});E&&(buffer=E.buffer);ya=buffer.byteLength;var K=buffer;
buffer=K;g.HEAP8=H=new Int8Array(K);g.HEAP16=xa=new Int16Array(K);g.HEAP32=J=new Int32Array(K);g.HEAPU8=sa=new Uint8Array(K);g.HEAPU16=new Uint16Array(K);g.HEAPU32=new Uint32Array(K);g.HEAPF32=new Float32Array(K);g.HEAPF64=new Float64Array(K);J[26152]=5347648;function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.o;"number"===typeof c?void 0===b.v?g.dynCall_v(c):g.dynCall_vi(c,b.v):c(void 0===b.v?null:b.v)}}}var Aa=[],Ba=[],Ca=[],Da=[];
function Ea(){var a=g.preRun.shift();Aa.unshift(a)}var Fa=Math.abs,Ga=Math.ceil,Ha=Math.floor,Ia=Math.min,L=0,Ja=null,Ka=null;function La(){L++;g.monitorRunDependencies&&g.monitorRunDependencies(L)}function Ma(){L--;g.monitorRunDependencies&&g.monitorRunDependencies(L);if(0==L&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka)){var a=Ka;Ka=null;a()}}g.preloadedImages={};g.preloadedAudios={};
function A(a){if(g.onAbort)g.onAbort(a);la(a);B(a);F=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Na(){var a=M;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var M="Sample1.wasm";if(!Na()){var Oa=M;M=g.locateFile?g.locateFile(Oa,y):y+Oa}
function Pa(){try{if(C)return new Uint8Array(C);if(z)return z(M);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}function Qa(){return C||!t&&!v||"function"!==typeof fetch?new Promise(function(a){a(Pa())}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Pa()})}var N,O;Ba.push({o:function(){Ra()}});
function Sa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function P(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ua(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Va(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Wa(){g.___errno_location&&(J[g.___errno_location()>>2]=28)}
function Xa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sa(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var Ya=[];function Za(a,b){Ya[a]={input:[],output:[],D:b};$a(a,ab)}
var ab={open:function(a){var b=Ya[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.D.flush(a.tty)},flush:function(a){a.tty.D.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.D.na)throw new Q(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.D.na(a.tty)}catch(m){throw new Q(29);}if(void 0===k&&0===f)throw new Q(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.D.ea)throw new Q(60);try{for(var f=
0;f<d;f++)a.tty.D.ea(a.tty,b[c+f])}catch(h){throw new Q(29);}d&&(a.node.timestamp=Date.now());return f}},bb={na:function(a){if(!a.input.length){var b=null;if(w){var c=Buffer.X?Buffer.X(256):new Buffer(256),d=0;try{d=fa.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(ua(b)+1);b=ta(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},ea:function(a,b){null===b||10===b?(la(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(qa(a.output,0)),a.output=[])}},cb={ea:function(a,b){null===b||10===b?(B(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(qa(a.output,0)),a.output=[])}},S={j:null,s:function(){return S.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);S.j||(S.j={dir:{node:{i:S.f.i,l:S.f.l,lookup:S.f.lookup,N:S.f.N,rename:S.f.rename,unlink:S.f.unlink,rmdir:S.f.rmdir,readdir:S.f.readdir,symlink:S.f.symlink},stream:{A:S.g.A}},file:{node:{i:S.f.i,l:S.f.l},stream:{A:S.g.A,read:S.g.read,write:S.g.write,ia:S.g.ia,pa:S.g.pa,ra:S.g.ra}},link:{node:{i:S.f.i,l:S.f.l,readlink:S.f.readlink},stream:{}},ja:{node:{i:S.f.i,l:S.f.l},stream:db}});c=eb(a,b,c,d);16384===
(c.mode&61440)?(c.f=S.j.dir.node,c.g=S.j.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=S.j.file.node,c.g=S.j.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=S.j.link.node,c.g=S.j.link.stream):8192===(c.mode&61440)&&(c.f=S.j.ja.node,c.g=S.j.ja.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},bb:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},cb:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},
ka:function(a,b){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))},Ja:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{i:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=
a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ya=4096;b.blocks=Math.ceil(b.size/b.ya);return b},l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&S.Ja(a,b.size)},lookup:function(){throw fb[44];},N:function(a,b,
c,d){return S.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=gb(b,c)}catch(h){}if(d)for(var f in d.c)throw new Q(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=gb(a,b),d;for(d in c.c)throw new Q(55);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==
(a.mode&61440))throw new Q(28);return a.link}},g:{read:function(a,b,c,d,f){var h=a.node.c;if(f>=a.node.h)return 0;a=Math.min(a.node.h-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write:function(a,b,c,d,f,h){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(h)return a.c=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===f)return a.c=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(f+d<=a.h)return a.c.set(b.subarray(c,c+d),f),d}S.ka(a,
f+d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.c[f+h]=b[c+h];a.h=Math.max(a.h,f+d);return d},A:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new Q(28);return b},ia:function(a,b,c){S.ka(a.node,b+c);a.node.h=Math.max(a.node.h,b+c)},pa:function(a,b,c,d,f,h,k){if(32768!==(a.node.mode&61440))throw new Q(43);c=a.node.c;if(k&2||c.buffer!==b.buffer){if(0<f||f+d<a.node.h)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,
f,f+d);a=!0;f=b.buffer==H.buffer;d=hb(d);if(!d)throw new Q(48);(f?H:b).set(c,d)}else a=!1,d=c.byteOffset;return{lb:d,Wa:a}},ra:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new Q(43);if(f&2)return 0;S.g.write(a,b,0,d,c,!1);return 0}}},ib=null,jb={},kb=[],lb=1,mb=null,nb=!0,ob={},Q=null,fb={};
function U(a,b){a=Xa("/",a);b=b||{};if(!a)return{path:"",node:null};var c={la:!0,fa:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.fa)throw new Q(32);a=Sa(a.split("/").filter(function(a){return!!a}),!1);var f=ib;c="/";for(d=0;d<a.length;d++){var h=d===a.length-1;if(h&&b.parent)break;f=gb(f,a[d]);c=P(c+"/"+a[d]);f.O&&(!h||h&&b.la)&&(f=f.O.root);if(!h||b.$)for(h=0;40960===(f.mode&61440);)if(f=pb(c),c=Xa(Ua(c),f),f=U(c,{fa:b.fa}).node,40<h++)throw new Q(32);}return{path:c,node:f}}
function qb(a){for(var b;;){if(a===a.parent)return a=a.s.qa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function rb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%mb.length}function sb(a){var b=rb(a.parent.id,a.name);a.Ia=mb[b];mb[b]=a}function gb(a,b){var c;if(c=(c=tb(a,"x"))?c:a.f.lookup?0:2)throw new Q(c,a);for(c=mb[rb(a.id,b)];c;c=c.Ia){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.lookup(a,b)}
function eb(a,b,c,d){ub||(ub=function(a,b,c,d){a||(a=this);this.parent=a;this.s=a.s;this.O=null;this.id=lb++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=d},ub.prototype={},Object.defineProperties(ub.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new ub(a,b,c,d);sb(a);return a}
var vb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function wb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function tb(a,b){if(nb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function xb(a,b){try{return gb(a,b),20}catch(c){}return tb(a,"wx")}
function yb(a){var b=4096;for(a=a||0;a<=b;a++)if(!kb[a])return a;throw new Q(33);}function zb(a,b){Ab||(Ab=function(){},Ab.prototype={},Object.defineProperties(Ab.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Ab,d;for(d in a)c[d]=a[d];a=c;b=yb(b);a.fd=b;return kb[b]=a}var db={open:function(a){a.g=jb[a.node.rdev].g;a.g.open&&a.g.open(a)},A:function(){throw new Q(70);}};function $a(a,b){jb[a]={g:b}}
function Bb(a,b){var c="/"===b,d=!b;if(c&&ib)throw new Q(10);if(!c&&!d){var f=U(b,{la:!1});b=f.path;f=f.node;if(f.O)throw new Q(10);if(16384!==(f.mode&61440))throw new Q(54);}b={type:a,jb:{},qa:b,Ha:[]};a=a.s(b);a.s=b;b.root=a;c?ib=a:f&&(f.O=b,f.s&&f.s.Ha.push(b))}function Cb(a,b,c){var d=U(a,{parent:!0}).node;a=Va(a);if(!a||"."===a||".."===a)throw new Q(28);var f=xb(d,a);if(f)throw new Q(f);if(!d.f.N)throw new Q(63);return d.f.N(d,a,b,c)}function V(a,b){Cb(a,(void 0!==b?b:511)&1023|16384,0)}
function Db(a,b,c){"undefined"===typeof c&&(c=b,b=438);Cb(a,b|8192,c)}function Eb(a,b){if(!Xa(a))throw new Q(44);var c=U(b,{parent:!0}).node;if(!c)throw new Q(44);b=Va(b);var d=xb(c,b);if(d)throw new Q(d);if(!c.f.symlink)throw new Q(63);c.f.symlink(c,b,a)}function pb(a){a=U(a).node;if(!a)throw new Q(44);if(!a.f.readlink)throw new Q(28);return Xa(qb(a.parent),a.f.readlink(a))}
function Fb(a,b,c,d){if(""===a)throw new Q(44);if("string"===typeof b){var f=vb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=P(a);try{h=U(a,{$:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(h){if(b&128)throw new Q(20);}else h=Cb(a,c,0),f=!0;if(!h)throw new Q(44);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&16384!==(h.mode&61440))throw new Q(54);if(!f&&(c=h?40960===(h.mode&61440)?32:
16384===(h.mode&61440)&&("r"!==wb(b)||b&512)?31:tb(h,wb(b)):44))throw new Q(c);if(b&512){c=h;var k;"string"===typeof c?k=U(c,{$:!0}).node:k=c;if(!k.f.l)throw new Q(63);if(16384===(k.mode&61440))throw new Q(31);if(32768!==(k.mode&61440))throw new Q(28);if(c=tb(k,"w"))throw new Q(c);k.f.l(k,{size:0,timestamp:Date.now()})}b&=-641;d=zb({node:h,path:qb(h),flags:b,seekable:!0,position:0,g:h.g,Sa:[],error:!1},d);d.g.open&&d.g.open(d);!g.logReadFiles||b&1||(Gb||(Gb={}),a in Gb||(Gb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{ob.onOpenFile&&(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),ob.onOpenFile(a,h))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Hb(a,b,c){if(null===a.fd)throw new Q(8);if(!a.seekable||!a.g.A)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.g.A(a,b,c);a.Sa=[]}
function Ib(){Q||(Q=function(a,b){this.node=b;this.Oa=function(a){this.m=a};this.Oa(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(function(a){fb[a]=new Q(a);fb[a].stack="<generic error, no stack>"}))}var Jb;function Kb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Lb(a,b,c){a=P("/dev/"+a);var d=Kb(!!b,!!c);Mb||(Mb=64);var f=Mb++<<8|0;$a(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var h=0,k=0;k<f;k++){try{var m=b()}catch(R){throw new Q(29);}if(void 0===m&&0===h)throw new Q(6);if(null===m||void 0===m)break;h++;c[d+k]=m}h&&(a.node.timestamp=Date.now());return h},write:function(a,b,d,f){for(var h=0;h<f;h++)try{c(b[d+h])}catch(u){throw new Q(29);}f&&(a.node.timestamp=Date.now());return h}});
Db(a,d,f)}var Mb,W={},ub,Ab,Gb,X=0;function G(){X+=4;return J[X-4>>2]}function Y(a){void 0===a&&(a=G());a=kb[a];if(!a)throw new Q(8);return a}function Z(){A()}
function Nb(a,b){e.b.V=a;e.b.W=b;if(e.b.o)if(0==a)e.b.u=function(){var a=Math.max(0,e.b.Ra+b-Z())|0;setTimeout(e.b.U,a)},e.b.method="timeout";else if(1==a)e.b.u=function(){e.requestAnimationFrame(e.b.U)},e.b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);v?(void 0===g.setImmediates&&(g.setImmediates=[]),
g.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}e.b.u=function(){setImmediate(e.b.U)};e.b.method="immediate"}}
function Ob(a,b,c,d,f){D=!0;assert(!e.b.o,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");e.b.o=a;e.b.v=d;var h="undefined"!==typeof d?function(){g.dynCall_vi(a,d)}:function(){g.dynCall_v(a)};var k=e.b.B;e.b.U=function(){if(!F)if(0<e.b.ua.length){var a=Date.now(),b=e.b.ua.shift();b.o(b.v);if(e.b.ga){var c=e.b.ga,d=0==c%1?c-1:Math.floor(c);e.b.ga=b.Za?d:(8*
c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");e.b.Ta();k<e.b.B||setTimeout(e.b.U,0)}else k<e.b.B||(e.b.Z=e.b.Z+1|0,1==e.b.V&&1<e.b.W&&0!=e.b.Z%e.b.W?e.b.u():(0==e.b.V&&(e.b.Ra=Z()),"timeout"===e.b.method&&g.Y&&(B("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),e.b.method=""),
e.b.La(h),k<e.b.B||e.b.u()))};f||(b&&0<b?Nb(0,1E3/b):Nb(1,1),e.b.u());if(c)throw"SimulateInfiniteLoop";}
e={b:{u:null,method:"",B:0,o:null,v:0,V:0,W:0,Z:0,ua:[],pause:function(){e.b.u=null;e.b.B++},resume:function(){e.b.B++;var a=e.b.V,b=e.b.W,c=e.b.o;e.b.o=null;Ob(c,0,!1,e.b.v,!0);Nb(a,b);e.b.u()},Ta:function(){if(g.setStatus){var a=g.statusMessage||"Please wait...",b=e.b.ga,c=e.b.ab;b?b<c?g.setStatus(a+" ("+(c-b)+"/"+c+")"):g.setStatus(a):g.setStatus("")}},La:function(a){if(!(F||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(b){if(b instanceof ia)return;b&&"object"===typeof b&&b.stack&&B("exception thrown: "+
[b,b.stack]);throw b;}g.postMainLoop&&g.postMainLoop()}}},H:!1,da:!1,Ga:[],workers:[],Da:function(){function a(){e.da=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!e.Ea){e.Ea=!0;try{e.L=!0}catch(c){e.L=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}e.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:e.L?null:console.log("warning: no BlobBuilder");e.K="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.ta||"undefined"!==typeof e.K||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.ta=!0);g.preloadPlugins.push({canHandle:function(a){return!g.ta&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,h){var c=null;if(e.L)try{c=
new Blob([a],{type:e.aa(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:e.aa(b)}))}catch(x){ma("Blob constructor present but fails: "+x+"; falling back to blob builder")}c||(c=new e.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=e.K.createObjectURL(c),q=new Image;q.onload=function(){assert(q.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=q.width;c.height=q.height;c.getContext("2d").drawImage(q,0,0);g.preloadedImages[b]=
c;e.K.revokeObjectURL(d);f&&f(a)};q.onerror=function(){console.log("Image "+d+" could not be decoded");h&&h()};q.src=d}});g.preloadPlugins.push({canHandle:function(a){return!g.ib&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,h){function c(c){q||(q=!0,g.preloadedAudios[b]=c,f&&f(a))}function d(){q||(q=!0,g.preloadedAudios[b]=new Audio,h&&h())}var q=!1;if(e.L){try{var x=new Blob([a],{type:e.aa(b)})}catch(ja){return d()}x=e.K.createObjectURL(x);var u=new Audio;u.addEventListener("canplaythrough",
function(){c(u)},!1);u.onerror=function(){if(!q){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,h=0,k=0;k<a.length;k++)for(f=f<<8|a[k],h+=8;6<=h;){var m=f>>h-6&63;h-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]}2==h?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==h&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");u.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(u)}};u.src=x;e.Ma(function(){c(u)},1E4)}else return d()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",function(a){!e.da&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&g.Y&&a==g.canvas)return g.Y;var f;if(b){var h={antialias:!1,alpha:!1,gb:1};if(d)for(var k in d)h[k]=d[k];if("undefined"!==typeof GL&&(f=GL.createContext(a,
h)))var m=GL.getContext(f).Va}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Y=m,b&&GL.hb(f),g.rb=b,e.Ga.forEach(function(a){a()}),e.Da());return m},$a:function(){},ma:!1,M:void 0,F:void 0,requestFullscreen:function(a,b,c){function d(){e.H=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=e.exitFullscreen,e.M&&f.requestPointerLock(),e.H=!0,e.F?e.Pa():e.J(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),e.F?e.Qa():e.J(f));if(g.onFullScreen)g.onFullScreen(e.H);if(g.onFullscreen)g.onFullscreen(e.H)}e.M=a;e.F=b;e.wa=c;"undefined"===typeof e.M&&(e.M=!0);"undefined"===typeof e.F&&(e.F=!1);"undefined"===typeof e.wa&&(e.wa=null);var f=g.canvas;e.ma||(e.ma=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var h=document.createElement("div");f.parentNode.insertBefore(h,f);h.appendChild(f);h.requestFullscreen=h.requestFullscreen||h.mozRequestFullScreen||h.msRequestFullscreen||(h.webkitRequestFullscreen?function(){h.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(h.webkitRequestFullScreen?function(){h.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?h.requestFullscreen({sb:c}):
h.requestFullscreen()},va:function(a,b,c){B("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");e.va=function(a,b,c){return e.requestFullscreen(a,b,c)};return e.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!e.H)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},C:0,za:function(a){var b=Date.now();if(0===e.C)e.C=
b+1E3/60;else for(;b+2>=e.C;)e.C+=1E3/60;setTimeout(a,Math.max(e.C-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=e.za;b(a)}},nb:function(a){return function(){if(!F)return a.apply(null,arguments)}},G:!0,I:[],kb:function(){e.G=!1},mb:function(){e.G=!0;if(0<e.I.length){var a=e.I;e.I=[];a.forEach(function(a){a()})}},ob:function(a){return e.requestAnimationFrame(function(){F||(e.G?a():e.I.push(a))})},Ma:function(a,b){D=!0;return setTimeout(function(){F||
(e.G?a():e.I.push(a))},b)},pb:function(a,b){D=!0;return setInterval(function(){F||e.G&&a()},b)},aa:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Aa:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},Ba:function(a){return a.movementY||
a.mozMovementY||a.webkitMovementY||0},eb:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},S:0,T:0,P:0,R:0,touches:{},oa:{},Ya:function(a){if(e.da)"mousemove"!=a.type&&"mozMovementX"in a?e.P=e.R=0:
(e.P=e.Aa(a),e.R=e.Ba(a)),e.S+=e.P,e.T+=e.R;else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,h="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.qb;if(void 0!==k)if(f=k.pageX-(f+b.left),h=k.pageY-(h+b.top),f*=c/b.width,h*=d/b.height,b={x:f,y:h},"touchstart"===a.type)e.oa[k.identifier]=b,e.touches[k.identifier]=
b;else if("touchend"===a.type||"touchmove"===a.type)(a=e.touches[k.identifier])||(a=b),e.oa[k.identifier]=a,e.touches[k.identifier]=b}else k=a.pageX-(f+b.left),a=a.pageY-(h+b.top),k*=c/b.width,a*=d/b.height,e.P=k-e.S,e.R=a-e.T,e.S=k,e.T=a}},Xa:function(a,b,c,d){var f=d?"":"al "+a;ea(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));f&&Ma()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});f&&La()},Ka:[],ha:function(){var a=g.canvas;
e.Ka.forEach(function(b){b(a.width,a.height)})},Na:function(a,b,c){e.J(g.canvas,a,b);c||e.ha()},vb:0,ub:0,Pa:function(){e.J(g.canvas);e.ha()},Qa:function(){e.J(g.canvas);e.ha()},J:function(a,b,c){b&&c?(a.Ua=b,a.Ca=c):(b=a.Ua,c=a.Ca);var d=b,f=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/f<g.forcedAspectRatio?d=Math.round(f*g.forcedAspectRatio):f=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/f);d=Math.round(d*h);f=Math.round(f*h)}e.F?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):
(a.style.removeProperty("width"),a.style.removeProperty("height"))))},tb:{},sa:0,fb:function(){var a=e.sa;e.sa++;return a}};Ib();mb=Array(4096);Bb(S,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");$a(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Db("/dev/null",259);Za(1280,bb);Za(1536,cb);Db("/dev/tty",1280);Db("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(w)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){A("random_device")});Lb("random",b);Lb("urandom",b);V("/dev/shm");
V("/dev/shm/tmp")})();V("/proc");V("/proc/self");V("/proc/self/fd");Bb({s:function(){var a=eb("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=kb[+c];if(!b)throw new Q(8);a={parent:null,s:{qa:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
w?Z=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Z=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Z=function(){return performance.now()}:Z=Date.now;g.requestFullScreen=function(a,b,c){B("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");g.requestFullScreen=g.requestFullscreen;e.va(a,b,c)};g.requestFullscreen=function(a,b,c){e.requestFullscreen(a,b,c)};
g.requestAnimationFrame=function(a){e.requestAnimationFrame(a)};g.setCanvasSize=function(a,b,c){e.Na(a,b,c)};g.pauseMainLoop=function(){e.b.pause()};g.resumeMainLoop=function(){e.b.resume()};g.getUserMedia=function(){e.getUserMedia()};g.createContext=function(a,b,c,d){return e.createContext(a,b,c,d)};
var Qb={__cxa_allocate_exception:function(a){return hb(a)},__cxa_throw:function(a){"uncaught_exception"in Pb?Pb.X++:Pb.X=1;throw a;},__lock:function(){},__syscall195:function(a,b){X=b;try{var c=ra();a:{var d=G();try{var f=U(c,{$:!0}).node;if(!f)throw new Q(44);if(!f.f.i)throw new Q(63);var h=f.f.i(f)}catch(m){if(m&&m.node&&P(c)!==P(qb(m.node))){var k=-54;break a}throw m;}J[d>>2]=h.dev;J[d+4>>2]=0;J[d+8>>2]=h.ino;J[d+12>>2]=h.mode;J[d+16>>2]=h.nlink;J[d+20>>2]=h.uid;J[d+24>>2]=h.gid;J[d+28>>2]=h.rdev;
J[d+32>>2]=0;O=[h.size>>>0,(N=h.size,1<=+Fa(N)?0<N?(Ia(+Ha(N/4294967296),4294967295)|0)>>>0:~~+Ga((N-+(~~N>>>0))/4294967296)>>>0:0)];J[d+40>>2]=O[0];J[d+44>>2]=O[1];J[d+48>>2]=4096;J[d+52>>2]=h.blocks;J[d+56>>2]=h.atime.getTime()/1E3|0;J[d+60>>2]=0;J[d+64>>2]=h.mtime.getTime()/1E3|0;J[d+68>>2]=0;J[d+72>>2]=h.ctime.getTime()/1E3|0;J[d+76>>2]=0;O=[h.ino>>>0,(N=h.ino,1<=+Fa(N)?0<N?(Ia(+Ha(N/4294967296),4294967295)|0)>>>0:~~+Ga((N-+(~~N>>>0))/4294967296)>>>0:0)];J[d+80>>2]=O[0];J[d+84>>2]=O[1];k=0}return k}catch(m){return"undefined"!==
typeof W&&m instanceof Q||A(m),-m.m}},__syscall221:function(a,b){X=b;try{var c=Y();switch(G()){case 0:var d=G();return 0>d?-28:Fb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=G(),c.flags|=d,0;case 12:return d=G(),xa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return Wa(),-1;default:return-28}}catch(f){return"undefined"!==typeof W&&f instanceof Q||A(f),-f.m}},__syscall39:function(a,b){X=b;try{var c=ra(),d=G();a=c;a=P(a);"/"===a[a.length-
1]&&(a=a.substr(0,a.length-1));V(a,d);return 0}catch(f){return"undefined"!==typeof W&&f instanceof Q||A(f),-f.m}},__syscall5:function(a,b){X=b;try{var c=ra(),d=G(),f=G();return Fb(c,d,f).fd}catch(h){return"undefined"!==typeof W&&h instanceof Q||A(h),-h.m}},__syscall54:function(a,b){X=b;try{var c=Y(),d=G();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var f=G();return J[f>>2]=0;
case 21520:return c.tty?-28:-59;case 21531:a=f=G();if(!c.g.Fa)throw new Q(59);return c.g.Fa(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:A("bad ioctl syscall "+d)}}catch(h){return"undefined"!==typeof W&&h instanceof Q||A(h),-h.m}},__unlock:function(){},abort:function(){A()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(w||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Z();else return Wa(),
-1;J[b>>2]=a/1E3|0;J[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_cancel_main_loop:function(){e.b.pause();e.b.o=null},emscripten_get_sbrk_ptr:function(){return 104608},emscripten_memcpy_big:function(a,b,c){sa.set(sa.subarray(b,b+c),a)},emscripten_resize_heap:function(){A("OOM")},emscripten_set_main_loop:Ob,fd_close:function(a){try{var b=Y(a);if(null===b.fd)throw new Q(8);b.ba&&(b.ba=null);try{b.g.close&&b.g.close(b)}catch(c){throw c;}finally{kb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==
typeof W&&c instanceof Q||A(c),c.m}},fd_read:function(a,b,c,d){try{a:{for(var f=Y(a),h=a=0;h<c;h++){var k=J[b+(8*h+4)>>2],m=f,q=J[b+8*h>>2],x=k,u=void 0,ja=H;if(0>x||0>u)throw new Q(28);if(null===m.fd)throw new Q(8);if(1===(m.flags&2097155))throw new Q(8);if(16384===(m.node.mode&61440))throw new Q(31);if(!m.g.read)throw new Q(28);var R="undefined"!==typeof u;if(!R)u=m.position;else if(!m.seekable)throw new Q(70);var ka=m.g.read(m,ja,q,x,u);R||(m.position+=ka);var T=ka;if(0>T){var I=-1;break a}a+=
T;if(T<k)break}I=a}J[d>>2]=I;return 0}catch(Ta){return"undefined"!==typeof W&&Ta instanceof Q||A(Ta),Ta.m}},fd_seek:function(a,b,c,d,f){try{var h=Y(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Hb(h,a,d);O=[h.position>>>0,(N=h.position,1<=+Fa(N)?0<N?(Ia(+Ha(N/4294967296),4294967295)|0)>>>0:~~+Ga((N-+(~~N>>>0))/4294967296)>>>0:0)];J[f>>2]=O[0];J[f+4>>2]=O[1];h.ba&&0===a&&0===d&&(h.ba=null);return 0}catch(k){return"undefined"!==typeof W&&k instanceof Q||A(k),k.m}},
fd_write:function(a,b,c,d){try{a:{for(var f=Y(a),h=a=0;h<c;h++){var k=f,m=J[b+8*h>>2],q=J[b+(8*h+4)>>2],x=void 0,u=H;if(0>q||0>x)throw new Q(28);if(null===k.fd)throw new Q(8);if(0===(k.flags&2097155))throw new Q(8);if(16384===(k.node.mode&61440))throw new Q(31);if(!k.g.write)throw new Q(28);k.flags&1024&&Hb(k,0,2);var ja="undefined"!==typeof x;if(!ja)x=k.position;else if(!k.seekable)throw new Q(70);var R=k.g.write(k,u,m,q,x,void 0);ja||(k.position+=R);try{if(k.path&&ob.onWriteToFile)ob.onWriteToFile(k.path)}catch(I){console.log("FS.trackingDelegate['onWriteToFile']('"+
k.path+"') threw an exception: "+I.message)}var ka=R;if(0>ka){var T=-1;break a}a+=ka}T=a}J[d>>2]=T;return 0}catch(I){return"undefined"!==typeof W&&I instanceof Q||A(I),I.m}},memory:E,nanosleep:function(a,b){if(0===a)return Wa(),-1;var c=J[a>>2];a=J[a+4>>2];if(0>a||999999999<a||0>c)return Wa(),-1;0!==b&&(J[b>>2]=0,J[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((t||v)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},
pthread_equal:function(a,b){return a==b},pthread_mutexattr_destroy:function(){},pthread_mutexattr_init:function(){},pthread_mutexattr_settype:function(){},sched_yield:function(){return 0},setTempRet0:function(){},table:oa},Rb=function(){function a(a){g.asm=a.exports;Ma()}function b(b){a(b.instance)}function c(a){return Qa().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){B("failed to asynchronously prepare wasm: "+a);A(a)})}var d={env:Qb,wasi_unstable:Qb};La();if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(f){return B("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(C||"function"!==typeof WebAssembly.instantiateStreaming||Na()||"function"!==typeof fetch)return c(b);fetch(M,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){B("wasm streaming compile failed: "+a);B("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();g.asm=Rb;
var Ra=g.___wasm_call_ctors=function(){return g.asm.__wasm_call_ctors.apply(null,arguments)};g._free=function(){return g.asm.free.apply(null,arguments)};g._main=function(){return g.asm.main.apply(null,arguments)};var hb=g._malloc=function(){return g.asm.malloc.apply(null,arguments)};g.___errno_location=function(){return g.asm.__errno_location.apply(null,arguments)};g.__get_tzname=function(){return g.asm._get_tzname.apply(null,arguments)};
g.__get_daylight=function(){return g.asm._get_daylight.apply(null,arguments)};g.__get_timezone=function(){return g.asm._get_timezone.apply(null,arguments)};g._setThrew=function(){return g.asm.setThrew.apply(null,arguments)};var Pb=g.__ZSt18uncaught_exceptionv=function(){return g.asm._ZSt18uncaught_exceptionv.apply(null,arguments)};g.stackSave=function(){return g.asm.stackSave.apply(null,arguments)};var wa=g.stackAlloc=function(){return g.asm.stackAlloc.apply(null,arguments)};
g.stackRestore=function(){return g.asm.stackRestore.apply(null,arguments)};g.__growWasmMemory=function(){return g.asm.__growWasmMemory.apply(null,arguments)};g.dynCall_iii=function(){return g.asm.dynCall_iii.apply(null,arguments)};g.dynCall_iiiii=function(){return g.asm.dynCall_iiiii.apply(null,arguments)};g.dynCall_ii=function(){return g.asm.dynCall_ii.apply(null,arguments)};g.dynCall_vi=function(){return g.asm.dynCall_vi.apply(null,arguments)};
g.dynCall_iiiiii=function(){return g.asm.dynCall_iiiiii.apply(null,arguments)};g.dynCall_vii=function(){return g.asm.dynCall_vii.apply(null,arguments)};g.dynCall_viii=function(){return g.asm.dynCall_viii.apply(null,arguments)};g.dynCall_iiii=function(){return g.asm.dynCall_iiii.apply(null,arguments)};g.dynCall_iij=function(){return g.asm.dynCall_iij.apply(null,arguments)};g.dynCall_iif=function(){return g.asm.dynCall_iif.apply(null,arguments)};
g.dynCall_iid=function(){return g.asm.dynCall_iid.apply(null,arguments)};g.dynCall_iijii=function(){return g.asm.dynCall_iijii.apply(null,arguments)};g.dynCall_iifii=function(){return g.asm.dynCall_iifii.apply(null,arguments)};g.dynCall_iidii=function(){return g.asm.dynCall_iidii.apply(null,arguments)};g.dynCall_fi=function(){return g.asm.dynCall_fi.apply(null,arguments)};g.dynCall_v=function(){return g.asm.dynCall_v.apply(null,arguments)};
g.dynCall_i=function(){return g.asm.dynCall_i.apply(null,arguments)};g.dynCall_di=function(){return g.asm.dynCall_di.apply(null,arguments)};g.dynCall_ji=function(){return g.asm.dynCall_ji.apply(null,arguments)};g.dynCall_viiii=function(){return g.asm.dynCall_viiii.apply(null,arguments)};g.dynCall_vid=function(){return g.asm.dynCall_vid.apply(null,arguments)};g.dynCall_jiji=function(){return g.asm.dynCall_jiji.apply(null,arguments)};
g.dynCall_iidiiii=function(){return g.asm.dynCall_iidiiii.apply(null,arguments)};g.dynCall_viiiiii=function(){return g.asm.dynCall_viiiiii.apply(null,arguments)};g.dynCall_viiiii=function(){return g.asm.dynCall_viiiii.apply(null,arguments)};g.asm=Rb;var Sb;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ka=function Tb(){Sb||Ub();Sb||(Ka=Tb)};
function Ub(a){function b(){if(!Sb&&(Sb=!0,!F)){g.noFSInit||Jb||(Jb=!0,Ib(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Lb("stdin",g.stdin):Eb("/dev/tty","/dev/stdin"),g.stdout?Lb("stdout",null,g.stdout):Eb("/dev/tty","/dev/stdout"),g.stderr?Lb("stderr",null,g.stderr):Eb("/dev/tty1","/dev/stderr"),Fb("/dev/stdin","r"),Fb("/dev/stdout","w"),Fb("/dev/stderr","w"));za(Ba);nb=!1;za(Ca);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Vb){var b=a,d=g._main;b=b||[];var f=b.length+1,
h=wa(4*(f+1));J[h>>2]=va(aa);for(var k=1;k<f;k++)J[(h>>2)+k]=va(b[k-1]);J[(h>>2)+f]=0;try{var m=d(f,h);if(!D||0!==m){if(!D&&(F=!0,g.onExit))g.onExit(m);r(m,new ia(m))}}catch(q){q instanceof ia||("SimulateInfiniteLoop"==q?D=!0:((b=q)&&"object"===typeof q&&q.stack&&(b=[q,q.stack]),B("exception thrown: "+b),r(1,q)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),Da.unshift(b);za(Da)}}a=a||p;if(!(0<L)){if(g.preRun)for("function"==
typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ea();za(Aa);0<L||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Ub;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Vb=!0;g.noInitialRun&&(Vb=!1);D=!0;Ub();
