var f;var k;k||(k=typeof Module !== 'undefined' ? Module : {});k.Aa||(k.Aa=0,k.sb=0);k.Aa++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.V?k.N[a].loaded=c.loaded:(d.V=!0,k.N||(k.N={}),k.N[a]={loaded:c.loaded,total:e});var g=e=c=0,h;for(h in k.N){var p=k.N[h];c+=p.total;e+=p.loaded;g++}c=Math.ceil(c*k.Aa/g);k.setStatus&&k.setStatus("Downloading data... ("+e+"/"+c+")")}else!k.N&&k.setStatus&&k.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){k.sb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.pb=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();k.removeRunDependency("datafile_Sample7.data")}b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;k.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.pb.subarray(this.start,this.end))},finish:function(a){var b=this;k.FS_createPreloadedFile(this.name,null,a,!0,!0,function(){k.removeRunDependency("fp "+b.name)},function(){b.audio?k.removeRunDependency("fp "+b.name):l("Preloading file "+b.name+
" failed")},!1,!0);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",d[e].filename);k.addRunDependency("datafile_Sample7.data");k.gb||(k.gb={});k.gb["Sample7.data"]={te:!1};n?(c(n),n=null):h=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof k.locateFilePackage||k.locateFile||(k.locateFile=k.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=k.locateFile?k.locateFile("Sample7.data",""):"Sample7.data",g=a.Ge,h=null,n=k.getPreloadedPackage?k.getPreloadedPackage(e,g):null;n||b(e,
g,function(a){h?(h(a),h=null):n=a},c);k.calledRun?d():(k.preRun||(k.preRun=[]),k.preRun.push(d))})({files:[{start:0,audio:0,end:2891,filename:"/AppInit.xml"},{start:2891,audio:0,end:3293,filename:"/button.lua"},{start:3293,audio:0,end:54341,filename:"/Calibri.ttf"},{start:54341,audio:0,end:55397,filename:"/Down.png"},{start:55397,audio:0,end:55746,filename:"/imgui.ini"},{start:55746,audio:0,end:82695,filename:"/KigsHD.png"},{start:82695,audio:0,end:83727,filename:"/LaunchScreen.xml"},{start:83727,
audio:0,end:158427,filename:"/Logo.png"},{start:158427,audio:0,end:160489,filename:"/Screen_Main.xml"},{start:160489,audio:0,end:160613,filename:"/ScriptOnApp.lua"},{start:160613,audio:0,end:161598,filename:"/test.lua"},{start:161598,audio:0,end:161931,filename:"/Up.png"}],remote_package_size:161931,package_uuid:"870b86ad-d12b-44b0-9cf6-5abebcdd2320"});var aa={},ba;for(ba in k)k.hasOwnProperty(ba)&&(aa[ba]=k[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}
var fa=!1,m=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;m="function"===typeof importScripts;ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!m;ja=!fa&&!ha&&!m;var q="",ka,la,ma;
if(ha){q=__dirname+"/";var na,oa;ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);a=na.readFileSync(a);return b?a:a.toString()};ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=k);process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;});process.on("unhandledRejection",u);ea=function(a){process.exit(a)};
k.inspect=function(){return"[Emscripten Module object]"}}else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||m)m?q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=k.print||console.log.bind(console),l=k.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(k[ba]=aa[ba]);aa=null;k.arguments&&(ca=k.arguments);k.thisProgram&&(da=k.thisProgram);k.quit&&(ea=k.quit);function ra(a){ta||(ta={});ta[a]||(ta[a]=1,l(a))}var ta,ua={},va;k.wasmBinary&&(va=k.wasmBinary);var wa;
k.noExitRuntime&&(wa=k.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");var xa,ya=new WebAssembly.Table({initial:11446,maximum:11446,element:"anyfunc"}),v=!1;function assert(a,b){a||u("Assertion failed: "+b)}
function za(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=Aa(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)w[a>>2]=0;for(b=d+c;a<b;)x[a++>>0]=0;return d}a.subarray||a.slice?z.set(a,d):z.set(new Uint8Array(a),d);return d}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function B(a,b){return a?Ca(z,a,b):""}
function Da(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Fa(a){var b=Ea(a)+1,c=Ga(b);Da(a,x,c,b);return c}function Ha(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,x,z,Ia,Ja,w,Ka,C;
function La(a){buffer=a;k.HEAP8=x=new Int8Array(a);k.HEAP16=Ia=new Int16Array(a);k.HEAP32=w=new Int32Array(a);k.HEAPU8=z=new Uint8Array(a);k.HEAPU16=Ja=new Uint16Array(a);k.HEAPU32=Ka=new Uint32Array(a);k.HEAPF32=C=new Float32Array(a);k.HEAPF64=new Float64Array(a)}var Ma=k.TOTAL_MEMORY||67108864;k.wasmMemory?xa=k.wasmMemory:xa=new WebAssembly.Memory({initial:Ma/65536});xa&&(buffer=xa.buffer);Ma=buffer.byteLength;La(buffer);w[12771388]=56328592;
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.C;"number"===typeof c?void 0===b.H?k.dynCall_v(c):k.dynCall_vi(c,b.H):c(void 0===b.H?null:b.H)}}}var Oa=[],Pa=[],Qa=[],Ra=[],Sa=[],Ta=!1;function Ua(){var a=k.preRun.shift();Oa.unshift(a)}var Va=Math.abs,Wa=Math.ceil,Xa=Math.floor,Ya=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;k.monitorRunDependencies&&k.monitorRunDependencies(Za)}
function cb(){Za--;k.monitorRunDependencies&&k.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}k.preloadedImages={};k.preloadedAudios={};function u(a){if(k.onAbort)k.onAbort(a);qa(a);l(a);v=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}function db(){var a=eb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var eb="Sample7.wasm";
if(!db()){var fb=eb;eb=k.locateFile?k.locateFile(fb,q):q+fb}function gb(){try{if(va)return new Uint8Array(va);if(ma)return ma(eb);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}function hb(){return va||!fa&&!m||"function"!==typeof fetch?new Promise(function(a){a(gb())}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return gb()})}var E,ib;Pa.push({C:function(){jb()}});
function kb(a,b){f.b.ra=a;f.b.sa=b;if(f.b.C)if(0==a)f.b.K=function(){var a=Math.max(0,f.b.Ob+b-lb())|0;setTimeout(f.b.qa,a)},f.b.method="timeout";else if(1==a)f.b.K=function(){f.requestAnimationFrame(f.b.qa)},f.b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);m?(void 0===k.setImmediates&&(k.setImmediates=
[]),k.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}f.b.K=function(){setImmediate(f.b.qa)};f.b.method="immediate"}}function lb(){u()}
function mb(a,b,c,d,e){wa=!0;assert(!f.b.C,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");f.b.C=a;f.b.H=d;var g="undefined"!==typeof d?function(){k.dynCall_vi(a,d)}:function(){k.dynCall_v(a)};var h=f.b.M;f.b.qa=function(){if(!v)if(0<f.b.hb.length){var a=Date.now(),b=f.b.hb.shift();b.C(b.H);if(f.b.Ka){var c=f.b.Ka,d=0==c%1?c-1:Math.floor(c);f.b.Ka=b.pe?d:(8*
c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");f.b.Ub();h<f.b.M||setTimeout(f.b.qa,0)}else h<f.b.M||(f.b.za=f.b.za+1|0,1==f.b.ra&&1<f.b.sa&&0!=f.b.za%f.b.sa?f.b.K():(0==f.b.ra&&(f.b.Ob=lb()),"timeout"===f.b.method&&k.ga&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),f.b.method=
""),f.b.Gb(g),h<f.b.M||f.b.K()))};e||(b&&0<b?kb(0,1E3/b):kb(1,1),f.b.K());if(c)throw"SimulateInfiniteLoop";}
f={b:{K:null,method:"",M:0,C:null,H:0,ra:0,sa:0,za:0,hb:[],pause:function(){f.b.K=null;f.b.M++},resume:function(){f.b.M++;var a=f.b.ra,b=f.b.sa,c=f.b.C;f.b.C=null;mb(c,0,!1,f.b.H,!0);kb(a,b);f.b.K()},Ub:function(){if(k.setStatus){var a=k.statusMessage||"Please wait...",b=f.b.Ka,c=f.b.se;b?b<c?k.setStatus(a+" ("+(c-b)+"/"+c+")"):k.setStatus(a):k.setStatus("")}},Gb:function(a){if(!(v||k.preMainLoop&&!1===k.preMainLoop())){try{a()}catch(b){if(b instanceof pa)return;b&&"object"===typeof b&&b.stack&&l("exception thrown: "+
[b,b.stack]);throw b;}k.postMainLoop&&k.postMainLoop()}}},W:!1,Ha:!1,Cb:[],workers:[],Ya:function(){function a(){f.Ha=document.pointerLockElement===k.canvas||document.mozPointerLockElement===k.canvas||document.webkitPointerLockElement===k.canvas||document.msPointerLockElement===k.canvas}k.preloadPlugins||(k.preloadPlugins=[]);if(!f.yb){f.yb=!0;try{f.ia=!0}catch(c){f.ia=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}f.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:f.ia?null:console.log("warning: no BlobBuilder");f.ea="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;k.fb||"undefined"!==typeof f.ea||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),k.fb=!0);k.preloadPlugins.push({canHandle:function(a){return!k.fb&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,e,g){var c=null;if(f.ia)try{c=
new Blob([a],{type:f.Ca(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:f.Ca(b)}))}catch(t){ra("Blob constructor present but fails: "+t+"; falling back to blob builder")}c||(c=new f.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=f.ea.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,0,0);k.preloadedImages[b]=
c;f.ea.revokeObjectURL(d);e&&e(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};p.src=d}});k.preloadPlugins.push({canHandle:function(a){return!k.Ce&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,g){function c(c){p||(p=!0,k.preloadedAudios[b]=c,e&&e(a))}function d(){p||(p=!0,k.preloadedAudios[b]=new Audio,g&&g())}var p=!1;if(f.ia){try{var t=new Blob([a],{type:f.Ca(b)})}catch(A){return d()}t=f.ea.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",
function(){c(r)},!1);r.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,g=0,h=0;h<a.length;h++)for(e=e<<8|a[h],g+=8;6<=g;){var n=e>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&15)<<2],d+="=");r.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(r)}};r.src=t;f.Hb(function(){c(r)},1E4)}else return d()}});var b=k.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),k.elementPointerLock&&b.addEventListener("click",function(a){!f.Ha&&k.canvas.requestPointerLock&&(k.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&k.ga&&a==k.canvas)return k.ga;var e;if(b){var g={antialias:!1,alpha:!1,ab:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof nb&&(e=ob(a,
g)))var n=pb[e].wa}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof F,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),k.ga=n,b&&qb(e),k.Oe=b,f.Cb.forEach(function(a){a()}),f.Ya());return n},qe:function(){},Ua:!1,ka:void 0,S:void 0,requestFullscreen:function(a,b,c){function d(){f.W=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=f.exitFullscreen,f.ka&&e.requestPointerLock(),f.W=!0,f.S?f.Lb():f.da(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),f.S?f.Mb():f.da(e));if(k.onFullScreen)k.onFullScreen(f.W);if(k.onFullscreen)k.onFullscreen(f.W)}f.ka=a;f.S=b;f.kb=c;"undefined"===typeof f.ka&&(f.ka=!0);"undefined"===typeof f.S&&(f.S=!1);"undefined"===typeof f.kb&&(f.kb=null);var e=k.canvas;f.Ua||(f.Ua=!0,document.addEventListener("fullscreenchange",d,!1),
document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");e.parentNode.insertBefore(g,e);g.appendChild(e);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?g.requestFullscreen({Pe:c}):g.requestFullscreen()},ib:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");f.ib=function(a,b,c){return f.requestFullscreen(a,b,c)};return f.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!f.W)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},P:0,rb:function(a){var b=
Date.now();if(0===f.P)f.P=b+1E3/60;else for(;b+2>=f.P;)f.P+=1E3/60;setTimeout(a,Math.max(f.P-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=f.rb;b(a)}},Je:function(a){return function(){if(!v)return a.apply(null,arguments)}},U:!0,aa:[],De:function(){f.U=!1},Ie:function(){f.U=!0;if(0<f.aa.length){var a=f.aa;f.aa=[];a.forEach(function(a){a()})}},Ke:function(a){return f.requestAnimationFrame(function(){v||(f.U?a():f.aa.push(a))})},
Hb:function(a,b){wa=!0;return setTimeout(function(){v||(f.U?a():f.aa.push(a))},b)},Le:function(a,b){wa=!0;return setInterval(function(){v||f.U&&a()},b)},Ca:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},ub:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},vb:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},we:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},na:0,oa:0,la:0,ma:0,touches:{},Za:{},
oe:function(a){if(f.Ha)"mousemove"!=a.type&&"mozMovementX"in a?f.la=f.ma=0:(f.la=f.ub(a),f.ma=f.vb(a)),f.na+=f.la,f.oa+=f.ma;else{var b=k.canvas.getBoundingClientRect(),c=k.canvas.width,d=k.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var h=a.Ne;if(void 0!==h)if(e=h.pageX-(e+b.left),g=h.pageY-(g+b.top),e*=c/b.width,g*=
d/b.height,b={x:e,y:g},"touchstart"===a.type)f.Za[h.identifier]=b,f.touches[h.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=f.touches[h.identifier])||(a=b),f.Za[h.identifier]=a,f.touches[h.identifier]=b}else h=a.pageX-(e+b.left),a=a.pageY-(g+b.top),h*=c/b.width,a*=d/b.height,f.la=h-f.na,f.ma=a-f.oa,f.na=h,f.oa=a}},ob:function(a,b,c,d){var e=d?"":"al "+a;la(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&cb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&bb(e)},Fb:[],La:function(){var a=k.canvas;f.Fb.forEach(function(b){b(a.width,a.height)})},Ib:function(a,b,c){f.da(k.canvas,a,b);c||f.La()},Te:0,Se:0,Lb:function(){f.da(k.canvas);f.La()},Mb:function(){f.da(k.canvas);f.La()},da:function(a,b,c){b&&c?(a.Vb=b,a.wb=c):(b=a.Vb,c=a.wb);var d=b,e=c;k.forcedAspectRatio&&0<k.forcedAspectRatio&&(d/e<k.forcedAspectRatio?d=Math.round(e*k.forcedAspectRatio):e=Math.round(d/k.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}f.S?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Re:{},eb:0,xe:function(){var a=f.eb;f.eb++;return a}};var rb=0,sb=0,G=[],tb=[],ub=null,vb=null,wb=[],xb=0,I=null;
function yb(a,b,c,d,e){var g=[];d.l=0;d.Ba=0;if(-1!=b.search("\n")){b=b.split("\n");for(var h=0;h<b.length;h++){var n={l:0,Ba:0};var p=yb(a,b[h],c,n,e);n.l>d.l&&(d.l=n.l);g.push(p);if(e)for(;g.length>e;)g.pop()}}else if(c){e=b.split(" ");b=0;h=e[b];p="";n=0;for(var t;b<e.length;)t=a.measureText(h).width,t>c?(0==n?(g.push(h),p="",n=0,b++):(n>d.l&&(d.l=n),g.push(p),n=0,p=""),h=e[b]):(b++,n=t,p=h,h+=" ",h+=e[b]);n&&(g.push(p),n>d.l&&(d.l=n))}else g.push(b),d.l=a.measureText(b).width;c&&d.l>c&&(d.l=c);
d.Ba=g.length;return g}var zb={};function Ab(a){k.___errno_location&&(w[k.___errno_location()>>2]=a)}function Bb(a,b){if(0===a)a=Date.now();else if(1===a&&(ha||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=lb();else return Ab(28),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0}function Cb(a,b){Ra.unshift({C:a,H:b})}
function Db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Db(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Gb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Hb(){var a=Array.prototype.slice.call(arguments,0);return Eb(a.join("/"))}function J(a,b){return Eb(a+"/"+b)}
function Ib(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Db(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function Jb(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=Ib(a).substr(1);b=Ib(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var Kb=[];function Lb(a,b){Kb[a]={input:[],output:[],R:b};Mb(a,Nb)}
var Nb={open:function(a){var b=Kb[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.R.flush(a.tty)},flush:function(a){a.tty.R.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.R.Wa)throw new K(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.R.Wa(a.tty)}catch(n){throw new K(29);}if(void 0===h&&0===e)throw new K(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.R.Ia)throw new K(60);try{for(var e=
0;e<d;e++)a.tty.R.Ia(a.tty,b[c+e])}catch(g){throw new K(29);}d&&(a.node.timestamp=Date.now());return e}},Pb={Wa:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.V?Buffer.V(256):new Buffer(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ob(b,!0)}return a.input.shift()},Ia:function(a,b){null===b||10===b?(qa(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ca(a.output,0)),a.output=[])}},Qb={Ia:function(a,b){null===b||10===b?(l(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ca(a.output,0)),a.output=[])}},L={D:null,m:function(){return L.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.D||(L.D={dir:{node:{v:L.f.v,o:L.f.o,lookup:L.f.lookup,Z:L.f.Z,rename:L.f.rename,unlink:L.f.unlink,rmdir:L.f.rmdir,readdir:L.f.readdir,symlink:L.f.symlink},stream:{I:L.g.I}},file:{node:{v:L.f.v,o:L.f.o},stream:{I:L.g.I,read:L.g.read,write:L.g.write,Ma:L.g.Ma,bb:L.g.bb,pa:L.g.pa}},link:{node:{v:L.f.v,o:L.f.o,readlink:L.f.readlink},stream:{}},Pa:{node:{v:L.f.v,o:L.f.o},stream:Rb}});c=Sb(a,b,c,d);M(c.mode)?(c.f=L.D.dir.node,
c.g=L.D.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=L.D.file.node,c.g=L.D.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=L.D.link.node,c.g=L.D.link.stream):8192===(c.mode&61440)&&(c.f=L.D.Pa.node,c.g=L.D.Pa.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},ue:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},ve:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},Ra:function(a,b){var c=a.c?a.c.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))},Eb:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{v:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=
0;b.gid=0;b.rdev=a.rdev;M(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.L=4096;b.blocks=Math.ceil(b.size/b.L);return b},o:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.Eb(a,b.size)},lookup:function(){throw Tb[44];},Z:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,
b,c){if(M(a.mode)){try{var d=Ub(b,c)}catch(g){}if(d)for(var e in d.c)throw new K(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=Ub(a,b),d;for(d in c.c)throw new K(55);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},
g:{read:function(a,b,c,d,e){var g=a.node.c;if(e>=a.node.h)return 0;a=Math.min(a.node.h-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===e)return a.c=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(e+d<=a.h)return a.c.set(b.subarray(c,c+d),e),d}L.Ra(a,e+d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.c[e+g]=b[c+g];a.h=Math.max(a.h,e+d);return d},I:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new K(28);return b},Ma:function(a,b,c){L.Ra(a.node,b+c);a.node.h=Math.max(a.node.h,b+c)},bb:function(a,b,c,d,e,g,h){if(32768!==(a.node.mode&61440))throw new K(43);c=a.node.c;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<e||e+d<a.node.h)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==
x.buffer;d=Aa(d);if(!d)throw new K(48);(e?x:b).set(c,d)}else a=!1,d=c.byteOffset;return{Fe:d,nb:a}},pa:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new K(43);if(e&2)return 0;L.g.write(a,b,0,d,c,!1);return 0}}},Vb={Od:63,nd:44,ae:71,Ic:27,Kc:29,Kd:60,Wb:1,od:45,ec:8,oc:12,bc:6,ke:6,sd:48,Xb:2,Bc:21,Bd:105,mc:10,Ac:20,le:75,md:43,Dd:54,Mc:31,Jc:28,gd:41,Yc:33,Id:59,he:74,Cc:22,xd:51,$d:70,Xd:69,Zc:34,Qd:64,xc:18,Ud:68,td:49,Fc:24,pc:106,Oc:156,Pc:107,Qc:108,Wc:109,ie:110,kd:111,Nc:112,uc:16,
pd:46,dc:113,ic:114,me:115,hd:104,jc:103,kc:102,vc:16,lc:101,zd:100,ld:116,ee:117,yd:118,ud:119,vd:120,Wd:121,qd:47,$b:122,be:123,qc:124,Rd:65,ad:36,yc:125,hc:9,Jd:126,fc:127,Vd:128,Rc:129,Sc:130,Vc:131,Uc:132,Tc:133,Ad:52,Ed:55,bd:37,Xc:32,Ld:138,Pd:139,tc:15,jd:42,ac:5,Td:67,Gd:57,wd:50,Yd:140,sc:14,Yb:3,rc:13,ed:40,cd:38,fe:73,Dc:142,Ec:23,Hc:26,cc:7,wc:17,$c:35,Sd:66,Zd:137,Zb:4,dd:39,Lc:30,Cd:53,ge:141,je:136,zc:19,ce:72,Hd:138,rd:148,Gc:25,Md:61,nc:11,Fd:56,Nd:62,de:135},N={ja:!1,Nb:function(){N.ja=
!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);N.Sa={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Na:function(a){return Buffer.alloc?Buffer.from(a):new Buffer(a)},j:function(a){a=a.code;assert(a in Vb);return Vb[a]},m:function(a){assert(ia);return N.createNode(null,"/",N.Va(a.Ga.root),0)},createNode:function(a,b,c){if(!M(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new K(28);a=Sb(a,b,c);a.f=N.f;a.g=
N.g;return a},Va:function(a){try{var b=fs.lstatSync(a);N.ja&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new K(N.j(c));}return b.mode},u:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.m.Ga.root);b.reverse();return Hb.apply(null,b)},tb:function(a){a&=-2656257;var b=0,c;for(c in N.Sa)a&c&&(b|=N.Sa[c],a^=c);if(a)throw new K(28);return b},f:{v:function(a){a=N.u(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new K(N.j(c));}N.ja&&!b.L&&(b.L=
4096);N.ja&&!b.blocks&&(b.blocks=(b.size+b.L-1)/b.L|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,L:b.L,blocks:b.blocks}},o:function(a,b){var c=N.u(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new K(N.j(d));}},lookup:function(a,b){var c=J(N.u(a),b);c=N.Va(c);return N.createNode(a,b,c)},Z:function(a,b,c,d){a=N.createNode(a,
b,c,d);b=N.u(a);try{M(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(e){if(!e.code)throw e;throw new K(N.j(e));}return a},rename:function(a,b,c){a=N.u(a);b=J(N.u(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new K(N.j(d));}},unlink:function(a,b){a=J(N.u(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new K(N.j(c));}},rmdir:function(a,b){a=J(N.u(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new K(N.j(c));}},readdir:function(a){a=
N.u(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new K(N.j(b));}},symlink:function(a,b,c){a=J(N.u(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new K(N.j(d));}},readlink:function(a){var b=N.u(a);try{return b=fs.readlinkSync(b),b=Wb.relative(Wb.resolve(a.m.Ga.root),b)}catch(c){if(!c.code)throw c;throw new K(N.j(c));}}},g:{open:function(a){var b=N.u(a.node);try{32768===(a.node.mode&61440)&&(a.$=fs.openSync(b,N.tb(a.flags)))}catch(c){if(!c.code)throw c;throw new K(N.j(c));
}},close:function(a){try{32768===(a.node.mode&61440)&&a.$&&fs.closeSync(a.$)}catch(b){if(!b.code)throw b;throw new K(N.j(b));}},read:function(a,b,c,d,e){if(0===d)return 0;try{return fs.readSync(a.$,N.Na(b.buffer),c,d,e)}catch(g){throw new K(N.j(g));}},write:function(a,b,c,d,e){try{return fs.writeSync(a.$,N.Na(b.buffer),c,d,e)}catch(g){throw new K(N.j(g));}},I:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.$).size}catch(d){throw new K(N.j(d));
}if(0>b)throw new K(28);return b}}},Xb=null,Yb={},Zb=[],$b=1,ac=null,bc=!0,O={},K=null,Tb={};
function P(a,b){a=Ib("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ta:!0,Ja:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ja)throw new K(32);a=Db(a.split("/").filter(function(a){return!!a}),!1);var e=Xb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=Ub(e,a[d]);c=J(c,a[d]);e.J&&(!g||g&&b.Ta)&&(e=e.J.root);if(!g||b.ha)for(g=0;40960===(e.mode&61440);)if(e=cc(c),c=Ib(Fb(c),e),e=P(c,{Ja:b.Ja}).node,40<g++)throw new K(32);}return{path:c,node:e}}
function Q(a){for(var b;;){if(a===a.parent)return a=a.m.cb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function dc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ac.length}function ec(a){var b=dc(a.parent.id,a.name);a.O=ac[b];ac[b]=a}function fc(a){var b=dc(a.parent.id,a.name);if(ac[b]===a)ac[b]=a.O;else for(b=ac[b];b;){if(b.O===a){b.O=a.O;break}b=b.O}}
function Ub(a,b){var c;if(c=(c=hc(a,"x"))?c:a.f.lookup?0:2)throw new K(c,a);for(c=ac[dc(a.id,b)];c;c=c.O){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.lookup(a,b)}
function Sb(a,b,c,d){ic||(ic=function(a,b,c,d){a||(a=this);this.parent=a;this.m=a.m;this.J=null;this.id=$b++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=d},ic.prototype={},Object.defineProperties(ic.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Bb:{get:function(){return M(this.mode)}},Ab:{get:function(){return 8192===(this.mode&
61440)}}}));a=new ic(a,b,c,d);ec(a);return a}function M(a){return 16384===(a&61440)}var jc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function kc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function hc(a,b){if(bc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function lc(a,b){try{return Ub(a,b),20}catch(c){}return hc(a,"wx")}function mc(a,b,c){try{var d=Ub(a,b)}catch(e){return e.i}if(a=hc(a,"wx"))return a;if(c){if(!M(d.mode))return 54;if(d===d.parent||"/"===Q(d))return 10}else if(M(d.mode))return 31;return 0}function nc(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!Zb[a])return a;throw new K(33);}
function oc(a,b,c){pc||(pc=function(){},pc.prototype={},Object.defineProperties(pc.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var d=new pc,e;for(e in a)d[e]=a[e];a=d;b=nc(b,c);a.fd=b;return Zb[b]=a}var Rb={open:function(a){a.g=Yb[a.node.rdev].g;a.g.open&&a.g.open(a)},I:function(){throw new K(70);}};function Mb(a,b){Yb[a]={g:b}}
function qc(a,b){var c="/"===b,d=!b;if(c&&Xb)throw new K(10);if(!c&&!d){var e=P(b,{Ta:!1});b=e.path;e=e.node;if(e.J)throw new K(10);if(!M(e.mode))throw new K(54);}b={type:a,Ga:{},cb:b,Db:[]};a=a.m(b);a.m=b;b.root=a;c?Xb=a:e&&(e.J=b,e.m&&e.m.Db.push(b))}function rc(a,b,c){var d=P(a,{parent:!0}).node;a=Gb(a);if(!a||"."===a||".."===a)throw new K(28);var e=lc(d,a);if(e)throw new K(e);if(!d.f.Z)throw new K(63);return d.f.Z(d,a,b,c)}function R(a,b){return rc(a,(void 0!==b?b:511)&1023|16384,0)}
function sc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return rc(a,b|8192,c)}function tc(a,b){if(!Ib(a))throw new K(44);var c=P(b,{parent:!0}).node;if(!c)throw new K(44);b=Gb(b);var d=lc(c,b);if(d)throw new K(d);if(!c.f.symlink)throw new K(63);return c.f.symlink(c,b,a)}
function uc(a){var b=P(a,{parent:!0}).node,c=Gb(a),d=Ub(b,c),e=mc(b,c,!1);if(e)throw new K(e);if(!b.f.unlink)throw new K(63);if(d.J)throw new K(10);try{O.willDeletePath&&O.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.f.unlink(b,c);fc(d);try{if(O.onDeletePath)O.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function cc(a){a=P(a).node;if(!a)throw new K(44);if(!a.f.readlink)throw new K(28);return Ib(Q(a.parent),a.f.readlink(a))}function vc(a,b){a=P(a,{ha:!b}).node;if(!a)throw new K(44);if(!a.f.v)throw new K(63);return a.f.v(a)}function wc(a){return vc(a,!0)}function xc(a,b){var c;"string"===typeof a?c=P(a,{ha:!0}).node:c=a;if(!c.f.o)throw new K(63);c.f.o(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function yc(a,b,c,d,e){if(""===a)throw new K(44);if("string"===typeof b){var g=jc[b];if("undefined"===typeof g)throw Error("Unknown file open mode: "+b);b=g}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=Eb(a);try{h=P(a,{ha:!(b&131072)}).node}catch(p){}}g=!1;if(b&64)if(h){if(b&128)throw new K(20);}else h=rc(a,c,0),g=!0;if(!h)throw new K(44);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&!M(h.mode))throw new K(54);if(!g&&(c=h?40960===(h.mode&61440)?32:M(h.mode)&&
("r"!==kc(b)||b&512)?31:hc(h,kc(b)):44))throw new K(c);if(b&512){c=h;var n;"string"===typeof c?n=P(c,{ha:!0}).node:n=c;if(!n.f.o)throw new K(63);if(M(n.mode))throw new K(31);if(32768!==(n.mode&61440))throw new K(28);if(c=hc(n,"w"))throw new K(c);n.f.o(n,{size:0,timestamp:Date.now()})}b&=-641;d=oc({node:h,path:Q(h),flags:b,seekable:!0,position:0,g:h.g,Tb:[],error:!1},d,e);d.g.open&&d.g.open(d);!k.logReadFiles||b&1||(zc||(zc={}),a in zc||(zc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{O.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),O.onOpenFile(a,e))}catch(p){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d}function Ac(a){if(null===a.fd)throw new K(8);a.Da&&(a.Da=null);try{a.g.close&&a.g.close(a)}catch(b){throw b;}finally{Zb[a.fd]=null}a.fd=null}
function Bc(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.g.I)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.g.I(a,b,c);a.Tb=[]}
function Cc(a,b,c,d,e,g){if(0>d||0>e)throw new K(28);if(null===a.fd)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(M(a.node.mode))throw new K(31);if(!a.g.write)throw new K(28);a.flags&1024&&Bc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new K(70);b=a.g.write(a,b,c,d,e,g);h||(a.position+=b);try{if(a.path&&O.onWriteToFile)O.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+n.message)}return b}
function Dc(){K||(K=function(a,b){this.node=b;this.Kb=function(a){this.i=a};this.Kb(a);this.message="FS error"},K.prototype=Error(),K.prototype.constructor=K,[44].forEach(function(a){Tb[a]=new K(a);Tb[a].stack="<generic error, no stack>"}))}var Ec;function Fc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Gc(a,b,c,d){a=J("string"===typeof a?a:Q(a),b);return R(a,Fc(c,d))}
function Hc(a,b){a="string"===typeof a?a:Q(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=J(a,c);try{R(d)}catch(e){}a=d}}return d}function Ic(a,b,c,d){a=J("string"===typeof a?a:Q(a),b);c=Fc(c,d);return rc(a,(void 0!==c?c:438)&4095|32768,0)}
function Jc(a,b,c,d,e,g){a=b?J("string"===typeof a?a:Q(a),b):a;d=Fc(d,e);e=rc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}xc(e,d|146);a=yc(e,"w");Cc(a,c,0,c.length,0,g);Ac(a);xc(e,d)}return e}
function S(a,b,c,d){a=J("string"===typeof a?a:Q(a),b);b=Fc(!!c,!!d);S.$a||(S.$a=64);var e=S.$a++<<8|0;Mb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var g=0,h=0;h<e;h++){try{var p=c()}catch(D){throw new K(29);}if(void 0===p&&0===g)throw new K(6);if(null===p||void 0===p)break;g++;b[d+h]=p}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,e){for(var g=0;g<e;g++)try{d(b[c+g])}catch(r){throw new K(29);}e&&(a.node.timestamp=
Date.now());return g}});return sc(a,b,e)}function Kc(a,b,c){a=J("string"===typeof a?a:Q(a),b);return tc(c,a)}
function Lc(a){if(a.Ab||a.Bb||a.link||a.c)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.c=Ob(ka(a.url),!0),a.h=a.c.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||Ab(29);return b}
function Mc(a,b,c,d,e){function g(){this.Ea=!1;this.fa=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Xa(a/this.chunkSize|0)[b]}};g.prototype.Jb=function(a){this.Xa=a};g.prototype.Oa=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;e||(g=b);var h=this;h.Jb(function(a){var d=a*g,e=(a+1)*g-1;e=Math.min(e,b-1);if("undefined"===typeof h.fa[a]){var y=h.fa;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==g&&p.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):Ob(p.responseText||"",!0);y[a]=d}if("undefined"===typeof h.fa[a])throw Error("doXHR failed!");return h.fa[a]});if(a||!b)g=b=1,g=b=this.Xa(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.mb=b;this.lb=
g;this.Ea=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Ea||this.Oa();return this.mb}},chunkSize:{get:function(){this.Ea||this.Oa();return this.lb}}});var n=void 0}else n=c,h=void 0;var p=Ic(a,b,d,e);h?p.c=h:n&&(p.c=null,p.url=n);Object.defineProperties(p,{h:{get:function(){return this.c.length}}});var t={};
Object.keys(p.g).forEach(function(a){var b=p.g[a];t[a]=function(){if(!Lc(p))throw new K(29);return b.apply(null,arguments)}});t.read=function(a,b,c,d,e){if(!Lc(p))throw new K(29);a=a.node.c;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[e+g];else for(g=0;g<d;g++)b[c+g]=a.get(e+g);return d};p.g=t;return p}
function Nc(a,b,c,d,e,g,h,n,p,t){function r(c){function y(c){t&&t();n||Jc(a,b,c,d,e,p);g&&g();cb(D)}var r=!1;k.preloadPlugins.forEach(function(a){!r&&a.canHandle(A)&&(a.handle(c,A,y,function(){h&&h();cb(D)}),r=!0)});r||y(c)}f.Ya();var A=b?Ib(J(a,b)):a,D="cp "+A;bb(D);"string"==typeof c?f.ob(c,function(a){r(a)},h):r(c)}var T={},ic,pc,zc,Oc={};
function Pc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&Eb(b)!==Eb(Q(e.node)))return-54;throw e;}w[c>>2]=d.dev;w[c+4>>2]=0;w[c+8>>2]=d.ino;w[c+12>>2]=d.mode;w[c+16>>2]=d.nlink;w[c+20>>2]=d.uid;w[c+24>>2]=d.gid;w[c+28>>2]=d.rdev;w[c+32>>2]=0;ib=[d.size>>>0,(E=d.size,1<=+Va(E)?0<E?(Ya(+Xa(E/4294967296),4294967295)|0)>>>0:~~+Wa((E-+(~~E>>>0))/4294967296)>>>0:0)];w[c+40>>2]=ib[0];w[c+44>>2]=ib[1];w[c+48>>2]=4096;w[c+52>>2]=d.blocks;w[c+56>>2]=d.atime.getTime()/1E3|0;w[c+60>>2]=0;w[c+64>>2]=d.mtime.getTime()/
1E3|0;w[c+68>>2]=0;w[c+72>>2]=d.ctime.getTime()/1E3|0;w[c+76>>2]=0;ib=[d.ino>>>0,(E=d.ino,1<=+Va(E)?0<E?(Ya(+Xa(E/4294967296),4294967295)|0)>>>0:~~+Wa((E-+(~~E>>>0))/4294967296)>>>0:0)];w[c+80>>2]=ib[0];w[c+84>>2]=ib[1];return 0}function Qc(a,b,c){var d=Zb[c];d&&Ac(d);return yc(a,b,0,c,c).fd}var U=0;function V(){U+=4;return w[U-4>>2]}function Rc(){return B(V())}function Sc(a){void 0===a&&(a=V());a=Zb[a];if(!a)throw new K(8);return a}
function Tc(){void 0===Tc.start&&(Tc.start=Date.now());return 1E3*(Date.now()-Tc.start)|0}var Uc=1,Vc=0,Wc=[],W=[],Xc=[],Yc=[],Zc=[],Y=[],$c=[],pb={},ad=null,bd={},cd={},dd=4;function Z(a){Vc||(Vc=a)}function ed(a){for(var b=Uc++,c=a.length;c<b;c++)a[c]=null;return b}var fd=null,gd=[0];
function ob(a,b){if(a=a.getContext("webgl",b)||a.getContext("experimental-webgl",b)){var c=Aa(8),d={handle:c,attributes:b,version:b.ab,wa:a};a.canvas&&(a.canvas.ne=d);pb[c]=d;("undefined"===typeof b.Qa||b.Qa)&&hd(d);b=c}else b=0;return b}function qb(a){ad=pb[a];k.ga=F=ad&&ad.wa;return!(a&&!F)}
function id(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,g){b.drawArraysInstancedANGLE(a,d,e,g)},a.drawElementsInstanced=function(a,d,e,g,h){b.drawElementsInstancedANGLE(a,d,e,g,h)})}
function jd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function kd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function hd(a){a||(a=ad);if(!a.xb){a.xb=!0;var b=a.wa;2>a.version&&(id(b),jd(b),kd(b));b.re=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var nb={},ld,md,nd=["default","low-power","high-performance"],od=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function pd(a){try{if(!a)return window;"number"===typeof a&&(a=od[a]||B(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?k.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var qd={};
function rd(){if(!sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in qd)a[b]=qd[b];var c=[];for(b in a)c.push(b+"="+a[b]);sd=c}return sd}var sd;function td(a,b,c,d){for(var e=0;e<a;e++){var g=F[c](),h=g&&ed(d);g?(g.name=h,d[h]=g):Z(1282);w[b+4*e>>2]=h}}
function ud(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=F.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=F.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Z(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Z(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Z(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Z(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}w[b>>2]=c}else Z(1281)}
var vd={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},wd={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};function xd(a,b,c,d,e){if(b=vd[b]*wd[a]){var g=dd;c=e+d*(c*b+g-1&-g);switch(a){case 5121:return z.subarray(e,c);case 5126:return C.subarray(e>>2,c>>2);case 5125:case 34042:return Ka.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return Ja.subarray(e>>1,c>>1);default:Z(1280)}}else Z(1280)}var yd=(Da("GMT",z,51085616,4),51085616);
function zd(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Ad){Ad=!0;w[Bd()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);w[Cd()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),e=a(b);d=za(Ob(d));e=za(Ob(e));b.getTimezoneOffset()<c.getTimezoneOffset()?(w[Dd()>>2]=d,w[Dd()+4>>2]=e):(w[Dd()>>2]=e,w[Dd()+4>>2]=d)}}var Ad;function Ed(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Fd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Gd=[31,29,31,30,31,30,31,31,30,31,30,31],Hd=[31,28,31,30,31,30,31,31,30,31,30,31];function Id(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ed(a.getFullYear())?Gd:Hd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Jd(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return e(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=Id(new Date(a.s+1900,0,1),a.va);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=h(n(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var t=w[d+40>>2];d={Rb:w[d>>2],Qb:w[d+4>>2],ta:w[d+8>>2],ba:w[d+12>>2],T:w[d+16>>2],s:w[d+20>>2],ua:w[d+24>>2],va:w[d+28>>2],Me:w[d+32>>2],Pb:w[d+36>>2],Sb:t?
B(t):""};c=B(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
D="January February March April May June July August September October November December".split(" ");t={"%a":function(a){return A[a.ua].substring(0,3)},"%A":function(a){return A[a.ua]},"%b":function(a){return D[a.T].substring(0,3)},"%B":function(a){return D[a.T]},"%C":function(a){return g((a.s+1900)/100|0,2)},"%d":function(a){return g(a.ba,2)},"%e":function(a){return e(a.ba,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return g(a.ta,2)},
"%I":function(a){a=a.ta;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.ba+Fd(Ed(a.s+1900)?Gd:Hd,a.T-1),3)},"%m":function(a){return g(a.T+1,2)},"%M":function(a){return g(a.Qb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.ta&&12>a.ta?"AM":"PM"},"%S":function(a){return g(a.Rb,2)},"%t":function(){return"\t"},"%u":function(a){return a.ua||7},"%U":function(a){var b=new Date(a.s+1900,0,1),c=0===b.getDay()?b:Id(b,7-b.getDay());a=new Date(a.s+1900,a.T,a.ba);return 0>h(c,
a)?g(Math.ceil((31-c.getDate()+(Fd(Ed(a.getFullYear())?Gd:Hd,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.s+1900,0,4)),c=n(new Date(a.s+1901,0,4)),d=Id(new Date(a.s+1900,0,1),a.va);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.s+1900?a.va+32-b.getDate():a.va+1-b.getDate())/7),2)},"%w":function(a){return a.ua},"%W":function(a){var b=new Date(a.s,0,1),c=1===b.getDay()?b:Id(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.s+1900,
a.T,a.ba);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Fd(Ed(a.getFullYear())?Gd:Hd,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.s+1900).toString().substring(2)},"%Y":function(a){return a.s+1900},"%z":function(a){a=a.Pb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Sb},"%%":function(){return"%"}};for(r in t)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=Ob(c,!1);if(r.length>b)return 0;
x.set(r,a);return r.length-1}k.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");k.requestFullScreen=k.requestFullscreen;f.ib(a,b,c)};k.requestFullscreen=function(a,b,c){f.requestFullscreen(a,b,c)};k.requestAnimationFrame=function(a){f.requestAnimationFrame(a)};k.setCanvasSize=function(a,b,c){f.Ib(a,b,c)};k.pauseMainLoop=function(){f.b.pause()};k.resumeMainLoop=function(){f.b.resume()};k.getUserMedia=function(){f.getUserMedia()};
k.createContext=function(a,b,c,d){return f.createContext(a,b,c,d)};ha?lb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?lb=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?lb=function(){return performance.now()}:lb=Date.now;Dc();ac=Array(4096);qc(L,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");Mb(259,{read:function(){return 0},write:function(a,b,c,h){return h}});sc("/dev/null",259);Lb(1280,Pb);Lb(1536,Qb);sc("/dev/tty",1280);sc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});S("/dev","random",b);S("/dev","urandom",b);
R("/dev/shm");R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");qc({m:function(){var a=Sb("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=Zb[+c];if(!b)throw new K(8);a={parent:null,m:{cb:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");k.FS_createFolder=Gc;k.FS_createPath=Hc;k.FS_createDataFile=Jc;k.FS_createPreloadedFile=Nc;k.FS_createLazyFile=Mc;k.FS_createLink=Kc;k.FS_createDevice=S;k.FS_unlink=uc;
if(ia){var fs=require("fs"),Wb=require("path");N.Nb()}var F;fd=new Float32Array(256);for(var Kd=0;256>Kd;Kd++)gd[Kd]=fd.subarray(0,Kd+1);function Ob(a,b){var c=Array(Ea(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}
var Od={AddListenerToKeyBoard:function(){window.addEventListener("keydown",function(a){tb.push({A:a.keyCode,B:"1"})},!1);window.addEventListener("keyup",function(a){tb.push({A:a.keyCode,B:"0"})},!1)},AddListenerToMouse:function(){function a(a){0<a.which&&4>a.which&&(G.push({A:a.which,B:"1",F:a.pageX,G:a.pageY}),a.stopImmediatePropagation())}function b(a){0<a.which&&4>a.which&&G.push({A:a.which,B:"2",F:a.pageX,G:a.pageY})}function c(a){G.push({A:"0",B:"3",F:a.pageX,G:a.pageY})}function d(a){a=window.event||
a;G.push({A:"2",B:"3",F:120*Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)),G:""});if(a.preventDefault)a.preventDefault();else return!1}function e(a){rb=a.targetTouches[0].pageX;sb=a.targetTouches[0].pageY;G.push({A:"1",B:"1",F:rb,G:sb});a.preventDefault()}function g(a){G.push({A:"1",B:"2",F:rb,G:sb});a.preventDefault()}var h=k.canvas;if(function(){var a="ontouchstart"in document.createElement("div");return window.navigator.msMaxTouchPoints||a?!0:!1}())h.addEventListener("touchstart",e,!1),window.addEventListener("touchend",
g,!1),h.addEventListener("touchmove",function(a){rb=a.targetTouches[0].pageX;sb=a.targetTouches[0].pageY;G.push({A:"0",B:"3",F:rb,G:sb});a.preventDefault()},!1);else{var n=/Firefox/i.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel";h.addEventListener("mousedown",a,!1);window.addEventListener("mouseup",b,!1);h.addEventListener("mousemove",c,!1);h.addEventListener(n,d,!1)}},ClearKeyBoardList:function(){tb=[]},ClearMouseList:function(){G=[]},CreateCanvas:function(a,b){a=B(a);0==b?(b=document.createElement("canvas"),
k.canvas.parentElement.appendChild(b),b.id=a,b.style.position="absolute",b.ya=1):(b=k.canvas,b.id=a,b.style.position="absolute",b.ya=1)},GetCanvasPositionX:function(a){a=B(a);return document.getElementById(a).offsetLeft},GetCanvasPositionY:function(a){a=B(a);return document.getElementById(a).offsetTop},GetHTMLBodySizeX:function(){return window.innerWidth},GetHTMLBodySizeY:function(){return window.innerHeight},GetHTMLParentSizeX:function(){return Math.max(k.canvas.parentElement.scrollWidth,k.canvas.parentElement.clientWidth,
k.canvas.parentElement.offsetWidth)},GetHTMLParentSizeY:function(){return Math.max(k.canvas.parentElement.scrollHeight,k.canvas.parentElement.clientHeight,k.canvas.parentElement.offsetHeight)},Get_Key:function(a){return tb[a].A},Get_KeyBoardEvent:function(a){return tb[a].B},Get_KeyBoardEventCount:function(){return tb.length},Get_MouseButton:function(a){return G[a].A},Get_MouseEvent:function(a){return G[a].B},Get_MouseEventCount:function(){return G.length},Get_MousePosX:function(a){return G[a].F},
Get_MousePosY:function(a){return G[a].G},JSDrawMultilineTextUTF16:function(a,b,c,d,e,g,h,n,p,t,r,A,D){d*=.82;r="";a>>=1;for(var y;;){y=Ja[a++];if(0==y)break;r+=String.fromCharCode(y)}a=r;I=document.createElement("canvas");r=I.getContext("2d");e=B(e);e=e.split(".")[0];r.font=d+"px "+e;y={l:0,Ba:0};b=yb(r,a,c,y,b);c=y.l;a=d*b.length;I.width=c;I.height=a;r.font=d+"px "+e;r.fillStyle="rgba("+n+","+p+","+t+",1)";r.textBaseline="middle";2==g?(g=c,r.textAlign="end"):1==g?(r.textAlign="center",g=c/2):(g=
0,r.textAlign="start");for(p=0;p<b.length-h;p++)n=p*d+.5*d,r.fillText(b[p+h],g,n);w[A>>2]=I.width;w[D>>2]=I.height},JSGetLanguage:function(a){var b=window.navigator.language||window.navigator.browserLanguage;x[a]=b.charCodeAt(0);x[a+1]=b.charCodeAt(1)},JSInitImageData:function(a,b,c){var d=I.getContext("2d").getImageData(0,0,b,c);b*=c;for(var e=c=0;e<b;e++)z[a++]=d.data[c++],z[a++]=d.data[c++],z[a++]=d.data[c++],z[a++]=d.data[c++];I=null},JSLoadTextureInCanvas:function(a,b,c){ub.getContext("webgl");
a=Ib(B(a));var d=k.preloadedImages[a];if(!d)return w[b>>2]=0,w[c>>2]=0,null===d&&k.printErr("Trying to reuse preloaded image, but freePreloadedMediaOnUse is set!"),ua.Qe("Cannot find preloaded image "+a),-1;k.freePreloadedMediaOnUse&&(k.preloadedImages[a]=null);I=document.createElement("canvas");a=I.getContext("2d");I.width=d.width;I.height=d.height;w[b>>2]=d.width;w[c>>2]=d.height;a.drawImage(d,0,0,d.width,d.height,0,0,d.width,d.height)},KigsCreateContext:function(a){function b(){}xb=a;null==ub&&
null==zb.Be&&(ub=k.canvas,a?ub.getContext("webgl"):ub.getContext("2d"));var c=!1;f.createContext(k.canvas,xb,!0);window.addEventListener("resize",function(){for(var a=k.canvas,b=a.offsetLeft,c=a.offsetTop,h=0;0>h;h++)if(null!=wb[h]){var n=wb[h].Element;n.style.left=b+wb[h].F+"px";n.style.top=c+wb[h].G+"px"}b=document.getElementById("BtPlayVideo");null!=b&&(b.style.left=a.offsetLeft+0+"px",b.style.top=a.offsetTop+0+"px")},!1);window.addEventListener("haschange",b,!1);window.addEventListener("beforeunload",
b,!1);window.addEventListener("keydown",function(a){a=a||window.event;c||116!=a.keyCode||(window.location.href=window.location.origin,c=!0,a.returnValue=!1,a.preventDefault&&a.preventDefault())},!1);vb=document.createElement("canvas");vb.width=1;vb.height=1},SetAbsolutePos:function(a,b){a=B(a);document.getElementById(a).ya=b},SetCanvasPos:function(a,b,c){a=B(a);a=document.getElementById(a);var d="static"==a.parentElement.position;a.ya?d?(d=a.parentElement.getBoundingClientRect(),a.style.left=d.left+
b+"px",a.style.top=d.top+c+"px"):(a.style.left=b+"px",a.style.top=c+"px"):d?(a.style.left=b+"px",a.style.top=c+"px"):(d=a.parentElement.getBoundingClientRect(),a.style.left=d.left+b+"px",a.style.top=d.top+c+"px")},SetCanvasSize:function(a,b,c){a=B(a);a=document.getElementById(a);a.width=b;a.height=c},__clock_gettime:function(a,b){return Bb(a,b)},__cxa_allocate_exception:function(a){return Aa(a)},__cxa_atexit:function(){return Cb.apply(null,arguments)},__cxa_throw:function(a){"uncaught_exception"in
Ld?Ld.V++:Ld.V=1;throw a;},__lock:function(){},__map_file:function(){Ab(63);return-1},__syscall10:function(a,b){U=b;try{var c=Rc();uc(c);return 0}catch(d){return"undefined"!==typeof T&&d instanceof K||u(d),-d.i}},__syscall195:function(a,b){U=b;try{var c=Rc(),d=V();return Pc(vc,c,d)}catch(e){return"undefined"!==typeof T&&e instanceof K||u(e),-e.i}},__syscall196:function(a,b){U=b;try{var c=Rc(),d=V();return Pc(wc,c,d)}catch(e){return"undefined"!==typeof T&&e instanceof K||u(e),-e.i}},__syscall221:function(a,
b){U=b;try{var c=Sc();switch(V()){case 0:var d=V();return 0>d?-28:yc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=V(),c.flags|=d,0;case 12:return d=V(),Ia[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return Ab(28),-1;default:return-28}}catch(e){return"undefined"!==typeof T&&e instanceof K||u(e),-e.i}},__syscall330:function(a,b){U=b;try{var c=Sc(),d=V();V();return c.fd===d?-28:Qc(c.path,c.flags,d)}catch(e){return"undefined"!==typeof T&&
e instanceof K||u(e),-e.i}},__syscall38:function(a,b){U=b;try{var c=Rc(),d=Rc(),e=Fb(c),g=Fb(d),h=Gb(c),n=Gb(d);try{var p=P(c,{parent:!0});var t=p.node;p=P(d,{parent:!0});var r=p.node}catch(H){throw new K(10);}if(!t||!r)throw new K(44);if(t.m!==r.m)throw new K(75);var A=Ub(t,h),D=Jb(c,g);if("."!==D.charAt(0))throw new K(28);D=Jb(d,e);if("."!==D.charAt(0))throw new K(55);try{var y=Ub(r,n)}catch(H){}if(A!==y){var sa=M(A.mode),X=mc(t,h,sa);if(X)throw new K(X);if(X=y?mc(r,n,sa):lc(r,n))throw new K(X);
if(!t.f.rename)throw new K(63);if(A.J||y&&y.J)throw new K(10);if(r!==t&&(X=hc(t,"w")))throw new K(X);try{O.willMovePath&&O.willMovePath(c,d)}catch(H){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+H.message)}fc(A);try{t.f.rename(A,r,n)}catch(H){throw H;}finally{ec(A)}try{if(O.onMovePath)O.onMovePath(c,d)}catch(H){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+H.message)}}return 0}catch(H){return"undefined"!==typeof T&&
H instanceof K||u(H),-H.i}},__syscall39:function(a,b){U=b;try{var c=Rc(),d=V();a=c;a=Eb(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));R(a,d);return 0}catch(e){return"undefined"!==typeof T&&e instanceof K||u(e),-e.i}},__syscall40:function(a,b){U=b;try{var c=Rc(),d=P(c,{parent:!0}).node,e=Gb(c),g=Ub(d,e),h=mc(d,e,!0);if(h)throw new K(h);if(!d.f.rmdir)throw new K(63);if(g.J)throw new K(10);try{O.willDeletePath&&O.willDeletePath(c)}catch(n){console.log("FS.trackingDelegate['willDeletePath']('"+c+
"') threw an exception: "+n.message)}d.f.rmdir(d,e);fc(g);try{if(O.onDeletePath)O.onDeletePath(c)}catch(n){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+n.message)}return 0}catch(n){return"undefined"!==typeof T&&n instanceof K||u(n),-n.i}},__syscall5:function(a,b){U=b;try{var c=Rc(),d=V(),e=V();return yc(c,d,e).fd}catch(g){return"undefined"!==typeof T&&g instanceof K||u(g),-g.i}},__syscall54:function(a,b){U=b;try{var c=Sc(),d=V();switch(d){case 21509:case 21505:return c.tty?
0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=V();return w[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=V();if(!c.g.zb)throw new K(59);return c.g.zb(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:u("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof T&&g instanceof K||u(g),-g.i}},__syscall63:function(a,b){U=b;try{var c=Sc(),d=V();return c.fd===d?d:Qc(c.path,c.flags,d)}catch(e){return"undefined"!==
typeof T&&e instanceof K||u(e),-e.i}},__syscall91:function(a,b){U=b;try{var c=V(),d=V();if(-1===c||0===d)var e=-28;else{var g=Oc[c];if(g&&d===g.ye){var h=Zb[g.fd],n=g.flags,p=new Uint8Array(z.subarray(c,c+d));h&&h.g.pa&&h.g.pa(h,p,0,d,n);Oc[c]=null;g.nb&&Md(g.ze)}e=0}return e}catch(t){return"undefined"!==typeof T&&t instanceof K||u(t),-t.i}},__unlock:function(){},abort:function(){u()},clock:Tc,clock_gettime:Bb,difftime:function(a,b){return a-b},emscripten_cancel_main_loop:function(){f.b.pause();f.b.C=
null},emscripten_get_sbrk_ptr:function(){return 51085552},emscripten_memcpy_big:function(a,b,c){z.set(z.subarray(b,b+c),a)},emscripten_resize_heap:function(a){if(2147418112<a)return!1;for(var b=Math.max(x.length,16777216);b<a;)536870912>=b?b=Ha(2*b):b=Math.min(Ha((3*b+2147483648)/4),2147418112);a:{try{xa.grow(b-buffer.byteLength+65535>>16);La(xa.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},emscripten_set_main_loop:mb,emscripten_webgl_create_context:function(a,b){var c={};b>>=2;c.alpha=
!!w[b];c.depth=!!w[b+1];c.stencil=!!w[b+2];c.antialias=!!w[b+3];c.premultipliedAlpha=!!w[b+4];c.preserveDrawingBuffer=!!w[b+5];c.powerPreference=nd[w[b+6]];c.failIfMajorPerformanceCaveat=!!w[b+7];c.ab=w[b+8];c.Ae=w[b+9];c.Qa=w[b+10];c.qb=w[b+11];c.Ee=w[b+12];c.He=w[b+13];"number"===typeof a&&(a=B(a));a=a&&"#canvas"!==a?"undefined"!==typeof nb&&bd[a]?bd[a]:pd(a):"undefined"!==typeof nb&&bd.canvas?bd.canvas:k.canvas;return!a||c.qb?0:ob(a,c)},emscripten_webgl_init_context_attributes:function(a){a>>=
2;for(var b=0;14>b;++b)w[a+b]=0;w[a]=w[a+1]=w[a+3]=w[a+4]=w[a+8]=w[a+10]=1},emscripten_webgl_make_context_current:function(a){return qb(a)?0:-5},environ_get:function(a,b){var c=0;rd().forEach(function(d,e){var g=b+c;e=w[a+4*e>>2]=g;for(g=0;g<d.length;++g)x[e++>>0]=d.charCodeAt(g);x[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=rd();w[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});w[b>>2]=d;return 0},exit:function(a){Nd(a)},fd_close:function(a){try{var b=Sc(a);
Ac(b);return 0}catch(c){return"undefined"!==typeof T&&c instanceof K||u(c),c.i}},fd_read:function(a,b,c,d){try{a:{for(var e=Sc(a),g=a=0;g<c;g++){var h=w[b+(8*g+4)>>2],n=e,p=w[b+8*g>>2],t=h,r=void 0,A=x;if(0>t||0>r)throw new K(28);if(null===n.fd)throw new K(8);if(1===(n.flags&2097155))throw new K(8);if(M(n.node.mode))throw new K(31);if(!n.g.read)throw new K(28);var D="undefined"!==typeof r;if(!D)r=n.position;else if(!n.seekable)throw new K(70);var y=n.g.read(n,A,p,t,r);D||(n.position+=y);var sa=y;
if(0>sa){var X=-1;break a}a+=sa;if(sa<h)break}X=a}w[d>>2]=X;return 0}catch(H){return"undefined"!==typeof T&&H instanceof K||u(H),H.i}},fd_seek:function(a,b,c,d,e){try{var g=Sc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Bc(g,a,d);ib=[g.position>>>0,(E=g.position,1<=+Va(E)?0<E?(Ya(+Xa(E/4294967296),4294967295)|0)>>>0:~~+Wa((E-+(~~E>>>0))/4294967296)>>>0:0)];w[e>>2]=ib[0];w[e+4>>2]=ib[1];g.Da&&0===a&&0===d&&(g.Da=null);return 0}catch(h){return"undefined"!==typeof T&&
h instanceof K||u(h),h.i}},fd_write:function(a,b,c,d){try{a:{for(var e=Sc(a),g=a=0;g<c;g++){var h=Cc(e,x,w[b+8*g>>2],w[b+(8*g+4)>>2],void 0);if(0>h){var n=-1;break a}a+=h}n=a}w[d>>2]=n;return 0}catch(p){return"undefined"!==typeof T&&p instanceof K||u(p),p.i}},glActiveTexture:function(a){F.activeTexture(a)},glAttachShader:function(a,b){F.attachShader(W[a],$c[b])},glBindBuffer:function(a,b){F.bindBuffer(a,Wc[b])},glBindFramebuffer:function(a,b){F.bindFramebuffer(a,Xc[b])},glBindRenderbuffer:function(a,
b){F.bindRenderbuffer(a,Yc[b])},glBindTexture:function(a,b){F.bindTexture(a,Zc[b])},glBlendFunc:function(a,b){F.blendFunc(a,b)},glBufferData:function(a,b,c,d){F.bufferData(a,c?z.subarray(c,c+b):b,d)},glCheckFramebufferStatus:function(a){return F.checkFramebufferStatus(a)},glClear:function(a){F.clear(a)},glClearColor:function(a,b,c,d){F.clearColor(a,b,c,d)},glColorMask:function(a,b,c,d){F.colorMask(!!a,!!b,!!c,!!d)},glCompileShader:function(a){F.compileShader($c[a])},glCreateProgram:function(){var a=
ed(W),b=F.createProgram();b.name=a;W[a]=b;return a},glCreateShader:function(a){var b=ed($c);$c[b]=F.createShader(a);return b},glCullFace:function(a){F.cullFace(a)},glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Wc[d];e&&(F.deleteBuffer(e),e.name=0,Wc[d]=null,d==ld&&(ld=0),d==md&&(md=0))}},glDeleteProgram:function(a){if(a){var b=W[a];b?(F.deleteProgram(b),b.name=0,W[a]=null,cd[a]=null):Z(1281)}},glDeleteShader:function(a){if(a){var b=$c[a];b?(F.deleteShader(b),$c[a]=null):Z(1281)}},
glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Zc[d];e&&(F.deleteTexture(e),e.name=0,Zc[d]=null)}},glDepthMask:function(a){F.depthMask(!!a)},glDetachShader:function(a,b){F.detachShader(W[a],$c[b])},glDisable:function(a){F.disable(a)},glDisableVertexAttribArray:function(a){F.disableVertexAttribArray(a)},glDrawArrays:function(a,b,c){F.drawArrays(a,b,c)},glDrawElements:function(a,b,c,d){F.drawElements(a,b,c,d)},glEnable:function(a){F.enable(a)},glEnableVertexAttribArray:function(a){F.enableVertexAttribArray(a)},
glFinish:function(){F.finish()},glFlush:function(){F.flush()},glFramebufferRenderbuffer:function(a,b,c,d){F.framebufferRenderbuffer(a,b,c,Yc[d])},glFramebufferTexture2D:function(a,b,c,d,e){F.framebufferTexture2D(a,b,c,Zc[d],e)},glGenBuffers:function(a,b){td(a,b,"createBuffer",Wc)},glGenFramebuffers:function(a,b){td(a,b,"createFramebuffer",Xc)},glGenRenderbuffers:function(a,b){td(a,b,"createRenderbuffer",Yc)},glGenTextures:function(a,b){td(a,b,"createTexture",Zc)},glGenerateMipmap:function(a){F.generateMipmap(a)},
glGetAttribLocation:function(a,b){return F.getAttribLocation(W[a],B(b))},glGetIntegerv:function(a,b){ud(a,b)},glGetProgramiv:function(a,b,c){if(c)if(a>=Uc)Z(1281);else{var d=cd[a];if(d)if(35716==b)a=F.getProgramInfoLog(W[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b)w[c>>2]=d.Fa;else if(35722==b){if(-1==d.X){a=W[a];var e=F.getProgramParameter(a,35721);for(b=d.X=0;b<e;++b)d.X=Math.max(d.X,F.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.X}else if(35381==b){if(-1==d.Y)for(a=
W[a],e=F.getProgramParameter(a,35382),b=d.Y=0;b<e;++b)d.Y=Math.max(d.Y,F.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.Y}else w[c>>2]=F.getProgramParameter(W[a],b);else Z(1282)}else Z(1281)},glGetUniformLocation:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=cd[a]&&cd[a].jb[b])&&0<=c&&c<a[0]?a[1]+c:-1},glLinkProgram:function(a){F.linkProgram(W[a]);var b=W[a];a=cd[a]={jb:{},Fa:0,X:-1,Y:-1};for(var c=a.jb,
d=F.getProgramParameter(b,35718),e=0;e<d;++e){var g=F.getActiveUniform(b,e),h=g.name;a.Fa=Math.max(a.Fa,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=F.getUniformLocation(b,h);if(n){var p=ed(Y);c[h]=[g.size,p];Y[p]=n;for(var t=1;t<g.size;++t)n=F.getUniformLocation(b,h+"["+t+"]"),p=ed(Y),Y[p]=n}}},glPixelStorei:function(a,b){3317==a&&(dd=b);F.pixelStorei(a,b)},glReadPixels:function(a,b,c,d,e,g,h){(h=xd(g,e,c,d,h))?F.readPixels(a,b,c,d,e,g,h):Z(1280)},glRenderbufferStorage:function(a,
b,c,d){F.renderbufferStorage(a,b,c,d)},glScissor:function(a,b,c,d){F.scissor(a,b,c,d)},glShaderSource:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?w[d+4*g>>2]:-1;e+=B(w[c+4*g>>2],0>h?void 0:h)}F.shaderSource($c[a],e)},glStencilFuncSeparate:function(a,b,c,d){F.stencilFuncSeparate(a,b,c,d)},glStencilMaskSeparate:function(a,b){F.stencilMaskSeparate(a,b)},glStencilOpSeparate:function(a,b,c,d){F.stencilOpSeparate(a,b,c,d)},glTexImage2D:function(a,b,c,d,e,g,h,n,p){F.texImage2D(a,b,c,d,e,g,h,n,p?
xd(n,h,d,e,p):null)},glTexParameteri:function(a,b,c){F.texParameteri(a,b,c)},glTexSubImage2D:function(a,b,c,d,e,g,h,n,p){var t=null;p&&(t=xd(n,h,e,g,p));F.texSubImage2D(a,b,c,d,e,g,h,n,t)},glUniform1f:function(a,b){F.uniform1f(Y[a],b)},glUniform1i:function(a,b){F.uniform1i(Y[a],b)},glUniform2f:function(a,b,c){F.uniform2f(Y[a],b,c)},glUniform3f:function(a,b,c,d){F.uniform3f(Y[a],b,c,d)},glUniform4f:function(a,b,c,d,e){F.uniform4f(Y[a],b,c,d,e)},glUniform4fv:function(a,b,c){if(256>=4*b)for(var d=gd[4*
b-1],e=0;e<4*b;e+=4)d[e]=C[c+4*e>>2],d[e+1]=C[c+(4*e+4)>>2],d[e+2]=C[c+(4*e+8)>>2],d[e+3]=C[c+(4*e+12)>>2];else d=C.subarray(c>>2,c+16*b>>2);F.uniform4fv(Y[a],d)},glUniformMatrix4fv:function(a,b,c,d){if(256>=16*b)for(var e=gd[16*b-1],g=0;g<16*b;g+=16)e[g]=C[d+4*g>>2],e[g+1]=C[d+(4*g+4)>>2],e[g+2]=C[d+(4*g+8)>>2],e[g+3]=C[d+(4*g+12)>>2],e[g+4]=C[d+(4*g+16)>>2],e[g+5]=C[d+(4*g+20)>>2],e[g+6]=C[d+(4*g+24)>>2],e[g+7]=C[d+(4*g+28)>>2],e[g+8]=C[d+(4*g+32)>>2],e[g+9]=C[d+(4*g+36)>>2],e[g+10]=C[d+(4*g+40)>>
2],e[g+11]=C[d+(4*g+44)>>2],e[g+12]=C[d+(4*g+48)>>2],e[g+13]=C[d+(4*g+52)>>2],e[g+14]=C[d+(4*g+56)>>2],e[g+15]=C[d+(4*g+60)>>2];else e=C.subarray(d>>2,d+64*b>>2);F.uniformMatrix4fv(Y[a],!!c,e)},glUseProgram:function(a){F.useProgram(W[a])},glVertexAttribPointer:function(a,b,c,d,e,g){F.vertexAttribPointer(a,b,c,!!d,e,g)},glViewport:function(a,b,c,d){F.viewport(a,b,c,d)},gmtime:function(a){a=new Date(1E3*w[a>>2]);w[12771392]=a.getUTCSeconds();w[12771393]=a.getUTCMinutes();w[12771394]=a.getUTCHours();
w[12771395]=a.getUTCDate();w[12771396]=a.getUTCMonth();w[12771397]=a.getUTCFullYear()-1900;w[12771398]=a.getUTCDay();w[12771401]=0;w[12771400]=0;w[12771399]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;w[12771402]=yd;return 51085568},localtime:function(a){zd();a=new Date(1E3*w[a>>2]);w[12771392]=a.getSeconds();w[12771393]=a.getMinutes();w[12771394]=a.getHours();w[12771395]=a.getDate();w[12771396]=a.getMonth();w[12771397]=a.getFullYear()-1900;w[12771398]=a.getDay();var b=new Date(a.getFullYear(),
0,1);w[12771399]=(a.getTime()-b.getTime())/864E5|0;w[12771401]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(c!=b&&a.getTimezoneOffset()==Math.min(b,c))|0;w[12771400]=a;a=w[Dd()+(a?4:0)>>2];w[12771402]=a;return 51085568},memory:xa,mktime:function(a){zd();var b=new Date(w[a+20>>2]+1900,w[a+16>>2],w[a+12>>2],w[a+8>>2],w[a+4>>2],w[a>>2],0),c=w[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),
6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),n=Math.min(h,g);0>c?w[a+32>>2]=Number(g!=h&&n==d):0<c!=(n==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?n:g)-d)));w[a+24>>2]=b.getDay();w[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;return b.getTime()/1E3|0},nanosleep:function(a,b){if(0===a)return Ab(28),-1;var c=w[a>>2];a=w[a+4>>2];if(0>a||999999999<a||0>c)return Ab(28),-1;0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((fa||m)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-
c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},pthread_create:function(){return 6},pthread_detach:function(){},pthread_equal:function(a,b){return a==b},pthread_mutexattr_destroy:function(){},pthread_mutexattr_init:function(){},pthread_mutexattr_settype:function(){},sched_yield:function(){return 0},sem_destroy:function(){},sem_init:function(){},sem_post:function(){},setTempRet0:function(){},strftime:Jd,strftime_l:function(a,b,c,d){return Jd(a,b,c,d)},system:function(){Ab(6);return-1},table:ya,
time:function(a){var b=Date.now()/1E3|0;a&&(w[a>>2]=b);return b}},Pd=function(){function a(a){k.asm=a.exports;cb("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return hb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);u(a)})}var d={env:Od,wasi_unstable:Od};bb("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(va||
"function"!==typeof WebAssembly.instantiateStreaming||db()||"function"!==typeof fetch)return c(b);fetch(eb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();k.asm=Pd;var jb=k.___wasm_call_ctors=function(){return k.asm.__wasm_call_ctors.apply(null,arguments)},Md=k._free=function(){return k.asm.free.apply(null,arguments)};
k._main=function(){return k.asm.main.apply(null,arguments)};var Aa=k._malloc=function(){return k.asm.malloc.apply(null,arguments)};k.___errno_location=function(){return k.asm.__errno_location.apply(null,arguments)};var Dd=k.__get_tzname=function(){return k.asm._get_tzname.apply(null,arguments)},Cd=k.__get_daylight=function(){return k.asm._get_daylight.apply(null,arguments)},Bd=k.__get_timezone=function(){return k.asm._get_timezone.apply(null,arguments)};
k._setThrew=function(){return k.asm.setThrew.apply(null,arguments)};var Ld=k.__ZSt18uncaught_exceptionv=function(){return k.asm._ZSt18uncaught_exceptionv.apply(null,arguments)};k.stackSave=function(){return k.asm.stackSave.apply(null,arguments)};var Ga=k.stackAlloc=function(){return k.asm.stackAlloc.apply(null,arguments)};k.stackRestore=function(){return k.asm.stackRestore.apply(null,arguments)};k.__growWasmMemory=function(){return k.asm.__growWasmMemory.apply(null,arguments)};
k.dynCall_ii=function(){return k.asm.dynCall_ii.apply(null,arguments)};k.dynCall_vi=function(){return k.asm.dynCall_vi.apply(null,arguments)};k.dynCall_iii=function(){return k.asm.dynCall_iii.apply(null,arguments)};k.dynCall_iiiiii=function(){return k.asm.dynCall_iiiiii.apply(null,arguments)};k.dynCall_vii=function(){return k.asm.dynCall_vii.apply(null,arguments)};k.dynCall_viii=function(){return k.asm.dynCall_viii.apply(null,arguments)};
k.dynCall_iiii=function(){return k.asm.dynCall_iiii.apply(null,arguments)};k.dynCall_iiiii=function(){return k.asm.dynCall_iiiii.apply(null,arguments)};k.dynCall_iij=function(){return k.asm.dynCall_iij.apply(null,arguments)};k.dynCall_iif=function(){return k.asm.dynCall_iif.apply(null,arguments)};k.dynCall_iid=function(){return k.asm.dynCall_iid.apply(null,arguments)};k.dynCall_iijii=function(){return k.asm.dynCall_iijii.apply(null,arguments)};
k.dynCall_iifii=function(){return k.asm.dynCall_iifii.apply(null,arguments)};k.dynCall_iidii=function(){return k.asm.dynCall_iidii.apply(null,arguments)};k.dynCall_di=function(){return k.asm.dynCall_di.apply(null,arguments)};k.dynCall_viiii=function(){return k.asm.dynCall_viiii.apply(null,arguments)};k.dynCall_v=function(){return k.asm.dynCall_v.apply(null,arguments)};k.dynCall_fi=function(){return k.asm.dynCall_fi.apply(null,arguments)};
k.dynCall_fii=function(){return k.asm.dynCall_fii.apply(null,arguments)};k.dynCall_viiiii=function(){return k.asm.dynCall_viiiii.apply(null,arguments)};k.dynCall_vid=function(){return k.asm.dynCall_vid.apply(null,arguments)};k.dynCall_i=function(){return k.asm.dynCall_i.apply(null,arguments)};k.dynCall_iiff=function(){return k.asm.dynCall_iiff.apply(null,arguments)};k.dynCall_iiif=function(){return k.asm.dynCall_iiif.apply(null,arguments)};
k.dynCall_iiiff=function(){return k.asm.dynCall_iiiff.apply(null,arguments)};k.dynCall_iiiiiii=function(){return k.asm.dynCall_iiiiiii.apply(null,arguments)};k.dynCall_viiff=function(){return k.asm.dynCall_viiff.apply(null,arguments)};k.dynCall_vifff=function(){return k.asm.dynCall_vifff.apply(null,arguments)};k.dynCall_viiiiii=function(){return k.asm.dynCall_viiiiii.apply(null,arguments)};k.dynCall_ji=function(){return k.asm.dynCall_ji.apply(null,arguments)};
k.dynCall_viij=function(){return k.asm.dynCall_viij.apply(null,arguments)};k.dynCall_iiijii=function(){return k.asm.dynCall_iiijii.apply(null,arguments)};k.dynCall_iiiiiiffffiiiffffi=function(){return k.asm.dynCall_iiiiiiffffiiiffffi.apply(null,arguments)};k.dynCall_iiiiiiiiffffiiiffffi=function(){return k.asm.dynCall_iiiiiiiiffffiiiffffi.apply(null,arguments)};k.dynCall_viff=function(){return k.asm.dynCall_viff.apply(null,arguments)};
k.dynCall_viiiiiii=function(){return k.asm.dynCall_viiiiiii.apply(null,arguments)};k.dynCall_viiiiiiii=function(){return k.asm.dynCall_viiiiiiii.apply(null,arguments)};k.dynCall_viiiiiiiii=function(){return k.asm.dynCall_viiiiiiiii.apply(null,arguments)};k.dynCall_viiffi=function(){return k.asm.dynCall_viiffi.apply(null,arguments)};k.dynCall_vif=function(){return k.asm.dynCall_vif.apply(null,arguments)};k.dynCall_jiji=function(){return k.asm.dynCall_jiji.apply(null,arguments)};
k.dynCall_iidiiii=function(){return k.asm.dynCall_iidiiii.apply(null,arguments)};k.dynCall_viijii=function(){return k.asm.dynCall_viijii.apply(null,arguments)};k.dynCall_iiiiiiiii=function(){return k.asm.dynCall_iiiiiiiii.apply(null,arguments)};k.dynCall_iiiiij=function(){return k.asm.dynCall_iiiiij.apply(null,arguments)};k.dynCall_iiiiid=function(){return k.asm.dynCall_iiiiid.apply(null,arguments)};k.dynCall_iiiiijj=function(){return k.asm.dynCall_iiiiijj.apply(null,arguments)};
k.dynCall_iiiiiiii=function(){return k.asm.dynCall_iiiiiiii.apply(null,arguments)};k.dynCall_iiiiiijj=function(){return k.asm.dynCall_iiiiiijj.apply(null,arguments)};k.asm=Pd;k.getMemory=function(a){if(Ta)var b=Aa(a);else b=w[12771388],a=b+a+15&-16,a>x.length&&u(),w[12771388]=a;return b};k.addRunDependency=bb;k.removeRunDependency=cb;k.FS_createFolder=Gc;k.FS_createPath=Hc;k.FS_createDataFile=Jc;k.FS_createPreloadedFile=Nc;k.FS_createLazyFile=Mc;k.FS_createLink=Kc;k.FS_createDevice=S;
k.FS_unlink=uc;k.calledRun=Qd;var Qd;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function Rd(){Qd||Sd();Qd||(ab=Rd)};
function Sd(a){function b(){if(!Qd&&(Qd=!0,k.calledRun=!0,!v)){Ta=!0;k.noFSInit||Ec||(Ec=!0,Dc(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?S("/dev","stdin",k.stdin):tc("/dev/tty","/dev/stdin"),k.stdout?S("/dev","stdout",null,k.stdout):tc("/dev/tty","/dev/stdout"),k.stderr?S("/dev","stderr",null,k.stderr):tc("/dev/tty1","/dev/stderr"),yc("/dev/stdin","r"),yc("/dev/stdout","w"),yc("/dev/stderr","w"));Na(Pa);bc=!1;Na(Qa);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(Td){var b=
a,d=k._main;b=b||[];var e=b.length+1,g=Ga(4*(e+1));w[g>>2]=Fa(da);for(var h=1;h<e;h++)w[(g>>2)+h]=Fa(b[h-1]);w[(g>>2)+e]=0;try{var n=d(e,g);Nd(n,!0)}catch(p){p instanceof pa||("SimulateInfiniteLoop"==p?wa=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),l("exception thrown: "+b),ea(1,p)))}finally{}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),Sa.unshift(b);Na(Sa)}}a=a||ca;if(!(0<Za)){if(k.preRun)for("function"==typeof k.preRun&&
(k.preRun=[k.preRun]);k.preRun.length;)Ua();Na(Oa);0<Za||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);b()},1)):b())}}k.run=Sd;function Nd(a,b){if(!b||!wa||0!==a){if(!wa&&(v=!0,k.onExit))k.onExit(a);ea(a,new pa(a))}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var Td=!0;k.noInitialRun&&(Td=!1);wa=!0;Sd();
