
var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.Z||(e.Z=0,e.Da=0);e.Z++;
(function(a){function b(l,t,q){var r=new XMLHttpRequest;r.open("GET",l,!0);r.responseType="arraybuffer";r.onprogress=function(w){var k=t;w.total&&(k=w.total);if(w.loaded){r.i?e.G[l].loaded=w.loaded:(r.i=!0,e.G||(e.G={}),e.G[l]={loaded:w.loaded,total:k});var v=k=w=0,x;for(x in e.G){var z=e.G[x];w+=z.total;k+=z.loaded;v++}w=Math.ceil(w*e.Z/v);e.setStatus&&e.setStatus("Downloading data... ("+k+"/"+w+")")}else!e.G&&e.setStatus&&e.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
l);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)q(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(l){console.error("package error:",l)}function d(){function l(w,k,v){this.start=w;this.X=k;this.audio=v}function t(w){e.Da++;if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);l.prototype.Ea=w;w=a.files;for(var k=
0;k<w.length;++k)l.prototype.i[w[k].filename].onload();e.removeRunDependency("datafile_Sample7.data")}l.prototype={i:{},open:function(w,k){this.name=k;this.i[k]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.Ca(this.Ea.subarray(this.start,this.X))},Ca:function(w){var k=this;e.FS_createPreloadedFile(this.name,null,w,!0,!0,function(){e.removeRunDependency("fp "+k.name)},function(){k.audio?e.removeRunDependency("fp "+k.name):m("Preloading file "+k.name+" failed")},!1,!0);this.i[this.name]=
null}};for(var q=a.files,r=0;r<q.length;++r)(new l(q[r].start,q[r].end,q[r].audio)).open("GET",q[r].filename);e.addRunDependency("datafile_Sample7.data");e.ua||(e.ua={});e.ua["Sample7.data"]={Ya:!1};n?(t(n),n=null):h=t}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,m("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=e.locateFile?e.locateFile("Sample7.data",""):"Sample7.data",g=a.remote_package_size,h=null,n=e.getPreloadedPackage?e.getPreloadedPackage(f,g):null;n||b(f,g,function(l){h?(h(l),h=null):
n=l},c);e.calledRun?d():(e.preRun||(e.preRun=[]),e.preRun.push(d))})({files:[{filename:"/AppInit.xml",start:0,end:2891,audio:0},{filename:"/button.lua",start:2891,end:3292,audio:0},{filename:"/Calibri.ttf",start:3292,end:54340,audio:0},{filename:"/Down.png",start:54340,end:55396,audio:0},{filename:"/KigsHD.png",start:55396,end:82345,audio:0},{filename:"/LaunchScreen.xml",start:82345,end:83416,audio:0},{filename:"/Logo.png",start:83416,end:99185,audio:0},{filename:"/Screen_Main.xml",start:99185,end:101247,
audio:0},{filename:"/ScriptOnApp.lua",start:101247,end:101371,audio:0},{filename:"/test.lua",start:101371,end:102356,audio:0},{filename:"/Up.png",start:102356,end:102689,audio:0}],remote_package_size:102689,package_uuid:"ae13c5bd-c99a-4d41-aafa-d67e317def92"});var aa={},p;for(p in e)e.hasOwnProperty(p)&&(aa[p]=e[p]);var ba=[],ca="./this.program";function ea(a,b){throw b;}var fa=!1,u=!1,ha=!1,ia=!1;fa="object"===typeof window;u="function"===typeof importScripts;
ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ia=!fa&&!ha&&!u;var y="",ja,ka,la,ma,na;
if(ha)y=u?require("path").dirname(y)+"/":__dirname+"/",ja=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;}),process.on("unhandledRejection",
A),ea=function(a){process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ia)"undefined"!=typeof read&&(ja=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||u)u?y=self.location.href:document.currentScript&&(y=document.currentScript.src),y=0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"",ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,
b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=e.print||console.log.bind(console),m=e.printErr||console.warn.bind(console);for(p in aa)aa.hasOwnProperty(p)&&(e[p]=aa[p]);aa=null;e.arguments&&(ba=e.arguments);e.thisProgram&&(ca=e.thisProgram);e.quit&&(ea=e.quit);function qa(a){ra||(ra={});ra[a]||(ra[a]=1,m(a))}var ra,sa;e.wasmBinary&&(sa=e.wasmBinary);var noExitRuntime;
e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&m("no native wasm support detected");var ta,ua=new WebAssembly.Table({initial:11309,maximum:11309,element:"anyfunc"}),va=!1;function assert(a,b){a||A("Assertion failed: "+b)}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function B(a,b){return a?xa(C,a,b):""}
function za(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function Aa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ba(a){var b=Aa(a)+1,c=Ca(b);c&&za(a,D,c,b);return c}function Da(a){var b=Aa(a)+1,c=Ea(b);za(a,D,c,b);return c}var Fa,D,C,Ga,Ha,E,Ia,Ja;
function Ka(a){Fa=a;e.HEAP8=D=new Int8Array(a);e.HEAP16=Ga=new Int16Array(a);e.HEAP32=E=new Int32Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=Ha=new Uint16Array(a);e.HEAPU32=Ia=new Uint32Array(a);e.HEAPF32=Ja=new Float32Array(a);e.HEAPF64=new Float64Array(a)}var La=e.INITIAL_MEMORY||67108864;e.wasmMemory?ta=e.wasmMemory:ta=new WebAssembly.Memory({initial:La/65536,maximum:32768});ta&&(Fa=ta.buffer);La=Fa.byteLength;Ka(Fa);E[12766324]=56308336;
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.aa;"number"===typeof c?void 0===b.K?e.dynCall_v(c):e.dynCall_vi(c,b.K):c(void 0===b.K?null:b.K)}}}var Na=[],Oa=[],Pa=[],Qa=[],Ra=[],Sa=!1;function Ta(){var a=e.preRun.shift();Na.unshift(a)}var Ua=Math.abs,Va=Math.ceil,Wa=Math.floor,Xa=Math.min,Ya=0,Za=null,$a=null;function ab(){Ya++;e.monitorRunDependencies&&e.monitorRunDependencies(Ya)}
function bb(){Ya--;e.monitorRunDependencies&&e.monitorRunDependencies(Ya);if(0==Ya&&(null!==Za&&(clearInterval(Za),Za=null),$a)){var a=$a;$a=null;a()}}e.preloadedImages={};e.preloadedAudios={};function A(a){if(e.onAbort)e.onAbort(a);pa(a);m(a);va=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function cb(a){var b=db;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}
function eb(){return cb("data:application/octet-stream;base64,")}var db="Sample7.wasm";if(!eb()){var fb=db;db=e.locateFile?e.locateFile(fb,y):y+fb}function gb(){try{if(sa)return new Uint8Array(sa);if(la)return la(db);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function hb(){return sa||!fa&&!u||"function"!==typeof fetch||cb("file://")?new Promise(function(a){a(gb())}):fetch(db,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+db+"'";return a.arrayBuffer()}).catch(function(){return gb()})}var F,G;Oa.push({aa:function(){ib()}});
function jb(a,b){kb=a;lb=b;if(mb)if(0==a)H=function(){var d=Math.max(0,nb+b-ob())|0;setTimeout(pb,d)};else if(1==a)H=function(){qb(pb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);u?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}H=function(){setImmediate(pb)}}}var ob;ha?ob=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?ob=dateNow:ob=function(){return performance.now()};
function rb(a,b,c,d,f){noExitRuntime=!0;assert(!mb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");mb=a;sb=d;var g="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var h=tb;pb=function(){if(!va)if(0<ub.length){var n=Date.now(),l=ub.shift();l.aa(l.K);if(vb){var t=vb,q=0==t%1?t-1:Math.floor(t);vb=l.Va?q:(8*t+(q+.5))/9}console.log('main loop blocker "'+
l.name+'" took '+(Date.now()-n)+" ms");e.setStatus&&(n=e.statusMessage||"Please wait...",l=vb,t=wb.Xa,l?l<t?e.setStatus(n+" ("+(t-l)+"/"+t+")"):e.setStatus(n):e.setStatus(""));h<tb||setTimeout(pb,0)}else if(!(h<tb))if(xb=xb+1|0,1==kb&&1<lb&&0!=xb%lb)H();else{0==kb&&(nb=ob());a:if(!(va||e.preMainLoop&&!1===e.preMainLoop())){try{g()}catch(r){if(r instanceof oa)break a;r&&"object"===typeof r&&r.stack&&m("exception thrown: "+[r,r.stack]);throw r;}e.postMainLoop&&e.postMainLoop()}h<tb||("object"===typeof SDL&&
SDL.audio&&SDL.audio.La&&SDL.audio.La(),H())}};f||(b&&0<b?jb(0,1E3/b):jb(1,1),H());if(c)throw"unwind";}var H=null,tb=0,mb=null,sb=0,kb=0,lb=0,xb=0,ub=[],wb={},nb,pb,vb,yb=!1,zb=!1,Ab=[];
function Bb(){function a(){zb=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Cb){Cb=!0;try{Db=!0}catch(c){Db=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Eb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Db?null:console.log("warning: no BlobBuilder");
Fb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.ta||"undefined"!==typeof Fb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.ta=!0);e.preloadPlugins.push({canHandle:function(c){return!e.ta&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var h=null;if(Db)try{h=new Blob([c],{type:Gb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Gb(d)}))}catch(t){qa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}h||(h=new Eb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var n=Fb.createObjectURL(h),l=new Image;l.onload=function(){assert(l.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=l.width;t.height=l.height;t.getContext("2d").drawImage(l,0,0);e.preloadedImages[d]=t;Fb.revokeObjectURL(n);f&&f(c)};l.onerror=function(){console.log("Image "+n+" could not be decoded");g&&g()};l.src=n}});e.preloadPlugins.push({canHandle:function(c){return!e.gb&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function h(r){l||(l=!0,e.preloadedAudios[d]=r,f&&f(c))}function n(){l||(l=!0,e.preloadedAudios[d]=new Audio,g&&g())}var l=!1;if(Db){try{var t=new Blob([c],{type:Gb(d)})}catch(r){return n()}t=Fb.createObjectURL(t);var q=new Audio;q.addEventListener("canplaythrough",function(){h(q)},!1);q.onerror=function(){if(!l){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var r="",w=0,k=0,
v=0;v<c.length;v++)for(w=w<<8|c[v],k+=8;6<=k;){var x=w>>k-6&63;k-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==k?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],r+="=="):4==k&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],r+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+r;h(q)}};q.src=t;Hb(function(){h(q)})}else return n()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!zb&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ib(a,b,c,d){if(b&&e.Y&&a==e.canvas)return e.Y;var f;if(b){var g={antialias:!1,alpha:!1,qa:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof Jb&&(f=Kb(a,g)))var n=Lb[f].V}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof I,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.Y=n,b&&Mb(f),e.pb=b,Ab.forEach(function(l){l()}),Bb());return n}var Nb=!1,Ob=void 0,Pb=void 0;
function Qb(a,b){function c(){yb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Rb,Ob&&d.requestPointerLock(),yb=!0,Pb?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=Ia[SDL.screen>>2]|8388608),Sb(e.canvas),Tb()):Sb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Pb?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=Ia[SDL.screen>>2]&
-8388609),Sb(e.canvas),Tb()):Sb(d));if(e.onFullScreen)e.onFullScreen(yb);if(e.onFullscreen)e.onFullscreen(yb)}Ob=a;Pb=b;"undefined"===typeof Ob&&(Ob=!0);"undefined"===typeof Pb&&(Pb=!1);var d=e.canvas;Nb||(Nb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);
f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Rb(){if(!yb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Ub=0;function qb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ub)Ub=b+1E3/60;else for(;b+2>=Ub;)Ub+=1E3/60;setTimeout(a,Math.max(Ub-b,0))}}function Hb(a){noExitRuntime=!0;setTimeout(function(){va||a()},1E4)}
function Gb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function Vb(a,b,c){var d="al "+a;ka(a,function(f){assert(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&bb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&ab(d)}var Wb=[];function Tb(){var a=e.canvas;Wb.forEach(function(b){b(a.width,a.height)})}
function Sb(a,b,c){b&&c?(a.Ta=b,a.Fa=c):(b=a.Ta,c=a.Fa);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}Pb?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Cb,Db,Eb,Fb,Xb=0,Yb=0,J=[],Zb=[],$b=null,ac=null,bc=[],cc=0,K=null;
function dc(a,b,c,d,f){var g=[];d.j=0;d.$=0;if(-1!=b.search("\n")){b=b.split("\n");for(var h=0;h<b.length;h++){var n={j:0,$:0};var l=dc(a,b[h],c,n,f);n.j>d.j&&(d.j=n.j);g.push(l);if(f)for(;g.length>f;)g.pop()}}else if(c){f=b.split(" ");b=0;h=f[b];l="";n=0;for(var t;b<f.length;)t=a.measureText(h).width,t>c?(0==n?(g.push(h),l="",n=0,b++):(n>d.j&&(d.j=n),g.push(l),n=0,l=""),h=f[b]):(b++,n=t,l=h,h+=" ",h+=f[b]);n&&(g.push(l),n>d.j&&(d.j=n))}else g.push(b),d.j=a.measureText(b).width;c&&d.j>c&&(d.j=c);
d.$=g.length;return g}var ec={};function fc(a){E[hc()>>2]=a}function ic(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ob();else return fc(28),-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0}function jc(){return 0<jc.i}function kc(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function M(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kc(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function lc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function mc(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function nc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kc(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function oc(a,b){function c(h){for(var n=0;n<h.length&&""===h[n];n++);for(var l=h.length-1;0<=l&&""===h[l];l--);return n>l?[]:h.slice(n,l-n+1)}a=nc(a).substr(1);b=nc(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var pc=[];function qc(a,b){pc[a]={input:[],output:[],I:b};rc(a,sc)}
var sc={open:function(a){var b=pc[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.I.flush(a.tty)},flush:function(a){a.tty.I.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.I.na)throw new N(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.I.na(a.tty)}catch(n){throw new N(29);}if(void 0===h&&0===f)throw new N(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.I.fa)throw new N(60);try{for(var f=
0;f<d;f++)a.tty.I.fa(a.tty,b[c+f])}catch(g){throw new N(29);}d&&(a.node.timestamp=Date.now());return f}},uc={na:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.i?Buffer.i(256):new Buffer(256),d=0;try{d=ma.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=tc(b,!0)}return a.input.shift()},fa:function(a,b){null===b||10===b?(pa(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(xa(a.output,0)),a.output=[])}},vc={fa:function(a,b){null===b||10===b?(m(xa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(m(xa(a.output,0)),a.output=[])}},O={A:null,o:function(){return O.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.A||(O.A={dir:{node:{v:O.c.v,m:O.c.m,lookup:O.c.lookup,P:O.c.P,rename:O.c.rename,unlink:O.c.unlink,rmdir:O.c.rmdir,readdir:O.c.readdir,symlink:O.c.symlink},stream:{F:O.f.F}},file:{node:{v:O.c.v,m:O.c.m},stream:{F:O.f.F,read:O.f.read,write:O.f.write,ha:O.f.ha,ra:O.f.ra,R:O.f.R}},link:{node:{v:O.c.v,m:O.c.m,readlink:O.c.readlink},stream:{}},ja:{node:{v:O.c.v,m:O.c.m},stream:wc}});c=xc(a,b,c,d);P(c.mode)?(c.c=O.A.dir.node,
c.f=O.A.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=O.A.file.node,c.f=O.A.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=O.A.link.node,c.f=O.A.link.stream):8192===(c.mode&61440)&&(c.c=O.A.ja.node,c.f=O.A.ja.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Za:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},$a:function(a){return a.b?a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array(0)},la:function(a,b){var c=a.b?a.b.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))},Ma:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(b);c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{v:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;P(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Aa=4096;b.blocks=Math.ceil(b.size/b.Aa);return b},m:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Ma(a,b.size)},lookup:function(){throw yc[44];},P:function(a,b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(P(a.mode)){try{var d=
Q(b,c)}catch(g){}if(d)for(var f in d.b)throw new N(55);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Q(a,b),d;for(d in c.b)throw new N(55);delete a.b[b]},readdir:function(a){var b=[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},f:{read:function(a,b,c,d,f){var g=
a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===D.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=b.slice(c,c+d),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}O.la(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=
0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},F:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new N(28);return b},ha:function(a,b,c){O.la(a.node,b+c);a.node.g=Math.max(a.node.g,b+c)},ra:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.b;if(h&2||a.buffer!==b.buffer){if(0<f||f+d<a.length)a.subarray?a=a.subarray(f,f+d):a=Array.prototype.slice.call(a,f,f+d);f=!0;h=b.buffer==D.buffer;d=Ca(d);if(!d)throw new N(48);
(h?D:b).set(a,d)}else f=!1,d=a.byteOffset;return{kb:d,za:f}},R:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new N(43);if(f&2)return 0;O.f.write(a,b,0,d,c,!1);return 0}}},zc=null,Ac={},Bc=[],Cc=1,Dc=null,Ec=!0,R={},N=null,yc={};
function S(a,b){a=nc("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ma:!0,ga:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ga)throw new N(32);a=kc(a.split("/").filter(function(h){return!!h}),!1);var f=zc;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Q(f,a[d]);c=M(c+"/"+a[d]);f.D&&(!g||g&&b.ma)&&(f=f.D.root);if(!g||b.O)for(g=0;40960===(f.mode&61440);)if(f=Fc(c),c=nc(lc(c),f),f=S(c,{ga:b.ga}).node,40<g++)throw new N(32);}return{path:c,node:f}}
function T(a){for(var b;;){if(a===a.parent)return a=a.o.sa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Dc.length}function Hc(a){var b=Gc(a.parent.id,a.name);a.H=Dc[b];Dc[b]=a}function Ic(a){var b=Gc(a.parent.id,a.name);if(Dc[b]===a)Dc[b]=a.H;else for(b=Dc[b];b;){if(b.H===a){b.H=a.H;break}b=b.H}}
function Q(a,b){var c;if(c=(c=Jc(a,"x"))?c:a.c.lookup?0:2)throw new N(c,a);for(c=Dc[Gc(a.id,b)];c;c=c.H){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}function xc(a,b,c,d){a=new Kc(a,b,c,d);Hc(a);return a}function P(a){return 16384===(a&61440)}var Lc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Mc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Jc(a,b){if(Ec)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Nc(a,b){try{return Q(a,b),20}catch(c){}return Jc(a,"wx")}function Oc(a,b,c){try{var d=Q(a,b)}catch(f){return f.h}if(a=Jc(a,"wx"))return a;if(c){if(!P(d.mode))return 54;if(d===d.parent||"/"===T(d))return 10}else if(P(d.mode))return 31;return 0}
function Pc(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!Bc[a])return a;throw new N(33);}function Qc(a,b,c){Rc||(Rc=function(){},Rc.prototype={});var d=new Rc,f;for(f in a)d[f]=a[f];a=d;b=Pc(b,c);a.fd=b;return Bc[b]=a}var wc={open:function(a){a.f=Ac[a.node.rdev].f;a.f.open&&a.f.open(a)},F:function(){throw new N(70);}};function rc(a,b){Ac[a]={f:b}}
function Sc(a,b){var c="/"===b,d=!b;if(c&&zc)throw new N(10);if(!c&&!d){var f=S(b,{ma:!1});b=f.path;f=f.node;if(f.D)throw new N(10);if(!P(f.mode))throw new N(54);}b={type:a,hb:{},sa:b,Ka:[]};a=a.o(b);a.o=b;b.root=a;c?zc=a:f&&(f.D=b,f.o&&f.o.Ka.push(b))}function Tc(a,b,c){var d=S(a,{parent:!0}).node;a=mc(a);if(!a||"."===a||".."===a)throw new N(28);var f=Nc(d,a);if(f)throw new N(f);if(!d.c.P)throw new N(63);return d.c.P(d,a,b,c)}function U(a,b){return Tc(a,(void 0!==b?b:511)&1023|16384,0)}
function Uc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Tc(a,b|8192,c)}function Vc(a,b){if(!nc(a))throw new N(44);var c=S(b,{parent:!0}).node;if(!c)throw new N(44);b=mc(b);var d=Nc(c,b);if(d)throw new N(d);if(!c.c.symlink)throw new N(63);return c.c.symlink(c,b,a)}
function Wc(a){var b=S(a,{parent:!0}).node,c=mc(a),d=Q(b,c),f=Oc(b,c,!1);if(f)throw new N(f);if(!b.c.unlink)throw new N(63);if(d.D)throw new N(10);try{R.willDeletePath&&R.willDeletePath(a)}catch(g){m("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.c.unlink(b,c);Ic(d);try{if(R.onDeletePath)R.onDeletePath(a)}catch(g){m("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function Fc(a){a=S(a).node;if(!a)throw new N(44);if(!a.c.readlink)throw new N(28);return nc(T(a.parent),a.c.readlink(a))}function Xc(a,b){a=S(a,{O:!b}).node;if(!a)throw new N(44);if(!a.c.v)throw new N(63);return a.c.v(a)}function Yc(a){return Xc(a,!0)}function Zc(a,b){var c;"string"===typeof a?c=S(a,{O:!0}).node:c=a;if(!c.c.m)throw new N(63);c.c.m(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function $c(a,b,c,d,f){if(""===a)throw new N(44);if("string"===typeof b){var g=Lc[b];if("undefined"===typeof g)throw Error("Unknown file open mode: "+b);b=g}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=M(a);try{h=S(a,{O:!(b&131072)}).node}catch(l){}}g=!1;if(b&64)if(h){if(b&128)throw new N(20);}else h=Tc(a,c,0),g=!0;if(!h)throw new N(44);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&!P(h.mode))throw new N(54);if(!g&&(c=h?40960===(h.mode&61440)?32:P(h.mode)&&
("r"!==Mc(b)||b&512)?31:Jc(h,Mc(b)):44))throw new N(c);if(b&512){c=h;var n;"string"===typeof c?n=S(c,{O:!0}).node:n=c;if(!n.c.m)throw new N(63);if(P(n.mode))throw new N(31);if(32768!==(n.mode&61440))throw new N(28);if(c=Jc(n,"w"))throw new N(c);n.c.m(n,{size:0,timestamp:Date.now()})}b&=-131713;d=Qc({node:h,path:T(h),flags:b,seekable:!0,position:0,f:h.f,Sa:[],error:!1},d,f);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(ad||(ad={}),a in ad||(ad[a]=1,m("FS.trackingDelegate error on read file: "+a)));
try{R.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),R.onOpenFile(a,f))}catch(l){m("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function bd(a){if(null===a.fd)throw new N(8);a.ba&&(a.ba=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Bc[a.fd]=null}a.fd=null}function cd(a,b,c){if(null===a.fd)throw new N(8);if(!a.seekable||!a.f.F)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.f.F(a,b,c);a.Sa=[]}
function dd(a,b,c,d,f,g){if(0>d||0>f)throw new N(28);if(null===a.fd)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(P(a.node.mode))throw new N(31);if(!a.f.write)throw new N(28);a.seekable&&a.flags&1024&&cd(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new N(70);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&R.onWriteToFile)R.onWriteToFile(a.path)}catch(n){m("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+n.message)}return b}
function ed(){N||(N=function(a,b){this.node=b;this.Na=function(c){this.h=c};this.Na(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(function(a){yc[a]=new N(a);yc[a].stack="<generic error, no stack>"}))}var fd;function gd(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function hd(a,b,c,d){a=M(("string"===typeof a?a:T(a))+"/"+b);return U(a,gd(c,d))}
function id(a,b){a="string"===typeof a?a:T(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=M(a+"/"+c);try{U(d)}catch(f){}a=d}}return d}function jd(a,b,c,d){a=M(("string"===typeof a?a:T(a))+"/"+b);c=gd(c,d);return Tc(a,(void 0!==c?c:438)&4095|32768,0)}
function kd(a,b,c,d,f,g){a=b?M(("string"===typeof a?a:T(a))+"/"+b):a;d=gd(d,f);f=Tc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Zc(f,d|146);a=$c(f,"w");dd(a,c,0,c.length,0,g);bd(a);Zc(f,d)}return f}
function V(a,b,c,d){a=M(("string"===typeof a?a:T(a))+"/"+b);b=gd(!!c,!!d);V.pa||(V.pa=64);var f=V.pa++<<8|0;rc(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,h,n,l){for(var t=0,q=0;q<l;q++){try{var r=c()}catch(w){throw new N(29);}if(void 0===r&&0===t)throw new N(6);if(null===r||void 0===r)break;t++;h[n+q]=r}t&&(g.node.timestamp=Date.now());return t},write:function(g,h,n,l){for(var t=0;t<l;t++)try{d(h[n+t])}catch(q){throw new N(29);}l&&(g.node.timestamp=
Date.now());return t}});return Uc(a,b,f)}function ld(a,b,c){a=M(("string"===typeof a?a:T(a))+"/"+b);return Vc(c,a)}
function md(a){if(a.Ia||a.Ja||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.b=tc(ja(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||fc(29);return b}
function nd(a,b,c,d,f){function g(){this.da=!1;this.i=[]}g.prototype.get=function(q){if(!(q>this.length-1||0>q)){var r=q%this.chunkSize;return this.oa(q/this.chunkSize|0)[r]}};g.prototype.X=function(q){this.oa=q};g.prototype.ia=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var r=Number(q.getResponseHeader("Content-length")),w,k=(w=q.getResponseHeader("Accept-Ranges"))&&"bytes"===
w;q=(w=q.getResponseHeader("Content-Encoding"))&&"gzip"===w;var v=1048576;k||(v=r);var x=this;x.X(function(z){var da=z*v,ya=(z+1)*v-1;ya=Math.min(ya,r-1);if("undefined"===typeof x.i[z]){var he=x.i;if(da>ya)throw Error("invalid range ("+da+", "+ya+") or no bytes requested!");if(ya>r-1)throw Error("only "+r+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);r!==v&&L.setRequestHeader("Range","bytes="+da+"-"+ya);"undefined"!=typeof Uint8Array&&(L.responseType="arraybuffer");
L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);da=void 0!==L.response?new Uint8Array(L.response||[]):tc(L.responseText||"",!0);he[z]=da}if("undefined"===typeof x.i[z])throw Error("doXHR failed!");return x.i[z]});if(q||!r)v=r=1,v=r=this.oa(0).length,pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.ya=r;this.wa=v;this.da=
!0};if("undefined"!==typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.da||this.ia();return this.ya}},chunkSize:{get:function(){this.da||this.ia();return this.wa}}});var n=void 0}else n=c,h=void 0;var l=jd(a,b,d,f);h?l.b=h:n&&(l.b=null,l.url=n);Object.defineProperties(l,{g:{get:function(){return this.b.length}}});var t={};Object.keys(l.f).forEach(function(q){var r=
l.f[q];t[q]=function(){if(!md(l))throw new N(29);return r.apply(null,arguments)}});t.read=function(q,r,w,k,v){if(!md(l))throw new N(29);q=q.node.b;if(v>=q.length)return 0;k=Math.min(q.length-v,k);if(q.slice)for(var x=0;x<k;x++)r[w+x]=q[v+x];else for(x=0;x<k;x++)r[w+x]=q.get(v+x);return k};l.f=t;return l}
function od(a,b,c,d,f,g,h,n,l,t){function q(k){function v(z){t&&t();n||kd(a,b,z,d,f,l);g&&g();bb(w)}var x=!1;e.preloadPlugins.forEach(function(z){!x&&z.canHandle(r)&&(z.handle(k,r,v,function(){h&&h();bb(w)}),x=!0)});x||v(k)}Bb();var r=b?nc(M(a+"/"+b)):a,w="cp "+r;ab(w);"string"==typeof c?Vb(c,function(k){q(k)},h):q(c)}var W={},Rc,ad,pd={};
function qd(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&M(b)!==M(T(f.node)))return-54;throw f;}E[c>>2]=d.dev;E[c+4>>2]=0;E[c+8>>2]=d.ino;E[c+12>>2]=d.mode;E[c+16>>2]=d.nlink;E[c+20>>2]=d.uid;E[c+24>>2]=d.gid;E[c+28>>2]=d.rdev;E[c+32>>2]=0;G=[d.size>>>0,(F=d.size,1<=+Ua(F)?0<F?(Xa(+Wa(F/4294967296),4294967295)|0)>>>0:~~+Va((F-+(~~F>>>0))/4294967296)>>>0:0)];E[c+40>>2]=G[0];E[c+44>>2]=G[1];E[c+48>>2]=4096;E[c+52>>2]=d.blocks;E[c+56>>2]=d.atime.getTime()/1E3|0;E[c+60>>2]=0;E[c+64>>2]=d.mtime.getTime()/
1E3|0;E[c+68>>2]=0;E[c+72>>2]=d.ctime.getTime()/1E3|0;E[c+76>>2]=0;G=[d.ino>>>0,(F=d.ino,1<=+Ua(F)?0<F?(Xa(+Wa(F/4294967296),4294967295)|0)>>>0:~~+Va((F-+(~~F>>>0))/4294967296)>>>0:0)];E[c+80>>2]=G[0];E[c+84>>2]=G[1];return 0}function rd(a,b,c){var d=Bc[c];d&&bd(d);return $c(a,b,0,c,c).fd}var sd=void 0;function td(){sd+=4;return E[sd-4>>2]}function ud(a){a=Bc[a];if(!a)throw new N(8);return a}function vd(){void 0===vd.start&&(vd.start=Date.now());return 1E3*(Date.now()-vd.start)|0}
function wd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,h){b.drawElementsInstancedANGLE(c,d,f,g,h)})}
function xd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function yd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var zd=1,Ad=0,Bd=[],X=[],Cd=[],Dd=[],Ed=[],Y=[],Fd=[],Lb=[],Gd=null,Hd={},Id=4;
function Z(a){Ad||(Ad=a)}function Jd(a){for(var b=zd++,c=a.length;c<b;c++)a[c]=null;return b}var Kd=[0];function Kb(a,b){if(a=a.getContext("webgl",b)){var c=Jd(Lb),d={ab:c,attributes:b,version:b.qa,V:a};a.canvas&&(a.canvas.Ua=d);Lb[c]=d;("undefined"===typeof b.ka||b.ka)&&Ld(d);b=c}else b=0;return b}function Mb(a){Gd=Lb[a];e.Y=I=Gd&&Gd.V;return!(a&&!I)}
function Ld(a){a||(a=Gd);if(!a.Ga){a.Ga=!0;var b=a.V;wd(b);xd(b);yd(b);b.Wa=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Jb={},Md,Nd,Od=["default","low-power","high-performance"],Pd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0],Qd={};
function Rd(){if(!Sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Qd)a[b]=Qd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Sd=c}return Sd}var Sd;function Td(a,b,c,d){for(var f=0;f<a;f++){var g=I[c](),h=g&&Jd(d);g?(g.name=h,d[h]=g):Z(1282);E[b+4*f>>2]=h}}
function Ud(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=I.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=I.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Z(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Z(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)E[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Z(1280);m("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Z(1280);m("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}E[b>>2]=c}else Z(1281)}
function Vd(a,b,c,d,f){a-=5120;a=1==a?C:4==a?E:6==a?Ja:5==a||28922==a?Ia:Ha;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Id;return a.subarray(f>>g,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var Wd=(za("GMT",C,51065360,4),51065360);
function Xd(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}if(!Yd){Yd=!0;E[Zd()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);E[$d()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),f=a(b);d=Ba(d);f=Ba(f);b.getTimezoneOffset()<c.getTimezoneOffset()?(E[ae()>>2]=d,E[ae()+4>>2]=f):(E[ae()>>2]=f,E[ae()+4>>2]=d)}}var Yd;function be(a){return 0===a%4&&(0!==a%100||0===a%400)}
function ce(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var de=[31,29,31,30,31,30,31,31,30,31,30,31],ee=[31,28,31,30,31,30,31,31,30,31,30,31];function fe(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(be(a.getFullYear())?de:ee)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function ge(a,b,c,d){function f(k,v,x){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=x[0]+k;return k}function g(k,v){return f(k,v,"0")}function h(k,v){function x(da){return 0>da?-1:0<da?1:0}var z;0===(z=x(k.getFullYear()-v.getFullYear()))&&0===(z=x(k.getMonth()-v.getMonth()))&&(z=x(k.getDate()-v.getDate()));return z}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function l(k){k=fe(new Date(k.l+1900,0,1),k.U);var v=new Date(k.getFullYear()+1,0,4),x=n(new Date(k.getFullYear(),0,4));v=n(v);return 0>=h(x,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var t=E[d+40>>2];d={Qa:E[d>>2],Pa:E[d+4>>2],S:E[d+8>>2],N:E[d+12>>2],J:E[d+16>>2],l:E[d+20>>2],T:E[d+24>>2],U:E[d+28>>2],ob:E[d+32>>2],Oa:E[d+36>>2],
Ra:t?B(t):""};c=B(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in t)c=c.replace(new RegExp(q,"g"),t[q]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");t={"%a":function(k){return r[k.T].substring(0,3)},"%A":function(k){return r[k.T]},"%b":function(k){return w[k.J].substring(0,3)},"%B":function(k){return w[k.J]},"%C":function(k){return g((k.l+1900)/100|0,2)},"%d":function(k){return g(k.N,2)},"%e":function(k){return f(k.N,2," ")},"%g":function(k){return l(k).toString().substring(2)},"%G":function(k){return l(k)},"%H":function(k){return g(k.S,2)},"%I":function(k){k=
k.S;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.N+ce(be(k.l+1900)?de:ee,k.J-1),3)},"%m":function(k){return g(k.J+1,2)},"%M":function(k){return g(k.Pa,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.S&&12>k.S?"AM":"PM"},"%S":function(k){return g(k.Qa,2)},"%t":function(){return"\t"},"%u":function(k){return k.T||7},"%U":function(k){var v=new Date(k.l+1900,0,1),x=0===v.getDay()?v:fe(v,7-v.getDay());k=new Date(k.l+1900,k.J,k.N);return 0>h(x,k)?g(Math.ceil((31-x.getDate()+
(ce(be(k.getFullYear())?de:ee,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,v)?"01":"00"},"%V":function(k){var v=new Date(k.l+1901,0,4),x=n(new Date(k.l+1900,0,4));v=n(v);var z=fe(new Date(k.l+1900,0,1),k.U);return 0>h(z,x)?"53":0>=h(v,z)?"01":g(Math.ceil((x.getFullYear()<k.l+1900?k.U+32-x.getDate():k.U+1-x.getDate())/7),2)},"%w":function(k){return k.T},"%W":function(k){var v=new Date(k.l,0,1),x=1===v.getDay()?v:fe(v,0===v.getDay()?1:7-v.getDay()+1);k=new Date(k.l+1900,k.J,k.N);return 0>h(x,k)?g(Math.ceil((31-
x.getDate()+(ce(be(k.getFullYear())?de:ee,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,v)?"01":"00"},"%y":function(k){return(k.l+1900).toString().substring(2)},"%Y":function(k){return k.l+1900},"%z":function(k){k=k.Oa;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Ra},"%%":function(){return"%"}};for(q in t)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),t[q](d)));q=tc(c,!1);if(q.length>b)return 0;D.set(q,a);return q.length-1}
e.requestFullscreen=function(a,b){Qb(a,b)};e.requestAnimationFrame=function(a){qb(a)};e.setCanvasSize=function(a,b,c){Sb(e.canvas,a,b);c||Tb()};e.pauseMainLoop=function(){H=null;tb++};e.resumeMainLoop=function(){tb++;var a=kb,b=lb,c=mb;mb=null;rb(c,0,!1,sb,!0);jb(a,b);H()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Ib(a,b,c,d)};
function Kc(a,b,c,d){a||(a=this);this.parent=a;this.o=a.o;this.D=null;this.id=Cc++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d}Object.defineProperties(Kc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ja:{get:function(){return P(this.mode)}},Ia:{get:function(){return 8192===(this.mode&61440)}}});ed();Dc=Array(4096);
Sc(O,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");rc(259,{read:function(){return 0},write:function(d,f,g,h){return h}});Uc("/dev/null",259);qc(1280,uc);qc(1536,vc);Uc("/dev/tty",1280);Uc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){A("random_device")});V("/dev","random",b);V("/dev","urandom",b);
U("/dev/shm");U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");Sc({o:function(){var a=xc("/proc/self","fd",16895,73);a.c={lookup:function(b,c){var d=Bc[+c];if(!d)throw new N(8);b={parent:null,o:{sa:"fake"},c:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");e.FS_createFolder=hd;e.FS_createPath=id;e.FS_createDataFile=kd;e.FS_createPreloadedFile=od;e.FS_createLazyFile=nd;e.FS_createLink=ld;e.FS_createDevice=V;e.FS_unlink=Wc;
for(var I,ie=new Float32Array(256),je=0;256>je;je++)Kd[je]=ie.subarray(0,je+1);for(je=0;256>je;je++);function tc(a,b){var c=Array(Aa(a)+1);a=za(a,c,0,c.length);b&&(c.length=a);return c}
var me={AddListenerToKeyBoard:function(){window.addEventListener("keydown",function(a){Zb.push({s:a.keyCode,u:"1"})},!1);window.addEventListener("keyup",function(a){Zb.push({s:a.keyCode,u:"0"})},!1)},AddListenerToMouse:function(){function a(l){0<l.which&&4>l.which&&(J.push({s:l.which,u:"1",B:l.pageX,C:l.pageY}),l.stopImmediatePropagation())}function b(l){0<l.which&&4>l.which&&J.push({s:l.which,u:"2",B:l.pageX,C:l.pageY})}function c(l){J.push({s:"0",u:"3",B:l.pageX,C:l.pageY})}function d(l){l=window.event||
l;J.push({s:"2",u:"3",B:120*Math.max(-1,Math.min(1,l.wheelDelta||-l.detail)),C:""});if(l.preventDefault)l.preventDefault();else return!1}function f(l){Xb=l.targetTouches[0].pageX;Yb=l.targetTouches[0].pageY;J.push({s:"1",u:"1",B:Xb,C:Yb});l.preventDefault()}function g(l){J.push({s:"1",u:"2",B:Xb,C:Yb});l.preventDefault()}var h=e.canvas;if(function(){var l="ontouchstart"in document.createElement("div");return window.navigator.msMaxTouchPoints||l?!0:!1}())h.addEventListener("touchstart",f,!1),window.addEventListener("touchend",
g,!1),h.addEventListener("touchmove",function(l){Xb=l.targetTouches[0].pageX;Yb=l.targetTouches[0].pageY;J.push({s:"0",u:"3",B:Xb,C:Yb});l.preventDefault()},!1);else{var n=/Firefox/i.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel";h.addEventListener("mousedown",a,!1);window.addEventListener("mouseup",b,!1);h.addEventListener("mousemove",c,!1);h.addEventListener(n,d,!1)}},ClearKeyBoardList:function(){Zb=[]},ClearMouseList:function(){J=[]},CreateCanvas:function(a,b){a=B(a);0==b?(b=document.createElement("canvas"),
e.canvas.parentElement.appendChild(b),b.id=a,b.style.position="absolute",b.W=1):(b=e.canvas,b.id=a,b.style.position="absolute",b.W=1)},GetCanvasPositionX:function(a){a=B(a);return document.getElementById(a).offsetLeft},GetCanvasPositionY:function(a){a=B(a);return document.getElementById(a).offsetTop},GetHTMLBodySizeX:function(){return window.innerWidth},GetHTMLBodySizeY:function(){return window.innerHeight},GetHTMLParentSizeX:function(){return Math.max(e.canvas.parentElement.scrollWidth,e.canvas.parentElement.clientWidth,
e.canvas.parentElement.offsetWidth)},GetHTMLParentSizeY:function(){return Math.max(e.canvas.parentElement.scrollHeight,e.canvas.parentElement.clientHeight,e.canvas.parentElement.offsetHeight)},Get_Key:function(a){return Zb[a].s},Get_KeyBoardEvent:function(a){return Zb[a].u},Get_KeyBoardEventCount:function(){return Zb.length},Get_MouseButton:function(a){return J[a].s},Get_MouseEvent:function(a){return J[a].u},Get_MouseEventCount:function(){return J.length},Get_MousePosX:function(a){return J[a].B},
Get_MousePosY:function(a){return J[a].C},JSDrawMultilineTextUTF16:function(a,b,c,d,f,g,h,n,l,t,q,r,w){d*=.82;q="";a>>=1;for(var k;;){k=Ha[a++];if(0==k)break;q+=String.fromCharCode(k)}a=q;K=document.createElement("canvas");q=K.getContext("2d");f=B(f);f=f.split(".")[0];q.font=d+"px "+f;k={j:0,$:0};b=dc(q,a,c,k,b);c=k.j;a=d*b.length;K.width=c;K.height=a;q.font=d+"px "+f;q.fillStyle="rgba("+n+","+l+","+t+",1)";q.textBaseline="middle";2==g?(g=c,q.textAlign="end"):1==g?(q.textAlign="center",g=c/2):(g=0,
q.textAlign="start");for(l=0;l<b.length-h;l++)n=l*d+.5*d,q.fillText(b[l+h],g,n);E[r>>2]=K.width;E[w>>2]=K.height},JSGetLanguage:function(a){var b=window.navigator.language||window.navigator.browserLanguage;D[a]=b.charCodeAt(0);D[a+1]=b.charCodeAt(1)},JSInitImageData:function(a,b,c){var d=K.getContext("2d").getImageData(0,0,b,c);b*=c;for(var f=c=0;f<b;f++)C[a++]=d.data[c++],C[a++]=d.data[c++],C[a++]=d.data[c++],C[a++]=d.data[c++];K=null},JSLoadTextureInCanvas:function(a,b,c){$b.getContext("webgl");
a=nc(B(a));var d=e.preloadedImages[a];if(!d)return E[b>>2]=0,E[c>>2]=0,null===d&&e.printErr("Trying to reuse preloaded image, but freePreloadedMediaOnUse is set!"),e.printErr("Cannot find preloaded image "+a),-1;e.freePreloadedMediaOnUse&&(e.preloadedImages[a]=null);K=document.createElement("canvas");a=K.getContext("2d");K.width=d.width;K.height=d.height;E[b>>2]=d.width;E[c>>2]=d.height;a.drawImage(d,0,0,d.width,d.height,0,0,d.width,d.height)},KigsCreateContext:function(a){function b(){}cc=a;null==
$b&&null==ec.fb&&($b=e.canvas,a?$b.getContext("webgl"):$b.getContext("2d"));var c=!1;Ib(e.canvas,cc,!0);window.addEventListener("resize",function(){for(var d=e.canvas,f=d.offsetLeft,g=d.offsetTop,h=0;0>h;h++)if(null!=bc[h]){var n=bc[h].Element;n.style.left=f+bc[h].B+"px";n.style.top=g+bc[h].C+"px"}f=document.getElementById("BtPlayVideo");null!=f&&(f.style.left=d.offsetLeft+0+"px",f.style.top=d.offsetTop+0+"px")},!1);window.addEventListener("haschange",b,!1);window.addEventListener("beforeunload",
b,!1);window.addEventListener("keydown",function(d){d=d||window.event;c||116!=d.keyCode||(window.location.href=window.location.origin,c=!0,d.returnValue=!1,d.preventDefault&&d.preventDefault())},!1);ac=document.createElement("canvas");ac.width=1;ac.height=1},SetAbsolutePos:function(a,b){a=B(a);document.getElementById(a).W=b},SetCanvasPos:function(a,b,c){a=B(a);a=document.getElementById(a);var d="static"==a.parentElement.position;a.W?d?(d=a.parentElement.getBoundingClientRect(),a.style.left=d.left+
b+"px",a.style.top=d.top+c+"px"):(a.style.left=b+"px",a.style.top=c+"px"):d?(a.style.left=b+"px",a.style.top=c+"px"):(d=a.parentElement.getBoundingClientRect(),a.style.left=d.left+b+"px",a.style.top=d.top+c+"px")},SetCanvasSize:function(a,b,c){a=B(a);a=document.getElementById(a);a.width=b;a.height=c},__clock_gettime:function(a,b){return ic(a,b)},__cxa_allocate_exception:function(a){return Ca(a)},__cxa_atexit:function(a,b){Qa.unshift({aa:a,K:b})},__cxa_throw:function(a){"uncaught_exception"in jc?jc.i++:
jc.i=1;throw a;},__map_file:function(){fc(63);return-1},__sys_dup2:function(a,b){try{var c=ud(a);return c.fd===b?b:rd(c.path,c.flags,b)}catch(d){return"undefined"!==typeof W&&d instanceof N||A(d),-d.h}},__sys_dup3:function(a,b){try{var c=ud(a);return c.fd===b?-28:rd(c.path,c.flags,b)}catch(d){return"undefined"!==typeof W&&d instanceof N||A(d),-d.h}},__sys_fcntl64:function(a,b,c){sd=c;try{var d=ud(a);switch(b){case 0:var f=td();return 0>f?-28:$c(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;
case 4:return f=td(),d.flags|=f,0;case 12:return f=td(),Ga[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return fc(28),-1;default:return-28}}catch(g){return"undefined"!==typeof W&&g instanceof N||A(g),-g.h}},__sys_ioctl:function(a,b,c){sd=c;try{var d=ud(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=td();return E[f>>2]=0;case 21520:return d.tty?-28:
-59;case 21531:a=f=td();if(!d.f.Ha)throw new N(59);return d.f.Ha(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:A("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof W&&g instanceof N||A(g),-g.h}},__sys_lstat64:function(a,b){try{return a=B(a),qd(Yc,a,b)}catch(c){return"undefined"!==typeof W&&c instanceof N||A(c),-c.h}},__sys_mkdir:function(a,b){try{return a=B(a),a=M(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),U(a,b),0}catch(c){return"undefined"!==typeof W&&
c instanceof N||A(c),-c.h}},__sys_munmap:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=pd[a];if(d&&b===d.bb){var f=Bc[d.fd];if(d.ib&2){var g=d.flags,h=d.offset,n=C.slice(a,a+b);f&&f.f.R&&f.f.R(f,n,h,b,g)}pd[a]=null;d.za&&ke(d.cb)}c=0}return c}catch(l){return"undefined"!==typeof W&&l instanceof N||A(l),-l.h}},__sys_open:function(a,b,c){sd=c;try{var d=B(a),f=td();return $c(d,b,f).fd}catch(g){return"undefined"!==typeof W&&g instanceof N||A(g),-g.h}},__sys_rename:function(a,b){try{a=B(a);
b=B(b);var c=lc(a),d=lc(b),f=mc(a),g=mc(b);try{var h=S(a,{parent:!0});var n=h.node;h=S(b,{parent:!0});var l=h.node}catch(v){throw new N(10);}if(!n||!l)throw new N(44);if(n.o!==l.o)throw new N(75);var t=Q(n,f),q=oc(a,d);if("."!==q.charAt(0))throw new N(28);q=oc(b,c);if("."!==q.charAt(0))throw new N(55);try{var r=Q(l,g)}catch(v){}if(t!==r){var w=P(t.mode),k=Oc(n,f,w);if(k)throw new N(k);if(k=r?Oc(l,g,w):Nc(l,g))throw new N(k);if(!n.c.rename)throw new N(63);if(t.D||r&&r.D)throw new N(10);if(l!==n&&(k=
Jc(n,"w")))throw new N(k);try{R.willMovePath&&R.willMovePath(a,b)}catch(v){m("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+v.message)}Ic(t);try{n.c.rename(t,l,g)}catch(v){throw v;}finally{Hc(t)}try{if(R.onMovePath)R.onMovePath(a,b)}catch(v){m("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+v.message)}}return 0}catch(v){return"undefined"!==typeof W&&v instanceof N||A(v),-v.h}},__sys_rmdir:function(a){try{a=B(a);var b=S(a,{parent:!0}).node,c=
mc(a),d=Q(b,c),f=Oc(b,c,!0);if(f)throw new N(f);if(!b.c.rmdir)throw new N(63);if(d.D)throw new N(10);try{R.willDeletePath&&R.willDeletePath(a)}catch(g){m("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.c.rmdir(b,c);Ic(d);try{if(R.onDeletePath)R.onDeletePath(a)}catch(g){m("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}return 0}catch(g){return"undefined"!==typeof W&&g instanceof N||A(g),-g.h}},__sys_stat64:function(a,b){try{return a=
B(a),qd(Xc,a,b)}catch(c){return"undefined"!==typeof W&&c instanceof N||A(c),-c.h}},__sys_unlink:function(a){try{return a=B(a),Wc(a),0}catch(b){return"undefined"!==typeof W&&b instanceof N||A(b),-b.h}},abort:function(){A()},clock:vd,clock_gettime:ic,difftime:function(a,b){return a-b},emscripten_cancel_main_loop:function(){H=null;tb++;mb=null},emscripten_get_sbrk_ptr:function(){return 51065296},emscripten_memcpy_big:function(a,b,c){C.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){a>>>=0;var b=
C.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ta.grow(Math.min(2147483648,d)-Fa.byteLength+65535>>>16);Ka(ta.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},emscripten_set_main_loop:rb,emscripten_webgl_create_context:function(a,b){var c={};b>>=2;c.alpha=!!E[b];c.depth=!!E[b+1];c.stencil=!!E[b+2];c.antialias=!!E[b+3];c.premultipliedAlpha=!!E[b+4];c.preserveDrawingBuffer=
!!E[b+5];c.powerPreference=Od[E[b+6]];c.failIfMajorPerformanceCaveat=!!E[b+7];c.qa=E[b+8];c.eb=E[b+9];c.ka=E[b+10];c.Ba=E[b+11];c.jb=E[b+12];c.lb=E[b+13];a=2<a?B(a):a;return(a=Pd[a]||("undefined"!==typeof document?document.querySelector(a):void 0))?c.Ba?-1:Kb(a,c):-4},emscripten_webgl_init_context_attributes:function(a){a>>=2;for(var b=0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},emscripten_webgl_make_context_current:function(a){return Mb(a)?0:-5},environ_get:function(a,b){var c=
0;Rd().forEach(function(d,f){var g=b+c;f=E[a+4*f>>2]=g;for(g=0;g<d.length;++g)D[f++>>0]=d.charCodeAt(g);D[f>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=Rd();E[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});E[b>>2]=d;return 0},exit:function(a){le(a)},fd_close:function(a){try{var b=ud(a);bd(b);return 0}catch(c){return"undefined"!==typeof W&&c instanceof N||A(c),c.h}},fd_read:function(a,b,c,d){try{a:{for(var f=ud(a),g=a=0;g<c;g++){var h=E[b+(8*g+4)>>2],n=f,l=E[b+
8*g>>2],t=h,q=void 0,r=D;if(0>t||0>q)throw new N(28);if(null===n.fd)throw new N(8);if(1===(n.flags&2097155))throw new N(8);if(P(n.node.mode))throw new N(31);if(!n.f.read)throw new N(28);var w="undefined"!==typeof q;if(!w)q=n.position;else if(!n.seekable)throw new N(70);var k=n.f.read(n,r,l,t,q);w||(n.position+=k);var v=k;if(0>v){var x=-1;break a}a+=v;if(v<h)break}x=a}E[d>>2]=x;return 0}catch(z){return"undefined"!==typeof W&&z instanceof N||A(z),z.h}},fd_seek:function(a,b,c,d,f){try{var g=ud(a);a=
4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;cd(g,a,d);G=[g.position>>>0,(F=g.position,1<=+Ua(F)?0<F?(Xa(+Wa(F/4294967296),4294967295)|0)>>>0:~~+Va((F-+(~~F>>>0))/4294967296)>>>0:0)];E[f>>2]=G[0];E[f+4>>2]=G[1];g.ba&&0===a&&0===d&&(g.ba=null);return 0}catch(h){return"undefined"!==typeof W&&h instanceof N||A(h),h.h}},fd_write:function(a,b,c,d){try{a:{for(var f=ud(a),g=a=0;g<c;g++){var h=dd(f,D,E[b+8*g>>2],E[b+(8*g+4)>>2],void 0);if(0>h){var n=-1;break a}a+=h}n=a}E[d>>
2]=n;return 0}catch(l){return"undefined"!==typeof W&&l instanceof N||A(l),l.h}},glActiveTexture:function(a){I.activeTexture(a)},glAttachShader:function(a,b){I.attachShader(X[a],Fd[b])},glBindBuffer:function(a,b){I.bindBuffer(a,Bd[b])},glBindFramebuffer:function(a,b){I.bindFramebuffer(a,Cd[b])},glBindRenderbuffer:function(a,b){I.bindRenderbuffer(a,Dd[b])},glBindTexture:function(a,b){I.bindTexture(a,Ed[b])},glBlendFunc:function(a,b){I.blendFunc(a,b)},glBufferData:function(a,b,c,d){I.bufferData(a,c?
C.subarray(c,c+b):b,d)},glCheckFramebufferStatus:function(a){return I.checkFramebufferStatus(a)},glClear:function(a){I.clear(a)},glClearColor:function(a,b,c,d){I.clearColor(a,b,c,d)},glColorMask:function(a,b,c,d){I.colorMask(!!a,!!b,!!c,!!d)},glCompileShader:function(a){I.compileShader(Fd[a])},glCreateProgram:function(){var a=Jd(X),b=I.createProgram();b.name=a;X[a]=b;return a},glCreateShader:function(a){var b=Jd(Fd);Fd[b]=I.createShader(a);return b},glCullFace:function(a){I.cullFace(a)},glDeleteBuffers:function(a,
b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=Bd[d];f&&(I.deleteBuffer(f),f.name=0,Bd[d]=null,d==Md&&(Md=0),d==Nd&&(Nd=0))}},glDeleteProgram:function(a){if(a){var b=X[a];b?(I.deleteProgram(b),b.name=0,X[a]=null,Hd[a]=null):Z(1281)}},glDeleteShader:function(a){if(a){var b=Fd[a];b?(I.deleteShader(b),Fd[a]=null):Z(1281)}},glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=E[b+4*c>>2],f=Ed[d];f&&(I.deleteTexture(f),f.name=0,Ed[d]=null)}},glDepthMask:function(a){I.depthMask(!!a)},glDetachShader:function(a,
b){I.detachShader(X[a],Fd[b])},glDisable:function(a){I.disable(a)},glDisableVertexAttribArray:function(a){I.disableVertexAttribArray(a)},glDrawArrays:function(a,b,c){I.drawArrays(a,b,c)},glDrawElements:function(a,b,c,d){I.drawElements(a,b,c,d)},glEnable:function(a){I.enable(a)},glEnableVertexAttribArray:function(a){I.enableVertexAttribArray(a)},glFinish:function(){I.finish()},glFlush:function(){I.flush()},glFramebufferRenderbuffer:function(a,b,c,d){I.framebufferRenderbuffer(a,b,c,Dd[d])},glFramebufferTexture2D:function(a,
b,c,d,f){I.framebufferTexture2D(a,b,c,Ed[d],f)},glGenBuffers:function(a,b){Td(a,b,"createBuffer",Bd)},glGenFramebuffers:function(a,b){Td(a,b,"createFramebuffer",Cd)},glGenRenderbuffers:function(a,b){Td(a,b,"createRenderbuffer",Dd)},glGenTextures:function(a,b){Td(a,b,"createTexture",Ed)},glGenerateMipmap:function(a){I.generateMipmap(a)},glGetAttribLocation:function(a,b){return I.getAttribLocation(X[a],B(b))},glGetIntegerv:function(a,b){Ud(a,b)},glGetProgramiv:function(a,b,c){if(c)if(a>=zd)Z(1281);
else{var d=Hd[a];if(d)if(35716==b)a=I.getProgramInfoLog(X[a]),null===a&&(a="(unknown error)"),E[c>>2]=a.length+1;else if(35719==b)E[c>>2]=d.ea;else if(35722==b){if(-1==d.L){a=X[a];var f=I.getProgramParameter(a,35721);for(b=d.L=0;b<f;++b)d.L=Math.max(d.L,I.getActiveAttrib(a,b).name.length+1)}E[c>>2]=d.L}else if(35381==b){if(-1==d.M)for(a=X[a],f=I.getProgramParameter(a,35382),b=d.M=0;b<f;++b)d.M=Math.max(d.M,I.getActiveUniformBlockName(a,b).length+1);E[c>>2]=d.M}else E[c>>2]=I.getProgramParameter(X[a],
b);else Z(1282)}else Z(1281)},glGetUniformLocation:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Hd[a]&&Hd[a].va[b])&&0<=c&&c<a[0]?a[1]+c:-1},glLinkProgram:function(a){I.linkProgram(X[a]);var b=X[a];a=Hd[a]={va:{},ea:0,L:-1,M:-1};for(var c=a.va,d=I.getProgramParameter(b,35718),f=0;f<d;++f){var g=I.getActiveUniform(b,f),h=g.name;a.ea=Math.max(a.ea,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));
var n=I.getUniformLocation(b,h);if(n){var l=Jd(Y);c[h]=[g.size,l];Y[l]=n;for(var t=1;t<g.size;++t)n=I.getUniformLocation(b,h+"["+t+"]"),l=Jd(Y),Y[l]=n}}},glPixelStorei:function(a,b){3317==a&&(Id=b);I.pixelStorei(a,b)},glReadPixels:function(a,b,c,d,f,g,h){(h=Vd(g,f,c,d,h))?I.readPixels(a,b,c,d,f,g,h):Z(1280)},glRenderbufferStorage:function(a,b,c,d){I.renderbufferStorage(a,b,c,d)},glScissor:function(a,b,c,d){I.scissor(a,b,c,d)},glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){var h=d?E[d+
4*g>>2]:-1;f+=B(E[c+4*g>>2],0>h?void 0:h)}I.shaderSource(Fd[a],f)},glStencilFuncSeparate:function(a,b,c,d){I.stencilFuncSeparate(a,b,c,d)},glStencilMaskSeparate:function(a,b){I.stencilMaskSeparate(a,b)},glStencilOpSeparate:function(a,b,c,d){I.stencilOpSeparate(a,b,c,d)},glTexImage2D:function(a,b,c,d,f,g,h,n,l){I.texImage2D(a,b,c,d,f,g,h,n,l?Vd(n,h,d,f,l):null)},glTexParameteri:function(a,b,c){I.texParameteri(a,b,c)},glTexSubImage2D:function(a,b,c,d,f,g,h,n,l){var t=null;l&&(t=Vd(n,h,f,g,l));I.texSubImage2D(a,
b,c,d,f,g,h,n,t)},glUniform1f:function(a,b){I.uniform1f(Y[a],b)},glUniform1i:function(a,b){I.uniform1i(Y[a],b)},glUniform2f:function(a,b,c){I.uniform2f(Y[a],b,c)},glUniform3f:function(a,b,c,d){I.uniform3f(Y[a],b,c,d)},glUniform4f:function(a,b,c,d,f){I.uniform4f(Y[a],b,c,d,f)},glUniform4fv:function(a,b,c){if(256>=4*b){var d=Kd[4*b-1],f=Ja;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=f[h];d[g+1]=f[h+1];d[g+2]=f[h+2];d[g+3]=f[h+3]}}else d=Ja.subarray(c>>2,c+16*b>>2);I.uniform4fv(Y[a],d)},glUniformMatrix4fv:function(a,
b,c,d){if(256>=16*b){var f=Kd[16*b-1],g=Ja;d>>=2;for(var h=0;h<16*b;h+=16){var n=d+h;f[h]=g[n];f[h+1]=g[n+1];f[h+2]=g[n+2];f[h+3]=g[n+3];f[h+4]=g[n+4];f[h+5]=g[n+5];f[h+6]=g[n+6];f[h+7]=g[n+7];f[h+8]=g[n+8];f[h+9]=g[n+9];f[h+10]=g[n+10];f[h+11]=g[n+11];f[h+12]=g[n+12];f[h+13]=g[n+13];f[h+14]=g[n+14];f[h+15]=g[n+15]}}else f=Ja.subarray(d>>2,d+64*b>>2);I.uniformMatrix4fv(Y[a],!!c,f)},glUseProgram:function(a){I.useProgram(X[a])},glVertexAttribPointer:function(a,b,c,d,f,g){I.vertexAttribPointer(a,b,c,
!!d,f,g)},glViewport:function(a,b,c,d){I.viewport(a,b,c,d)},gmtime:function(a){a=new Date(1E3*E[a>>2]);E[12766328]=a.getUTCSeconds();E[12766329]=a.getUTCMinutes();E[12766330]=a.getUTCHours();E[12766331]=a.getUTCDate();E[12766332]=a.getUTCMonth();E[12766333]=a.getUTCFullYear()-1900;E[12766334]=a.getUTCDay();E[12766337]=0;E[12766336]=0;E[12766335]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;E[12766338]=Wd;return 51065312},localtime:function(a){Xd();a=new Date(1E3*E[a>>2]);E[12766328]=
a.getSeconds();E[12766329]=a.getMinutes();E[12766330]=a.getHours();E[12766331]=a.getDate();E[12766332]=a.getMonth();E[12766333]=a.getFullYear()-1900;E[12766334]=a.getDay();var b=new Date(a.getFullYear(),0,1);E[12766335]=(a.getTime()-b.getTime())/864E5|0;E[12766337]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(c!=b&&a.getTimezoneOffset()==Math.min(b,c))|0;E[12766336]=a;a=E[ae()+(a?4:0)>>2];E[12766338]=a;return 51065312},memory:ta,
mktime:function(a){Xd();var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=f.getTimezoneOffset(),n=Math.min(h,g);0>c?E[a+32>>2]=Number(g!=h&&n==d):0<c!=(n==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?n:g)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},nanosleep:function(a,b){if(0===
a)return fc(28),-1;var c=E[a>>2];a=E[a+4>>2];if(0>a||999999999<a||0>c)return fc(28),-1;0!==b&&(E[b>>2]=0,E[b+4>>2]=0);b=1E6*c+a/1E3;for(c=ob();ob()-c<b/1E3;);},pthread_create:function(){return 6},pthread_detach:function(){},pthread_mutexattr_destroy:function(){},pthread_mutexattr_init:function(){},pthread_mutexattr_settype:function(){},sem_destroy:function(){},sem_init:function(){},sem_post:function(){},setTempRet0:function(){},strftime:ge,strftime_l:function(a,b,c,d){return ge(a,b,c,d)},system:function(a){if(ha){if(!a)return 1;
a=B(a);if(!a.length)return 0;a=require("child_process").nb(a,[],{mb:!0,stdio:"inherit"});var b=function(c,d){return c<<8|d};return null===a.status?b(0,function(c){switch(c){case "SIGHUP":return 1;case "SIGQUIT":return 3;case "SIGFPE":return 8;case "SIGKILL":return 9;case "SIGALRM":return 14;case "SIGTERM":return 15}return 2}(a.signal)):a.status<<8|0}if(!a)return 0;fc(6);return-1},table:ua,time:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}},ne=function(){function a(f){e.asm=f.exports;
bb("wasm-instantiate")}function b(f){a(f.instance)}function c(f){return hb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){m("failed to asynchronously prepare wasm: "+g);A(g)})}var d={env:me,wasi_snapshot_preview1:me};ab("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return m("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(sa||"function"!==typeof WebAssembly.instantiateStreaming||eb()||cb("file://")||"function"!==
typeof fetch)return c(b);fetch(db,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){m("wasm streaming compile failed: "+g);m("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();e.asm=ne;var ib=e.___wasm_call_ctors=function(){return(ib=e.___wasm_call_ctors=e.asm.__wasm_call_ctors).apply(null,arguments)},ke=e._free=function(){return(ke=e._free=e.asm.free).apply(null,arguments)};
e._main=function(){return(e._main=e.asm.main).apply(null,arguments)};
var Ca=e._malloc=function(){return(Ca=e._malloc=e.asm.malloc).apply(null,arguments)},hc=e.___errno_location=function(){return(hc=e.___errno_location=e.asm.__errno_location).apply(null,arguments)},ae=e.__get_tzname=function(){return(ae=e.__get_tzname=e.asm._get_tzname).apply(null,arguments)},$d=e.__get_daylight=function(){return($d=e.__get_daylight=e.asm._get_daylight).apply(null,arguments)},Zd=e.__get_timezone=function(){return(Zd=e.__get_timezone=e.asm._get_timezone).apply(null,arguments)};
e._setThrew=function(){return(e._setThrew=e.asm.setThrew).apply(null,arguments)};e._emscripten_main_thread_process_queued_calls=function(){return(e._emscripten_main_thread_process_queued_calls=e.asm.emscripten_main_thread_process_queued_calls).apply(null,arguments)};e.stackSave=function(){return(e.stackSave=e.asm.stackSave).apply(null,arguments)};var Ea=e.stackAlloc=function(){return(Ea=e.stackAlloc=e.asm.stackAlloc).apply(null,arguments)};
e.stackRestore=function(){return(e.stackRestore=e.asm.stackRestore).apply(null,arguments)};e.__growWasmMemory=function(){return(e.__growWasmMemory=e.asm.__growWasmMemory).apply(null,arguments)};e.dynCall_ii=function(){return(e.dynCall_ii=e.asm.dynCall_ii).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.dynCall_vi).apply(null,arguments)};e.dynCall_iiiiii=function(){return(e.dynCall_iiiiii=e.asm.dynCall_iiiiii).apply(null,arguments)};
e.dynCall_iii=function(){return(e.dynCall_iii=e.asm.dynCall_iii).apply(null,arguments)};e.dynCall_vii=function(){return(e.dynCall_vii=e.asm.dynCall_vii).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.dynCall_viii).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.dynCall_iiii).apply(null,arguments)};e.dynCall_iiiii=function(){return(e.dynCall_iiiii=e.asm.dynCall_iiiii).apply(null,arguments)};
e.dynCall_iij=function(){return(e.dynCall_iij=e.asm.dynCall_iij).apply(null,arguments)};e.dynCall_iif=function(){return(e.dynCall_iif=e.asm.dynCall_iif).apply(null,arguments)};e.dynCall_iid=function(){return(e.dynCall_iid=e.asm.dynCall_iid).apply(null,arguments)};e.dynCall_iijii=function(){return(e.dynCall_iijii=e.asm.dynCall_iijii).apply(null,arguments)};e.dynCall_iifii=function(){return(e.dynCall_iifii=e.asm.dynCall_iifii).apply(null,arguments)};
e.dynCall_iidii=function(){return(e.dynCall_iidii=e.asm.dynCall_iidii).apply(null,arguments)};e.dynCall_di=function(){return(e.dynCall_di=e.asm.dynCall_di).apply(null,arguments)};e.dynCall_viiii=function(){return(e.dynCall_viiii=e.asm.dynCall_viiii).apply(null,arguments)};e.dynCall_v=function(){return(e.dynCall_v=e.asm.dynCall_v).apply(null,arguments)};e.dynCall_fi=function(){return(e.dynCall_fi=e.asm.dynCall_fi).apply(null,arguments)};
e.dynCall_fii=function(){return(e.dynCall_fii=e.asm.dynCall_fii).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.dynCall_viiiii).apply(null,arguments)};e.dynCall_vid=function(){return(e.dynCall_vid=e.asm.dynCall_vid).apply(null,arguments)};e.dynCall_i=function(){return(e.dynCall_i=e.asm.dynCall_i).apply(null,arguments)};e.dynCall_iiff=function(){return(e.dynCall_iiff=e.asm.dynCall_iiff).apply(null,arguments)};
e.dynCall_iiif=function(){return(e.dynCall_iiif=e.asm.dynCall_iiif).apply(null,arguments)};e.dynCall_iiiff=function(){return(e.dynCall_iiiff=e.asm.dynCall_iiiff).apply(null,arguments)};e.dynCall_iiiiiii=function(){return(e.dynCall_iiiiiii=e.asm.dynCall_iiiiiii).apply(null,arguments)};e.dynCall_viiff=function(){return(e.dynCall_viiff=e.asm.dynCall_viiff).apply(null,arguments)};e.dynCall_vifff=function(){return(e.dynCall_vifff=e.asm.dynCall_vifff).apply(null,arguments)};
e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.dynCall_viiiiii).apply(null,arguments)};e.dynCall_ji=function(){return(e.dynCall_ji=e.asm.dynCall_ji).apply(null,arguments)};e.dynCall_viij=function(){return(e.dynCall_viij=e.asm.dynCall_viij).apply(null,arguments)};e.dynCall_iiijii=function(){return(e.dynCall_iiijii=e.asm.dynCall_iiijii).apply(null,arguments)};e.dynCall_iiiiiiffffiiiffffi=function(){return(e.dynCall_iiiiiiffffiiiffffi=e.asm.dynCall_iiiiiiffffiiiffffi).apply(null,arguments)};
e.dynCall_iiiiiiiiffffiiiffffi=function(){return(e.dynCall_iiiiiiiiffffiiiffffi=e.asm.dynCall_iiiiiiiiffffiiiffffi).apply(null,arguments)};e.dynCall_viff=function(){return(e.dynCall_viff=e.asm.dynCall_viff).apply(null,arguments)};e.dynCall_viiiiiii=function(){return(e.dynCall_viiiiiii=e.asm.dynCall_viiiiiii).apply(null,arguments)};e.dynCall_viiiiiiii=function(){return(e.dynCall_viiiiiiii=e.asm.dynCall_viiiiiiii).apply(null,arguments)};
e.dynCall_viiiiiiiii=function(){return(e.dynCall_viiiiiiiii=e.asm.dynCall_viiiiiiiii).apply(null,arguments)};e.dynCall_viiffi=function(){return(e.dynCall_viiffi=e.asm.dynCall_viiffi).apply(null,arguments)};e.dynCall_vif=function(){return(e.dynCall_vif=e.asm.dynCall_vif).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.dynCall_jiji).apply(null,arguments)};e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.dynCall_iidiiii).apply(null,arguments)};
e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.dynCall_viijii).apply(null,arguments)};e.dynCall_iiiiiiiii=function(){return(e.dynCall_iiiiiiiii=e.asm.dynCall_iiiiiiiii).apply(null,arguments)};e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.dynCall_iiiiij).apply(null,arguments)};e.dynCall_iiiiid=function(){return(e.dynCall_iiiiid=e.asm.dynCall_iiiiid).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.dynCall_iiiiijj).apply(null,arguments)};
e.dynCall_iiiiiiii=function(){return(e.dynCall_iiiiiiii=e.asm.dynCall_iiiiiiii).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.dynCall_iiiiiijj).apply(null,arguments)};e.asm=ne;e.getMemory=function(a){if(Sa)a=Ca(a);else{var b=E[12766324];E[12766324]=b+a+15&-16;a=b}return a};e.addRunDependency=ab;e.removeRunDependency=bb;e.FS_createFolder=hd;e.FS_createPath=id;e.FS_createDataFile=kd;e.FS_createPreloadedFile=od;e.FS_createLazyFile=nd;e.FS_createLink=ld;
e.FS_createDevice=V;e.FS_unlink=Wc;var oe;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}$a=function pe(){oe||qe();oe||($a=pe)};
function qe(a){function b(){if(!oe&&(oe=!0,e.calledRun=!0,!va)){Sa=!0;e.noFSInit||fd||(fd=!0,ed(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?V("/dev","stdin",e.stdin):Vc("/dev/tty","/dev/stdin"),e.stdout?V("/dev","stdout",null,e.stdout):Vc("/dev/tty","/dev/stdout"),e.stderr?V("/dev","stderr",null,e.stderr):Vc("/dev/tty1","/dev/stderr"),$c("/dev/stdin","r"),$c("/dev/stdout","w"),$c("/dev/stderr","w"));Ma(Oa);Ec=!1;Ma(Pa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(re){var c=
a,d=e._main;c=c||[];var f=c.length+1,g=Ea(4*(f+1));E[g>>2]=Da(ca);for(var h=1;h<f;h++)E[(g>>2)+h]=Da(c[h-1]);E[(g>>2)+f]=0;try{var n=d(f,g);le(n,!0)}catch(l){l instanceof oa||("unwind"==l?noExitRuntime=!0:((c=l)&&"object"===typeof l&&l.stack&&(c=[l,l.stack]),m("exception thrown: "+c),ea(1,l)))}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ra.unshift(c);Ma(Ra)}}a=a||ba;if(!(0<Ya)){if(e.preRun)for("function"==typeof e.preRun&&
(e.preRun=[e.preRun]);e.preRun.length;)Ta();Ma(Na);0<Ya||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=qe;function le(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(va=!0,e.onExit))e.onExit(a);ea(a,new oa(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var re=!0;e.noInitialRun&&(re=!1);noExitRuntime=!0;qe();
