var f;var k;k||(k=typeof Module !== 'undefined' ? Module : {});k.ua||(k.ua=0,k.kb=0);k.ua++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var e=b;c.total&&(e=c.total);if(c.loaded){d.S?k.K[a].loaded=c.loaded:(d.S=!0,k.K||(k.K={}),k.K[a]={loaded:c.loaded,total:e});var g=e=c=0,h;for(h in k.K){var p=k.K[h];c+=p.total;e+=p.loaded;g++}c=Math.ceil(c*k.ua/g);k.setStatus&&k.setStatus("Downloading data... ("+e+"/"+c+")")}else!k.K&&k.setStatus&&k.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){k.kb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.hb=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();k.removeRunDependency("datafile_Sample5.data")}b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;k.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.hb.subarray(this.start,this.end))},finish:function(a){var b=this;k.FS_createPreloadedFile(this.name,null,a,!0,!0,function(){k.removeRunDependency("fp "+b.name)},function(){b.audio?k.removeRunDependency("fp "+b.name):l("Preloading file "+b.name+
" failed")},!1,!0);this.requests[this.name]=null}};for(var d=a.files,e=0;e<d.length;++e)(new b(d[e].start,d[e].end,d[e].audio)).open("GET",d[e].filename);k.addRunDependency("datafile_Sample5.data");k.Xa||(k.Xa={});k.Xa["Sample5.data"]={Sb:!1};m?(c(m),m=null):h=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof k.locateFilePackage||k.locateFile||(k.locateFile=k.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=k.locateFile?k.locateFile("Sample5.data",""):"Sample5.data",g=a.fc,h=null,m=k.getPreloadedPackage?k.getPreloadedPackage(e,g):null;m||b(e,
g,function(a){h?(h(a),h=null):m=a},c);k.calledRun?d():(k.preRun||(k.preRun=[]),k.preRun.push(d))})({files:[{start:0,audio:0,end:2810,filename:"/AppInit.xml"},{start:2810,audio:0,end:53858,filename:"/Calibri.ttf"},{start:53858,audio:0,end:53943,filename:"/imgui.ini"},{start:53943,audio:0,end:80892,filename:"/KigsHD.png"},{start:80892,audio:0,end:81889,filename:"/LaunchScreen.xml"},{start:81889,audio:0,end:156589,filename:"/Logo.png"},{start:156589,audio:0,end:158594,filename:"/Screen_Main.xml"},{start:158594,
audio:0,end:158855,filename:"/testCoreItemExport.xml"}],remote_package_size:158855,package_uuid:"76e894d7-b4e7-422b-acf0-a5740b153b89"});var aa={},ba;for(ba in k)k.hasOwnProperty(ba)&&(aa[ba]=k[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,n=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;n="function"===typeof importScripts;ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!n;ja=!fa&&!ha&&!n;
var q="",ka,la,ma,na,oa;
if(ha)q=__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=k),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",u),ea=function(a){process.exit(a)},
k.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||n)n?q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=k.print||console.log.bind(console),l=k.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(k[ba]=aa[ba]);aa=null;k.arguments&&(ca=k.arguments);k.thisProgram&&(da=k.thisProgram);k.quit&&(ea=k.quit);function sa(a){ta||(ta={});ta[a]||(ta[a]=1,l(a))}var ta,ua={},va;k.wasmBinary&&(va=k.wasmBinary);var wa;
k.noExitRuntime&&(wa=k.noExitRuntime);"object"!==typeof WebAssembly&&l("no native wasm support detected");var xa,ya=new WebAssembly.Table({initial:11449,maximum:11449,element:"anyfunc"}),v=!1;function assert(a,b){a||u("Assertion failed: "+b)}
function za(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=Aa(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)w[a>>2]=0;for(b=d+c;a<b;)y[a++>>0]=0;return d}a.subarray||a.slice?A.set(a,d):A.set(new Uint8Array(a),d);return d}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function B(a,b){return a?Ca(A,a,b):""}
function Da(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Fa(a){var b=Ea(a)+1,c=Ga(b);Da(a,y,c,b);return c}function Ha(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,y,A,Ia,Ja,w,Ka,D;
function La(a){buffer=a;k.HEAP8=y=new Int8Array(a);k.HEAP16=Ia=new Int16Array(a);k.HEAP32=w=new Int32Array(a);k.HEAPU8=A=new Uint8Array(a);k.HEAPU16=Ja=new Uint16Array(a);k.HEAPU32=Ka=new Uint32Array(a);k.HEAPF32=D=new Float32Array(a);k.HEAPF64=new Float64Array(a)}var Ma=k.TOTAL_MEMORY||67108864;k.wasmMemory?xa=k.wasmMemory:xa=new WebAssembly.Memory({initial:Ma/65536});xa&&(buffer=xa.buffer);Ma=buffer.byteLength;La(buffer);w[12771528]=56329152;
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.v;"number"===typeof c?void 0===b.F?k.dynCall_v(c):k.dynCall_vi(c,b.F):c(void 0===b.F?null:b.F)}}}var Oa=[],Pa=[],Qa=[],Ra=[],Sa=[],Ta=!1;function Ua(){var a=k.preRun.shift();Oa.unshift(a)}var Va=Math.abs,Wa=Math.ceil,Xa=Math.floor,Ya=Math.min,Za=0,$a=null,ab=null;function bb(){Za++;k.monitorRunDependencies&&k.monitorRunDependencies(Za)}
function cb(){Za--;k.monitorRunDependencies&&k.monitorRunDependencies(Za);if(0==Za&&(null!==$a&&(clearInterval($a),$a=null),ab)){var a=ab;ab=null;a()}}k.preloadedImages={};k.preloadedAudios={};function u(a){if(k.onAbort)k.onAbort(a);qa(a);l(a);v=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function db(){var a=eb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var eb="Sample5.wasm";if(!db()){var fb=eb;eb=k.locateFile?k.locateFile(fb,q):q+fb}function gb(){try{if(va)return new Uint8Array(va);if(ma)return ma(eb);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function hb(){return va||!fa&&!n||"function"!==typeof fetch?new Promise(function(a){a(gb())}):fetch(eb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+eb+"'";return a.arrayBuffer()}).catch(function(){return gb()})}var E,F;Pa.push({v:function(){ib()}});
function jb(a,b){f.b.ma=a;f.b.na=b;if(f.b.v)if(0==a)f.b.H=function(){var a=Math.max(0,f.b.Eb+b-kb())|0;setTimeout(f.b.la,a)},f.b.method="timeout";else if(1==a)f.b.H=function(){f.requestAnimationFrame(f.b.la)},f.b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);n?(void 0===k.setImmediates&&(k.setImmediates=
[]),k.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}f.b.H=function(){setImmediate(f.b.la)};f.b.method="immediate"}}function kb(){u()}
function lb(a,b,c,d,e){wa=!0;assert(!f.b.v,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");f.b.v=a;f.b.F=d;var g="undefined"!==typeof d?function(){k.dynCall_vi(a,d)}:function(){k.dynCall_v(a)};var h=f.b.J;f.b.la=function(){if(!v)if(0<f.b.Ya.length){var a=Date.now(),b=f.b.Ya.shift();b.v(b.F);if(f.b.Ea){var c=f.b.Ea,d=0==c%1?c-1:Math.floor(c);f.b.Ea=b.Ob?d:(8*
c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");f.b.Kb();h<f.b.J||setTimeout(f.b.la,0)}else h<f.b.J||(f.b.ta=f.b.ta+1|0,1==f.b.ma&&1<f.b.na&&0!=f.b.ta%f.b.na?f.b.H():(0==f.b.ma&&(f.b.Eb=kb()),"timeout"===f.b.method&&k.aa&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),f.b.method=
""),f.b.xb(g),h<f.b.J||f.b.H()))};e||(b&&0<b?jb(0,1E3/b):jb(1,1),f.b.H());if(c)throw"SimulateInfiniteLoop";}
f={b:{H:null,method:"",J:0,v:null,F:0,ma:0,na:0,ta:0,Ya:[],pause:function(){f.b.H=null;f.b.J++},resume:function(){f.b.J++;var a=f.b.ma,b=f.b.na,c=f.b.v;f.b.v=null;lb(c,0,!1,f.b.F,!0);jb(a,b);f.b.H()},Kb:function(){if(k.setStatus){var a=k.statusMessage||"Please wait...",b=f.b.Ea,c=f.b.Rb;b?b<c?k.setStatus(a+" ("+(c-b)+"/"+c+")"):k.setStatus(a):k.setStatus("")}},xb:function(a){if(!(v||k.preMainLoop&&!1===k.preMainLoop())){try{a()}catch(b){if(b instanceof pa)return;b&&"object"===typeof b&&b.stack&&l("exception thrown: "+
[b,b.stack]);throw b;}k.postMainLoop&&k.postMainLoop()}}},T:!1,Ba:!1,tb:[],workers:[],Pa:function(){function a(){f.Ba=document.pointerLockElement===k.canvas||document.mozPointerLockElement===k.canvas||document.webkitPointerLockElement===k.canvas||document.msPointerLockElement===k.canvas}k.preloadPlugins||(k.preloadPlugins=[]);if(!f.pb){f.pb=!0;try{f.da=!0}catch(c){f.da=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}f.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:f.da?null:console.log("warning: no BlobBuilder");f.Z="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;k.Wa||"undefined"!==typeof f.Z||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),k.Wa=!0);k.preloadPlugins.push({canHandle:function(a){return!k.Wa&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,e,g){var c=null;if(f.da)try{c=
new Blob([a],{type:f.wa(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:f.wa(b)}))}catch(t){sa("Blob constructor present but fails: "+t+"; falling back to blob builder")}c||(c=new f.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=f.Z.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,0,0);k.preloadedImages[b]=
c;f.Z.revokeObjectURL(d);e&&e(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};p.src=d}});k.preloadPlugins.push({canHandle:function(a){return!k.ac&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,e,g){function c(c){p||(p=!0,k.preloadedAudios[b]=c,e&&e(a))}function d(){p||(p=!0,k.preloadedAudios[b]=new Audio,g&&g())}var p=!1;if(f.da){try{var t=new Blob([a],{type:f.wa(b)})}catch(z){return d()}t=f.Z.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",
function(){c(r)},!1);r.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",e=0,g=0,h=0;h<a.length;h++)for(e=e<<8|a[h],g+=8;6<=g;){var m=e>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(e&15)<<2],d+="=");r.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(r)}};r.src=t;f.yb(function(){c(r)},1E4)}else return d()}});var b=k.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),k.elementPointerLock&&b.addEventListener("click",function(a){!f.Ba&&k.canvas.requestPointerLock&&(k.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&k.aa&&a==k.canvas)return k.aa;var e;if(b){var g={antialias:!1,alpha:!1,Sa:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof mb&&(e=nb(a,
g)))var m=ob[e].ra}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof H,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),k.aa=m,b&&pb(e),k.oc=b,f.tb.forEach(function(a){a()}),f.Pa());return m},Pb:function(){},Ma:!1,ea:void 0,O:void 0,requestFullscreen:function(a,b,c){function d(){f.T=!1;var a=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(e.exitFullscreen=f.exitFullscreen,f.ea&&e.requestPointerLock(),f.T=!0,f.O?f.Cb():f.Y(e)):(a.parentNode.insertBefore(e,a),a.parentNode.removeChild(a),f.O?f.Db():f.Y(e));if(k.onFullScreen)k.onFullScreen(f.T);if(k.onFullscreen)k.onFullscreen(f.T)}f.ea=a;f.O=b;f.ab=c;"undefined"===typeof f.ea&&(f.ea=!0);"undefined"===typeof f.O&&(f.O=!1);"undefined"===typeof f.ab&&(f.ab=null);var e=k.canvas;f.Ma||(f.Ma=!0,document.addEventListener("fullscreenchange",d,!1),
document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");e.parentNode.insertBefore(g,e);g.appendChild(e);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:
null);c?g.requestFullscreen({pc:c}):g.requestFullscreen()},Za:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");f.Za=function(a,b,c){return f.requestFullscreen(a,b,c)};return f.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!f.T)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},M:0,jb:function(a){var b=
Date.now();if(0===f.M)f.M=b+1E3/60;else for(;b+2>=f.M;)f.M+=1E3/60;setTimeout(a,Math.max(f.M-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=f.jb;b(a)}},jc:function(a){return function(){if(!v)return a.apply(null,arguments)}},R:!0,W:[],cc:function(){f.R=!1},ic:function(){f.R=!0;if(0<f.W.length){var a=f.W;f.W=[];a.forEach(function(a){a()})}},kc:function(a){return f.requestAnimationFrame(function(){v||(f.R?a():f.W.push(a))})},
yb:function(a,b){wa=!0;return setTimeout(function(){v||(f.R?a():f.W.push(a))},b)},lc:function(a,b){wa=!0;return setInterval(function(){v||f.R&&a()},b)},wa:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},lb:function(a){return a.movementX||
a.mozMovementX||a.webkitMovementX||0},mb:function(a){return a.movementY||a.mozMovementY||a.webkitMovementY||0},Vb:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},ia:0,ja:0,ga:0,ha:0,touches:{},Qa:{},
Nb:function(a){if(f.Ba)"mousemove"!=a.type&&"mozMovementX"in a?f.ga=f.ha=0:(f.ga=f.lb(a),f.ha=f.mb(a)),f.ia+=f.ga,f.ja+=f.ha;else{var b=k.canvas.getBoundingClientRect(),c=k.canvas.width,d=k.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var h=a.nc;if(void 0!==h)if(e=h.pageX-(e+b.left),g=h.pageY-(g+b.top),e*=c/b.width,g*=
d/b.height,b={x:e,y:g},"touchstart"===a.type)f.Qa[h.identifier]=b,f.touches[h.identifier]=b;else if("touchend"===a.type||"touchmove"===a.type)(a=f.touches[h.identifier])||(a=b),f.Qa[h.identifier]=a,f.touches[h.identifier]=b}else h=a.pageX-(e+b.left),a=a.pageY-(g+b.top),h*=c/b.width,a*=d/b.height,f.ga=h-f.ia,f.ha=a-f.ja,f.ia=h,f.ja=a}},fb:function(a,b,c,d){var e=d?"":"al "+a;la(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));e&&cb(e)},function(){if(c)c();
else throw'Loading data file "'+a+'" failed.';});e&&bb(e)},wb:[],Fa:function(){var a=k.canvas;f.wb.forEach(function(b){b(a.width,a.height)})},zb:function(a,b,c){f.Y(k.canvas,a,b);c||f.Fa()},tc:0,sc:0,Cb:function(){f.Y(k.canvas);f.Fa()},Db:function(){f.Y(k.canvas);f.Fa()},Y:function(a,b,c){b&&c?(a.Lb=b,a.nb=c):(b=a.Lb,c=a.nb);var d=b,e=c;k.forcedAspectRatio&&0<k.forcedAspectRatio&&(d/e<k.forcedAspectRatio?d=Math.round(e*k.forcedAspectRatio):e=Math.round(d/k.forcedAspectRatio));if((document.fullscreenElement||
document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*g)}f.O?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||
e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))},rc:{},Va:0,Wb:function(){var a=f.Va;f.Va++;return a}};var qb=0,rb=0,I=[],sb=[],tb=null,ub=null,vb=[],wb=0,J=null;
function xb(a,b,c,d,e){var g=[];d.j=0;d.va=0;if(-1!=b.search("\n")){b=b.split("\n");for(var h=0;h<b.length;h++){var m={j:0,va:0};var p=xb(a,b[h],c,m,e);m.j>d.j&&(d.j=m.j);g.push(p);if(e)for(;g.length>e;)g.pop()}}else if(c){e=b.split(" ");b=0;h=e[b];p="";m=0;for(var t;b<e.length;)t=a.measureText(h).width,t>c?(0==m?(g.push(h),p="",m=0,b++):(m>d.j&&(d.j=m),g.push(p),m=0,p=""),h=e[b]):(b++,m=t,p=h,h+=" ",h+=e[b]);m&&(g.push(p),m>d.j&&(d.j=m))}else g.push(b),d.j=a.measureText(b).width;c&&d.j>c&&(d.j=c);
d.va=g.length;return g}var yb={};function zb(a){k.___errno_location&&(w[k.___errno_location()>>2]=a)}function Ab(a,b){if(0===a)a=Date.now();else if(1===a&&(ha||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=kb();else return zb(28),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0}function Bb(a,b){Ra.unshift({v:a,F:b})}
function Cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function K(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Cb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Eb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Fb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Cb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}
function Gb(a,b){function c(a){for(var b=0;b<a.length&&""===a[b];b++);for(var c=a.length-1;0<=c&&""===a[c];c--);return b>c?[]:a.slice(b,c-b+1)}a=Fb(a).substr(1);b=Fb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var Hb=[];function Ib(a,b){Hb[a]={input:[],output:[],N:b};Jb(a,Kb)}
var Kb={open:function(a){var b=Hb[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.N.flush(a.tty)},flush:function(a){a.tty.N.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.N.Na)throw new L(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.N.Na(a.tty)}catch(m){throw new L(29);}if(void 0===h&&0===e)throw new L(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.N.Ca)throw new L(60);try{for(var e=
0;e<d;e++)a.tty.N.Ca(a.tty,b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},Mb={Na:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.S?Buffer.S(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Lb(b,!0)}return a.input.shift()},Ca:function(a,b){null===b||10===b?(qa(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ca(a.output,0)),a.output=[])}},Nb={Ca:function(a,b){null===b||10===b?(l(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Ca(a.output,0)),a.output=[])}},M={B:null,o:function(){return M.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.B||(M.B={dir:{node:{A:M.f.A,m:M.f.m,lookup:M.f.lookup,fa:M.f.fa,rename:M.f.rename,unlink:M.f.unlink,rmdir:M.f.rmdir,readdir:M.f.readdir,symlink:M.f.symlink},stream:{I:M.g.I}},file:{node:{A:M.f.A,m:M.f.m},stream:{I:M.g.I,read:M.g.read,write:M.g.write,Ga:M.g.Ga,Ta:M.g.Ta,ka:M.g.ka}},link:{node:{A:M.f.A,m:M.f.m,readlink:M.f.readlink},stream:{}},Ia:{node:{A:M.f.A,m:M.f.m},stream:Ob}});c=Pb(a,b,c,d);N(c.mode)?(c.f=M.B.dir.node,
c.g=M.B.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=M.B.file.node,c.g=M.B.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=M.B.link.node,c.g=M.B.link.stream):8192===(c.mode&61440)&&(c.f=M.B.Ia.node,c.g=M.B.Ia.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},Tb:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},Ub:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},Ka:function(a,b){var c=a.c?a.c.length:
0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))},vb:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{A:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=
0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.gb=4096;b.blocks=Math.ceil(b.size/b.gb);return b},m:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.vb(a,b.size)},lookup:function(){throw Qb[44];},fa:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,
b,c){if(N(a.mode)){try{var d=Rb(b,c)}catch(g){}if(d)for(var e in d.c)throw new L(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=Rb(a,b),d;for(d in c.c)throw new L(55);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},
g:{read:function(a,b,c,d,e){var g=a.node.c;if(e>=a.node.h)return 0;a=Math.min(a.node.h-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===y.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===e)return a.c=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(e+d<=a.h)return a.c.set(b.subarray(c,c+d),e),d}M.Ka(a,e+d);if(a.c.subarray&&
b.subarray)a.c.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.c[e+g]=b[c+g];a.h=Math.max(a.h,e+d);return d},I:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new L(28);return b},Ga:function(a,b,c){M.Ka(a.node,b+c);a.node.h=Math.max(a.node.h,b+c)},Ta:function(a,b,c,d,e,g,h){if(32768!==(a.node.mode&61440))throw new L(43);c=a.node.c;if(h&2||c.buffer!==b.buffer){if(0<e||e+d<a.node.h)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);
a=!0;e=b.buffer==y.buffer;d=Aa(d);if(!d)throw new L(48);(e?y:b).set(c,d)}else a=!1,d=c.byteOffset;return{ec:d,eb:a}},ka:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.g.write(a,b,0,d,c,!1);return 0}}},Sb=null,Tb={},Ub=[],Vb=1,Wb=null,Xb=!0,O={},L=null,Qb={};
function P(a,b){a=Fb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={La:!0,Da:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Da)throw new L(32);a=Cb(a.split("/").filter(function(a){return!!a}),!1);var e=Sb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=Rb(e,a[d]);c=K(c+"/"+a[d]);e.G&&(!g||g&&b.La)&&(e=e.G.root);if(!g||b.ba)for(g=0;40960===(e.mode&61440);)if(e=Yb(c),c=Fb(Db(c),e),e=P(c,{Da:b.Da}).node,40<g++)throw new L(32);}return{path:c,node:e}}
function Q(a){for(var b;;){if(a===a.parent)return a=a.o.Ua,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Wb.length}function $b(a){var b=Zb(a.parent.id,a.name);a.L=Wb[b];Wb[b]=a}function ac(a){var b=Zb(a.parent.id,a.name);if(Wb[b]===a)Wb[b]=a.L;else for(b=Wb[b];b;){if(b.L===a){b.L=a.L;break}b=b.L}}
function Rb(a,b){var c;if(c=(c=bc(a,"x"))?c:a.f.lookup?0:2)throw new L(c,a);for(c=Wb[Zb(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.lookup(a,b)}
function Pb(a,b,c,d){cc||(cc=function(a,b,c,d){a||(a=this);this.parent=a;this.o=a.o;this.G=null;this.id=Vb++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=d},cc.prototype={},Object.defineProperties(cc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},sb:{get:function(){return N(this.mode)}},rb:{get:function(){return 8192===(this.mode&
61440)}}}));a=new cc(a,b,c,d);$b(a);return a}function N(a){return 16384===(a&61440)}var dc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function ec(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function bc(a,b){if(Xb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function fc(a,b){try{return Rb(a,b),20}catch(c){}return bc(a,"wx")}function hc(a,b,c){try{var d=Rb(a,b)}catch(e){return e.i}if(a=bc(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(d===d.parent||"/"===Q(d))return 10}else if(N(d.mode))return 31;return 0}function ic(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!Ub[a])return a;throw new L(33);}
function jc(a,b,c){kc||(kc=function(){},kc.prototype={},Object.defineProperties(kc.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var d=new kc,e;for(e in a)d[e]=a[e];a=d;b=ic(b,c);a.fd=b;return Ub[b]=a}var Ob={open:function(a){a.g=Tb[a.node.rdev].g;a.g.open&&a.g.open(a)},I:function(){throw new L(70);}};function Jb(a,b){Tb[a]={g:b}}
function lc(a,b){var c="/"===b,d=!b;if(c&&Sb)throw new L(10);if(!c&&!d){var e=P(b,{La:!1});b=e.path;e=e.node;if(e.G)throw new L(10);if(!N(e.mode))throw new L(54);}b={type:a,bc:{},Ua:b,ub:[]};a=a.o(b);a.o=b;b.root=a;c?Sb=a:e&&(e.G=b,e.o&&e.o.ub.push(b))}function mc(a,b,c){var d=P(a,{parent:!0}).node;a=Eb(a);if(!a||"."===a||".."===a)throw new L(28);var e=fc(d,a);if(e)throw new L(e);if(!d.f.fa)throw new L(63);return d.f.fa(d,a,b,c)}function R(a,b){return mc(a,(void 0!==b?b:511)&1023|16384,0)}
function nc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return mc(a,b|8192,c)}function oc(a,b){if(!Fb(a))throw new L(44);var c=P(b,{parent:!0}).node;if(!c)throw new L(44);b=Eb(b);var d=fc(c,b);if(d)throw new L(d);if(!c.f.symlink)throw new L(63);return c.f.symlink(c,b,a)}
function pc(a){var b=P(a,{parent:!0}).node,c=Eb(a),d=Rb(b,c),e=hc(b,c,!1);if(e)throw new L(e);if(!b.f.unlink)throw new L(63);if(d.G)throw new L(10);try{O.willDeletePath&&O.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.f.unlink(b,c);ac(d);try{if(O.onDeletePath)O.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function Yb(a){a=P(a).node;if(!a)throw new L(44);if(!a.f.readlink)throw new L(28);return Fb(Q(a.parent),a.f.readlink(a))}function qc(a,b){a=P(a,{ba:!b}).node;if(!a)throw new L(44);if(!a.f.A)throw new L(63);return a.f.A(a)}function rc(a){return qc(a,!0)}function sc(a,b){var c;"string"===typeof a?c=P(a,{ba:!0}).node:c=a;if(!c.f.m)throw new L(63);c.f.m(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function tc(a,b,c,d,e){if(""===a)throw new L(44);if("string"===typeof b){var g=dc[b];if("undefined"===typeof g)throw Error("Unknown file open mode: "+b);b=g}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=K(a);try{h=P(a,{ba:!(b&131072)}).node}catch(p){}}g=!1;if(b&64)if(h){if(b&128)throw new L(20);}else h=mc(a,c,0),g=!0;if(!h)throw new L(44);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&!N(h.mode))throw new L(54);if(!g&&(c=h?40960===(h.mode&61440)?32:N(h.mode)&&
("r"!==ec(b)||b&512)?31:bc(h,ec(b)):44))throw new L(c);if(b&512){c=h;var m;"string"===typeof c?m=P(c,{ba:!0}).node:m=c;if(!m.f.m)throw new L(63);if(N(m.mode))throw new L(31);if(32768!==(m.mode&61440))throw new L(28);if(c=bc(m,"w"))throw new L(c);m.f.m(m,{size:0,timestamp:Date.now()})}b&=-641;d=jc({node:h,path:Q(h),flags:b,seekable:!0,position:0,g:h.g,Jb:[],error:!1},d,e);d.g.open&&d.g.open(d);!k.logReadFiles||b&1||(uc||(uc={}),a in uc||(uc[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{O.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),O.onOpenFile(a,e))}catch(p){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d}function vc(a){if(null===a.fd)throw new L(8);a.ya&&(a.ya=null);try{a.g.close&&a.g.close(a)}catch(b){throw b;}finally{Ub[a.fd]=null}a.fd=null}
function wc(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.g.I)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.g.I(a,b,c);a.Jb=[]}
function xc(a,b,c,d,e,g){if(0>d||0>e)throw new L(28);if(null===a.fd)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(N(a.node.mode))throw new L(31);if(!a.g.write)throw new L(28);a.flags&1024&&wc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new L(70);b=a.g.write(a,b,c,d,e,g);h||(a.position+=b);try{if(a.path&&O.onWriteToFile)O.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function yc(){L||(L=function(a,b){this.node=b;this.Bb=function(a){this.i=a};this.Bb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){Qb[a]=new L(a);Qb[a].stack="<generic error, no stack>"}))}var zc;function Ac(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Bc(a,b,c,d){a=K(("string"===typeof a?a:Q(a))+"/"+b);return R(a,Ac(c,d))}
function Cc(a,b){a="string"===typeof a?a:Q(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=K(a+"/"+c);try{R(d)}catch(e){}a=d}}return d}function Dc(a,b,c,d){a=K(("string"===typeof a?a:Q(a))+"/"+b);c=Ac(c,d);return mc(a,(void 0!==c?c:438)&4095|32768,0)}
function Ec(a,b,c,d,e,g){a=b?K(("string"===typeof a?a:Q(a))+"/"+b):a;d=Ac(d,e);e=mc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}sc(e,d|146);a=tc(e,"w");xc(a,c,0,c.length,0,g);vc(a);sc(e,d)}return e}
function S(a,b,c,d){a=K(("string"===typeof a?a:Q(a))+"/"+b);b=Ac(!!c,!!d);S.Ra||(S.Ra=64);var e=S.Ra++<<8|0;Jb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var g=0,h=0;h<e;h++){try{var p=c()}catch(C){throw new L(29);}if(void 0===p&&0===g)throw new L(6);if(null===p||void 0===p)break;g++;b[d+h]=p}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,e){for(var g=0;g<e;g++)try{d(b[c+g])}catch(r){throw new L(29);}e&&(a.node.timestamp=
Date.now());return g}});return nc(a,b,e)}function Fc(a,b,c){a=K(("string"===typeof a?a:Q(a))+"/"+b);return oc(c,a)}
function Gc(a){if(a.rb||a.sb||a.link||a.c)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.c=Lb(ka(a.url),!0),a.h=a.c.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||zb(29);return b}
function Hc(a,b,c,d,e){function g(){this.za=!1;this.$=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Oa(a/this.chunkSize|0)[b]}};g.prototype.Ab=function(a){this.Oa=a};g.prototype.Ha=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;e||(g=b);var h=this;h.Ab(function(a){var d=a*g,e=(a+1)*g-1;e=Math.min(e,b-1);if("undefined"===typeof h.$[a]){var x=h.$;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==g&&p.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");p.overrideMimeType&&
p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):Lb(p.responseText||"",!0);x[a]=d}if("undefined"===typeof h.$[a])throw Error("doXHR failed!");return h.$[a]});if(a||!b)g=b=1,g=b=this.Oa(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.cb=b;this.bb=g;this.za=!0};if("undefined"!==
typeof XMLHttpRequest){if(!n)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.za||this.Ha();return this.cb}},chunkSize:{get:function(){this.za||this.Ha();return this.bb}}});var m=void 0}else m=c,h=void 0;var p=Dc(a,b,d,e);h?p.c=h:m&&(p.c=null,p.url=m);Object.defineProperties(p,{h:{get:function(){return this.c.length}}});var t={};Object.keys(p.g).forEach(function(a){var b=
p.g[a];t[a]=function(){if(!Gc(p))throw new L(29);return b.apply(null,arguments)}});t.read=function(a,b,c,d,e){if(!Gc(p))throw new L(29);a=a.node.c;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[e+g];else for(g=0;g<d;g++)b[c+g]=a.get(e+g);return d};p.g=t;return p}
function Ic(a,b,c,d,e,g,h,m,p,t){function r(c){function x(c){t&&t();m||Ec(a,b,c,d,e,p);g&&g();cb(C)}var r=!1;k.preloadPlugins.forEach(function(a){!r&&a.canHandle(z)&&(a.handle(c,z,x,function(){h&&h();cb(C)}),r=!0)});r||x(c)}f.Pa();var z=b?Fb(K(a+"/"+b)):a,C="cp "+z;bb(C);"string"==typeof c?f.fb(c,function(a){r(a)},h):r(c)}var T={},cc,kc,uc,Jc={};
function Kc(a,b,c){try{var d=a(b)}catch(e){if(e&&e.node&&K(b)!==K(Q(e.node)))return-54;throw e;}w[c>>2]=d.dev;w[c+4>>2]=0;w[c+8>>2]=d.ino;w[c+12>>2]=d.mode;w[c+16>>2]=d.nlink;w[c+20>>2]=d.uid;w[c+24>>2]=d.gid;w[c+28>>2]=d.rdev;w[c+32>>2]=0;F=[d.size>>>0,(E=d.size,1<=+Va(E)?0<E?(Ya(+Xa(E/4294967296),4294967295)|0)>>>0:~~+Wa((E-+(~~E>>>0))/4294967296)>>>0:0)];w[c+40>>2]=F[0];w[c+44>>2]=F[1];w[c+48>>2]=4096;w[c+52>>2]=d.blocks;w[c+56>>2]=d.atime.getTime()/1E3|0;w[c+60>>2]=0;w[c+64>>2]=d.mtime.getTime()/
1E3|0;w[c+68>>2]=0;w[c+72>>2]=d.ctime.getTime()/1E3|0;w[c+76>>2]=0;F=[d.ino>>>0,(E=d.ino,1<=+Va(E)?0<E?(Ya(+Xa(E/4294967296),4294967295)|0)>>>0:~~+Wa((E-+(~~E>>>0))/4294967296)>>>0:0)];w[c+80>>2]=F[0];w[c+84>>2]=F[1];return 0}function Lc(a,b,c){var d=Ub[c];d&&vc(d);return tc(a,b,0,c,c).fd}var U=0;function V(){U+=4;return w[U-4>>2]}function Mc(){return B(V())}function Nc(a){void 0===a&&(a=V());a=Ub[a];if(!a)throw new L(8);return a}
function Oc(){void 0===Oc.start&&(Oc.start=Date.now());return 1E3*(Date.now()-Oc.start)|0}var Pc=1,Qc=0,Rc=[],X=[],Sc=[],Tc=[],Uc=[],Y=[],Vc=[],ob={},Wc=null,Xc={},Yc={},Zc=4;function Z(a){Qc||(Qc=a)}function $c(a){for(var b=Pc++,c=a.length;c<b;c++)a[c]=null;return b}var ad=null,bd=[0];
function nb(a,b){if(a=a.getContext("webgl",b)||a.getContext("experimental-webgl",b)){var c=Aa(8),d={handle:c,attributes:b,version:b.Sa,ra:a};a.canvas&&(a.canvas.Mb=d);ob[c]=d;("undefined"===typeof b.Ja||b.Ja)&&cd(d);b=c}else b=0;return b}function pb(a){Wc=ob[a];k.aa=H=Wc&&Wc.ra;return!(a&&!H)}
function dd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,g){b.drawArraysInstancedANGLE(a,d,e,g)},a.drawElementsInstanced=function(a,d,e,g,h){b.drawElementsInstancedANGLE(a,d,e,g,h)})}
function ed(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function fd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function cd(a){a||(a=Wc);if(!a.ob){a.ob=!0;var b=a.ra;2>a.version&&(dd(b),ed(b),fd(b));b.Qb=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var mb={},gd,hd,id=["default","low-power","high-performance"],jd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function kd(a){try{if(!a)return window;"number"===typeof a&&(a=jd[a]||B(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?k.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var ld={};
function md(){if(!nd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in ld)a[b]=ld[b];var c=[];for(b in a)c.push(b+"="+a[b]);nd=c}return nd}var nd;function od(a,b,c,d){for(var e=0;e<a;e++){var g=H[c](),h=g&&$c(d);g?(g.name=h,d[h]=g):Z(1282);w[b+4*e>>2]=h}}
function pd(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=H.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=H.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Z(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Z(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Z(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Z(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}w[b>>2]=c}else Z(1281)}
var qd={6402:1,6406:1,6407:3,6408:4,6409:1,6410:2,35904:3,35906:4},rd={5121:1,5123:2,5125:4,5126:4,32819:2,32820:2,33635:2,34042:4,36193:2};function sd(a,b,c,d,e){if(b=qd[b]*rd[a]){var g=Zc;c=e+d*(c*b+g-1&-g);switch(a){case 5121:return A.subarray(e,c);case 5126:return D.subarray(e>>2,c>>2);case 5125:case 34042:return Ka.subarray(e>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:return Ja.subarray(e>>1,c>>1);default:Z(1280)}}else Z(1280)}var td=(Da("GMT",A,51086176,4),51086176);
function ud(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!vd){vd=!0;w[wd()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);w[xd()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),e=a(b);d=za(Lb(d));e=za(Lb(e));b.getTimezoneOffset()<c.getTimezoneOffset()?(w[yd()>>2]=d,w[yd()+4>>2]=e):(w[yd()>>2]=e,w[yd()+4>>2]=d)}}var vd;function zd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Ad(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Bd=[31,29,31,30,31,30,31,31,30,31,30,31],Cd=[31,28,31,30,31,30,31,31,30,31,30,31];function Dd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(zd(a.getFullYear())?Bd:Cd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ed(a,b,c,d){function e(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return e(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=Dd(new Date(a.l+1900,0,1),a.qa);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=h(m(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var t=w[d+40>>2];d={Hb:w[d>>2],Gb:w[d+4>>2],oa:w[d+8>>2],X:w[d+12>>2],P:w[d+16>>2],l:w[d+20>>2],pa:w[d+24>>2],qa:w[d+28>>2],mc:w[d+32>>2],Fb:w[d+36>>2],Ib:t?
B(t):""};c=B(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var z="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
C="January February March April May June July August September October November December".split(" ");t={"%a":function(a){return z[a.pa].substring(0,3)},"%A":function(a){return z[a.pa]},"%b":function(a){return C[a.P].substring(0,3)},"%B":function(a){return C[a.P]},"%C":function(a){return g((a.l+1900)/100|0,2)},"%d":function(a){return g(a.X,2)},"%e":function(a){return e(a.X,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return g(a.oa,2)},
"%I":function(a){a=a.oa;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.X+Ad(zd(a.l+1900)?Bd:Cd,a.P-1),3)},"%m":function(a){return g(a.P+1,2)},"%M":function(a){return g(a.Gb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.oa&&12>a.oa?"AM":"PM"},"%S":function(a){return g(a.Hb,2)},"%t":function(){return"\t"},"%u":function(a){return a.pa||7},"%U":function(a){var b=new Date(a.l+1900,0,1),c=0===b.getDay()?b:Dd(b,7-b.getDay());a=new Date(a.l+1900,a.P,a.X);return 0>h(c,a)?
g(Math.ceil((31-c.getDate()+(Ad(zd(a.getFullYear())?Bd:Cd,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.l+1900,0,4)),c=m(new Date(a.l+1901,0,4)),d=Dd(new Date(a.l+1900,0,1),a.qa);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.l+1900?a.qa+32-b.getDate():a.qa+1-b.getDate())/7),2)},"%w":function(a){return a.pa},"%W":function(a){var b=new Date(a.l,0,1),c=1===b.getDay()?b:Dd(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.l+1900,a.P,
a.X);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(Ad(zd(a.getFullYear())?Bd:Cd,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.l+1900).toString().substring(2)},"%Y":function(a){return a.l+1900},"%z":function(a){a=a.Fb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.Ib},"%%":function(){return"%"}};for(r in t)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=Lb(c,!1);if(r.length>b)return 0;
y.set(r,a);return r.length-1}k.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");k.requestFullScreen=k.requestFullscreen;f.Za(a,b,c)};k.requestFullscreen=function(a,b,c){f.requestFullscreen(a,b,c)};k.requestAnimationFrame=function(a){f.requestAnimationFrame(a)};k.setCanvasSize=function(a,b,c){f.zb(a,b,c)};k.pauseMainLoop=function(){f.b.pause()};k.resumeMainLoop=function(){f.b.resume()};k.getUserMedia=function(){f.getUserMedia()};
k.createContext=function(a,b,c,d){return f.createContext(a,b,c,d)};ha?kb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?kb=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?kb=function(){return performance.now()}:kb=Date.now;yc();Wb=Array(4096);lc(M,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");Jb(259,{read:function(){return 0},write:function(a,b,c,h){return h}});nc("/dev/null",259);Ib(1280,Mb);Ib(1536,Nb);nc("/dev/tty",1280);nc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){u("random_device")});S("/dev","random",b);S("/dev","urandom",b);
R("/dev/shm");R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");lc({o:function(){var a=Pb("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=Ub[+c];if(!b)throw new L(8);a={parent:null,o:{Ua:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");k.FS_createFolder=Bc;k.FS_createPath=Cc;k.FS_createDataFile=Ec;k.FS_createPreloadedFile=Ic;k.FS_createLazyFile=Hc;k.FS_createLink=Fc;k.FS_createDevice=S;k.FS_unlink=pc;var H;ad=new Float32Array(256);
for(var Fd=0;256>Fd;Fd++)bd[Fd]=ad.subarray(0,Fd+1);function Lb(a,b){var c=Array(Ea(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}
var Jd={AddListenerToKeyBoard:function(){window.addEventListener("keydown",function(a){sb.push({s:a.keyCode,u:"1"})},!1);window.addEventListener("keyup",function(a){sb.push({s:a.keyCode,u:"0"})},!1)},AddListenerToMouse:function(){function a(a){0<a.which&&4>a.which&&(I.push({s:a.which,u:"1",C:a.pageX,D:a.pageY}),a.stopImmediatePropagation())}function b(a){0<a.which&&4>a.which&&I.push({s:a.which,u:"2",C:a.pageX,D:a.pageY})}function c(a){I.push({s:"0",u:"3",C:a.pageX,D:a.pageY})}function d(a){a=window.event||
a;I.push({s:"2",u:"3",C:120*Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)),D:""});if(a.preventDefault)a.preventDefault();else return!1}function e(a){qb=a.targetTouches[0].pageX;rb=a.targetTouches[0].pageY;I.push({s:"1",u:"1",C:qb,D:rb});a.preventDefault()}function g(a){I.push({s:"1",u:"2",C:qb,D:rb});a.preventDefault()}var h=k.canvas;if(function(){var a="ontouchstart"in document.createElement("div");return window.navigator.msMaxTouchPoints||a?!0:!1}())h.addEventListener("touchstart",e,!1),window.addEventListener("touchend",
g,!1),h.addEventListener("touchmove",function(a){qb=a.targetTouches[0].pageX;rb=a.targetTouches[0].pageY;I.push({s:"0",u:"3",C:qb,D:rb});a.preventDefault()},!1);else{var m=/Firefox/i.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel";h.addEventListener("mousedown",a,!1);window.addEventListener("mouseup",b,!1);h.addEventListener("mousemove",c,!1);h.addEventListener(m,d,!1)}},ClearKeyBoardList:function(){sb=[]},ClearMouseList:function(){I=[]},CreateCanvas:function(a,b){a=B(a);0==b?(b=document.createElement("canvas"),
k.canvas.parentElement.appendChild(b),b.id=a,b.style.position="absolute",b.sa=1):(b=k.canvas,b.id=a,b.style.position="absolute",b.sa=1)},GetCanvasPositionX:function(a){a=B(a);return document.getElementById(a).offsetLeft},GetCanvasPositionY:function(a){a=B(a);return document.getElementById(a).offsetTop},GetHTMLBodySizeX:function(){return window.innerWidth},GetHTMLBodySizeY:function(){return window.innerHeight},GetHTMLParentSizeX:function(){return Math.max(k.canvas.parentElement.scrollWidth,k.canvas.parentElement.clientWidth,
k.canvas.parentElement.offsetWidth)},GetHTMLParentSizeY:function(){return Math.max(k.canvas.parentElement.scrollHeight,k.canvas.parentElement.clientHeight,k.canvas.parentElement.offsetHeight)},Get_Key:function(a){return sb[a].s},Get_KeyBoardEvent:function(a){return sb[a].u},Get_KeyBoardEventCount:function(){return sb.length},Get_MouseButton:function(a){return I[a].s},Get_MouseEvent:function(a){return I[a].u},Get_MouseEventCount:function(){return I.length},Get_MousePosX:function(a){return I[a].C},
Get_MousePosY:function(a){return I[a].D},JSDrawMultilineTextUTF16:function(a,b,c,d,e,g,h,m,p,t,r,z,C){d*=.82;r="";a>>=1;for(var x;;){x=Ja[a++];if(0==x)break;r+=String.fromCharCode(x)}a=r;J=document.createElement("canvas");r=J.getContext("2d");e=B(e);e=e.split(".")[0];r.font=d+"px "+e;x={j:0,va:0};b=xb(r,a,c,x,b);c=x.j;a=d*b.length;J.width=c;J.height=a;r.font=d+"px "+e;r.fillStyle="rgba("+m+","+p+","+t+",1)";r.textBaseline="middle";2==g?(g=c,r.textAlign="end"):1==g?(r.textAlign="center",g=c/2):(g=
0,r.textAlign="start");for(p=0;p<b.length-h;p++)m=p*d+.5*d,r.fillText(b[p+h],g,m);w[z>>2]=J.width;w[C>>2]=J.height},JSGetLanguage:function(a){var b=window.navigator.language||window.navigator.browserLanguage;y[a]=b.charCodeAt(0);y[a+1]=b.charCodeAt(1)},JSInitImageData:function(a,b,c){var d=J.getContext("2d").getImageData(0,0,b,c);b*=c;for(var e=c=0;e<b;e++)A[a++]=d.data[c++],A[a++]=d.data[c++],A[a++]=d.data[c++],A[a++]=d.data[c++];J=null},JSLoadTextureInCanvas:function(a,b,c){tb.getContext("webgl");
a=Fb(B(a));var d=k.preloadedImages[a];if(!d)return w[b>>2]=0,w[c>>2]=0,null===d&&k.printErr("Trying to reuse preloaded image, but freePreloadedMediaOnUse is set!"),ua.qc("Cannot find preloaded image "+a),-1;k.freePreloadedMediaOnUse&&(k.preloadedImages[a]=null);J=document.createElement("canvas");a=J.getContext("2d");J.width=d.width;J.height=d.height;w[b>>2]=d.width;w[c>>2]=d.height;a.drawImage(d,0,0,d.width,d.height,0,0,d.width,d.height)},KigsCreateContext:function(a){function b(){}wb=a;null==tb&&
null==yb.$b&&(tb=k.canvas,a?tb.getContext("webgl"):tb.getContext("2d"));var c=!1;f.createContext(k.canvas,wb,!0);window.addEventListener("resize",function(){for(var a=k.canvas,b=a.offsetLeft,c=a.offsetTop,h=0;0>h;h++)if(null!=vb[h]){var m=vb[h].Element;m.style.left=b+vb[h].C+"px";m.style.top=c+vb[h].D+"px"}b=document.getElementById("BtPlayVideo");null!=b&&(b.style.left=a.offsetLeft+0+"px",b.style.top=a.offsetTop+0+"px")},!1);window.addEventListener("haschange",b,!1);window.addEventListener("beforeunload",
b,!1);window.addEventListener("keydown",function(a){a=a||window.event;c||116!=a.keyCode||(window.location.href=window.location.origin,c=!0,a.returnValue=!1,a.preventDefault&&a.preventDefault())},!1);ub=document.createElement("canvas");ub.width=1;ub.height=1},SetAbsolutePos:function(a,b){a=B(a);document.getElementById(a).sa=b},SetCanvasPos:function(a,b,c){a=B(a);a=document.getElementById(a);var d="static"==a.parentElement.position;a.sa?d?(d=a.parentElement.getBoundingClientRect(),a.style.left=d.left+
b+"px",a.style.top=d.top+c+"px"):(a.style.left=b+"px",a.style.top=c+"px"):d?(a.style.left=b+"px",a.style.top=c+"px"):(d=a.parentElement.getBoundingClientRect(),a.style.left=d.left+b+"px",a.style.top=d.top+c+"px")},SetCanvasSize:function(a,b,c){a=B(a);a=document.getElementById(a);a.width=b;a.height=c},__clock_gettime:function(a,b){return Ab(a,b)},__cxa_allocate_exception:function(a){return Aa(a)},__cxa_atexit:function(){return Bb.apply(null,arguments)},__cxa_throw:function(a){"uncaught_exception"in
Gd?Gd.S++:Gd.S=1;throw a;},__lock:function(){},__map_file:function(){zb(63);return-1},__syscall10:function(a,b){U=b;try{var c=Mc();pc(c);return 0}catch(d){return"undefined"!==typeof T&&d instanceof L||u(d),-d.i}},__syscall195:function(a,b){U=b;try{var c=Mc(),d=V();return Kc(qc,c,d)}catch(e){return"undefined"!==typeof T&&e instanceof L||u(e),-e.i}},__syscall196:function(a,b){U=b;try{var c=Mc(),d=V();return Kc(rc,c,d)}catch(e){return"undefined"!==typeof T&&e instanceof L||u(e),-e.i}},__syscall221:function(a,
b){U=b;try{var c=Nc();switch(V()){case 0:var d=V();return 0>d?-28:tc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=V(),c.flags|=d,0;case 12:return d=V(),Ia[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return zb(28),-1;default:return-28}}catch(e){return"undefined"!==typeof T&&e instanceof L||u(e),-e.i}},__syscall330:function(a,b){U=b;try{var c=Nc(),d=V();V();return c.fd===d?-28:Lc(c.path,c.flags,d)}catch(e){return"undefined"!==typeof T&&
e instanceof L||u(e),-e.i}},__syscall38:function(a,b){U=b;try{var c=Mc(),d=Mc(),e=Db(c),g=Db(d),h=Eb(c),m=Eb(d);try{var p=P(c,{parent:!0});var t=p.node;p=P(d,{parent:!0});var r=p.node}catch(G){throw new L(10);}if(!t||!r)throw new L(44);if(t.o!==r.o)throw new L(75);var z=Rb(t,h),C=Gb(c,g);if("."!==C.charAt(0))throw new L(28);C=Gb(d,e);if("."!==C.charAt(0))throw new L(55);try{var x=Rb(r,m)}catch(G){}if(z!==x){var ra=N(z.mode),W=hc(t,h,ra);if(W)throw new L(W);if(W=x?hc(r,m,ra):fc(r,m))throw new L(W);
if(!t.f.rename)throw new L(63);if(z.G||x&&x.G)throw new L(10);if(r!==t&&(W=bc(t,"w")))throw new L(W);try{O.willMovePath&&O.willMovePath(c,d)}catch(G){console.log("FS.trackingDelegate['willMovePath']('"+c+"', '"+d+"') threw an exception: "+G.message)}ac(z);try{t.f.rename(z,r,m)}catch(G){throw G;}finally{$b(z)}try{if(O.onMovePath)O.onMovePath(c,d)}catch(G){console.log("FS.trackingDelegate['onMovePath']('"+c+"', '"+d+"') threw an exception: "+G.message)}}return 0}catch(G){return"undefined"!==typeof T&&
G instanceof L||u(G),-G.i}},__syscall39:function(a,b){U=b;try{var c=Mc(),d=V();a=c;a=K(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));R(a,d);return 0}catch(e){return"undefined"!==typeof T&&e instanceof L||u(e),-e.i}},__syscall40:function(a,b){U=b;try{var c=Mc(),d=P(c,{parent:!0}).node,e=Eb(c),g=Rb(d,e),h=hc(d,e,!0);if(h)throw new L(h);if(!d.f.rmdir)throw new L(63);if(g.G)throw new L(10);try{O.willDeletePath&&O.willDeletePath(c)}catch(m){console.log("FS.trackingDelegate['willDeletePath']('"+c+
"') threw an exception: "+m.message)}d.f.rmdir(d,e);ac(g);try{if(O.onDeletePath)O.onDeletePath(c)}catch(m){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+m.message)}return 0}catch(m){return"undefined"!==typeof T&&m instanceof L||u(m),-m.i}},__syscall5:function(a,b){U=b;try{var c=Mc(),d=V(),e=V();return tc(c,d,e).fd}catch(g){return"undefined"!==typeof T&&g instanceof L||u(g),-g.i}},__syscall54:function(a,b){U=b;try{var c=Nc(),d=V();switch(d){case 21509:case 21505:return c.tty?
0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=V();return w[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=V();if(!c.g.qb)throw new L(59);return c.g.qb(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:u("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof T&&g instanceof L||u(g),-g.i}},__syscall63:function(a,b){U=b;try{var c=Nc(),d=V();return c.fd===d?d:Lc(c.path,c.flags,d)}catch(e){return"undefined"!==
typeof T&&e instanceof L||u(e),-e.i}},__syscall91:function(a,b){U=b;try{var c=V(),d=V();if(-1===c||0===d)var e=-28;else{var g=Jc[c];if(g&&d===g.Xb){var h=Ub[g.fd],m=g.flags,p=new Uint8Array(A.subarray(c,c+d));h&&h.g.ka&&h.g.ka(h,p,0,d,m);Jc[c]=null;g.eb&&Hd(g.Yb)}e=0}return e}catch(t){return"undefined"!==typeof T&&t instanceof L||u(t),-t.i}},__unlock:function(){},abort:function(){u()},clock:Oc,clock_gettime:Ab,difftime:function(a,b){return a-b},emscripten_cancel_main_loop:function(){f.b.pause();f.b.v=
null},emscripten_get_sbrk_ptr:function(){return 51086112},emscripten_memcpy_big:function(a,b,c){A.set(A.subarray(b,b+c),a)},emscripten_resize_heap:function(a){if(2147418112<a)return!1;for(var b=Math.max(y.length,16777216);b<a;)536870912>=b?b=Ha(2*b):b=Math.min(Ha((3*b+2147483648)/4),2147418112);a:{try{xa.grow(b-buffer.byteLength+65535>>16);La(xa.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},emscripten_set_main_loop:lb,emscripten_webgl_create_context:function(a,b){var c={};b>>=2;c.alpha=
!!w[b];c.depth=!!w[b+1];c.stencil=!!w[b+2];c.antialias=!!w[b+3];c.premultipliedAlpha=!!w[b+4];c.preserveDrawingBuffer=!!w[b+5];c.powerPreference=id[w[b+6]];c.failIfMajorPerformanceCaveat=!!w[b+7];c.Sa=w[b+8];c.Zb=w[b+9];c.Ja=w[b+10];c.ib=w[b+11];c.dc=w[b+12];c.hc=w[b+13];"number"===typeof a&&(a=B(a));a=a&&"#canvas"!==a?"undefined"!==typeof mb&&Xc[a]?Xc[a]:kd(a):"undefined"!==typeof mb&&Xc.canvas?Xc.canvas:k.canvas;return!a||c.ib?0:nb(a,c)},emscripten_webgl_init_context_attributes:function(a){a>>=
2;for(var b=0;14>b;++b)w[a+b]=0;w[a]=w[a+1]=w[a+3]=w[a+4]=w[a+8]=w[a+10]=1},emscripten_webgl_make_context_current:function(a){return pb(a)?0:-5},environ_get:function(a,b){var c=0;md().forEach(function(d,e){var g=b+c;e=w[a+4*e>>2]=g;for(g=0;g<d.length;++g)y[e++>>0]=d.charCodeAt(g);y[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=md();w[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});w[b>>2]=d;return 0},exit:function(a){Id(a)},fd_close:function(a){try{var b=Nc(a);
vc(b);return 0}catch(c){return"undefined"!==typeof T&&c instanceof L||u(c),c.i}},fd_read:function(a,b,c,d){try{a:{for(var e=Nc(a),g=a=0;g<c;g++){var h=w[b+(8*g+4)>>2],m=e,p=w[b+8*g>>2],t=h,r=void 0,z=y;if(0>t||0>r)throw new L(28);if(null===m.fd)throw new L(8);if(1===(m.flags&2097155))throw new L(8);if(N(m.node.mode))throw new L(31);if(!m.g.read)throw new L(28);var C="undefined"!==typeof r;if(!C)r=m.position;else if(!m.seekable)throw new L(70);var x=m.g.read(m,z,p,t,r);C||(m.position+=x);var ra=x;
if(0>ra){var W=-1;break a}a+=ra;if(ra<h)break}W=a}w[d>>2]=W;return 0}catch(G){return"undefined"!==typeof T&&G instanceof L||u(G),G.i}},fd_seek:function(a,b,c,d,e){try{var g=Nc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;wc(g,a,d);F=[g.position>>>0,(E=g.position,1<=+Va(E)?0<E?(Ya(+Xa(E/4294967296),4294967295)|0)>>>0:~~+Wa((E-+(~~E>>>0))/4294967296)>>>0:0)];w[e>>2]=F[0];w[e+4>>2]=F[1];g.ya&&0===a&&0===d&&(g.ya=null);return 0}catch(h){return"undefined"!==typeof T&&
h instanceof L||u(h),h.i}},fd_write:function(a,b,c,d){try{a:{for(var e=Nc(a),g=a=0;g<c;g++){var h=xc(e,y,w[b+8*g>>2],w[b+(8*g+4)>>2],void 0);if(0>h){var m=-1;break a}a+=h}m=a}w[d>>2]=m;return 0}catch(p){return"undefined"!==typeof T&&p instanceof L||u(p),p.i}},glActiveTexture:function(a){H.activeTexture(a)},glAttachShader:function(a,b){H.attachShader(X[a],Vc[b])},glBindBuffer:function(a,b){H.bindBuffer(a,Rc[b])},glBindFramebuffer:function(a,b){H.bindFramebuffer(a,Sc[b])},glBindRenderbuffer:function(a,
b){H.bindRenderbuffer(a,Tc[b])},glBindTexture:function(a,b){H.bindTexture(a,Uc[b])},glBlendFunc:function(a,b){H.blendFunc(a,b)},glBufferData:function(a,b,c,d){H.bufferData(a,c?A.subarray(c,c+b):b,d)},glCheckFramebufferStatus:function(a){return H.checkFramebufferStatus(a)},glClear:function(a){H.clear(a)},glClearColor:function(a,b,c,d){H.clearColor(a,b,c,d)},glColorMask:function(a,b,c,d){H.colorMask(!!a,!!b,!!c,!!d)},glCompileShader:function(a){H.compileShader(Vc[a])},glCreateProgram:function(){var a=
$c(X),b=H.createProgram();b.name=a;X[a]=b;return a},glCreateShader:function(a){var b=$c(Vc);Vc[b]=H.createShader(a);return b},glCullFace:function(a){H.cullFace(a)},glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Rc[d];e&&(H.deleteBuffer(e),e.name=0,Rc[d]=null,d==gd&&(gd=0),d==hd&&(hd=0))}},glDeleteProgram:function(a){if(a){var b=X[a];b?(H.deleteProgram(b),b.name=0,X[a]=null,Yc[a]=null):Z(1281)}},glDeleteShader:function(a){if(a){var b=Vc[a];b?(H.deleteShader(b),Vc[a]=null):Z(1281)}},
glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Uc[d];e&&(H.deleteTexture(e),e.name=0,Uc[d]=null)}},glDepthMask:function(a){H.depthMask(!!a)},glDetachShader:function(a,b){H.detachShader(X[a],Vc[b])},glDisable:function(a){H.disable(a)},glDisableVertexAttribArray:function(a){H.disableVertexAttribArray(a)},glDrawArrays:function(a,b,c){H.drawArrays(a,b,c)},glDrawElements:function(a,b,c,d){H.drawElements(a,b,c,d)},glEnable:function(a){H.enable(a)},glEnableVertexAttribArray:function(a){H.enableVertexAttribArray(a)},
glFinish:function(){H.finish()},glFlush:function(){H.flush()},glFramebufferRenderbuffer:function(a,b,c,d){H.framebufferRenderbuffer(a,b,c,Tc[d])},glFramebufferTexture2D:function(a,b,c,d,e){H.framebufferTexture2D(a,b,c,Uc[d],e)},glGenBuffers:function(a,b){od(a,b,"createBuffer",Rc)},glGenFramebuffers:function(a,b){od(a,b,"createFramebuffer",Sc)},glGenRenderbuffers:function(a,b){od(a,b,"createRenderbuffer",Tc)},glGenTextures:function(a,b){od(a,b,"createTexture",Uc)},glGenerateMipmap:function(a){H.generateMipmap(a)},
glGetAttribLocation:function(a,b){return H.getAttribLocation(X[a],B(b))},glGetIntegerv:function(a,b){pd(a,b)},glGetProgramiv:function(a,b,c){if(c)if(a>=Pc)Z(1281);else{var d=Yc[a];if(d)if(35716==b)a=H.getProgramInfoLog(X[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b)w[c>>2]=d.Aa;else if(35722==b){if(-1==d.U){a=X[a];var e=H.getProgramParameter(a,35721);for(b=d.U=0;b<e;++b)d.U=Math.max(d.U,H.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.U}else if(35381==b){if(-1==d.V)for(a=
X[a],e=H.getProgramParameter(a,35382),b=d.V=0;b<e;++b)d.V=Math.max(d.V,H.getActiveUniformBlockName(a,b).length+1);w[c>>2]=d.V}else w[c>>2]=H.getProgramParameter(X[a],b);else Z(1282)}else Z(1281)},glGetUniformLocation:function(a,b){b=B(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Yc[a]&&Yc[a].$a[b])&&0<=c&&c<a[0]?a[1]+c:-1},glLinkProgram:function(a){H.linkProgram(X[a]);var b=X[a];a=Yc[a]={$a:{},Aa:0,U:-1,V:-1};for(var c=a.$a,
d=H.getProgramParameter(b,35718),e=0;e<d;++e){var g=H.getActiveUniform(b,e),h=g.name;a.Aa=Math.max(a.Aa,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=H.getUniformLocation(b,h);if(m){var p=$c(Y);c[h]=[g.size,p];Y[p]=m;for(var t=1;t<g.size;++t)m=H.getUniformLocation(b,h+"["+t+"]"),p=$c(Y),Y[p]=m}}},glPixelStorei:function(a,b){3317==a&&(Zc=b);H.pixelStorei(a,b)},glReadPixels:function(a,b,c,d,e,g,h){(h=sd(g,e,c,d,h))?H.readPixels(a,b,c,d,e,g,h):Z(1280)},glRenderbufferStorage:function(a,
b,c,d){H.renderbufferStorage(a,b,c,d)},glScissor:function(a,b,c,d){H.scissor(a,b,c,d)},glShaderSource:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?w[d+4*g>>2]:-1;e+=B(w[c+4*g>>2],0>h?void 0:h)}H.shaderSource(Vc[a],e)},glStencilFuncSeparate:function(a,b,c,d){H.stencilFuncSeparate(a,b,c,d)},glStencilMaskSeparate:function(a,b){H.stencilMaskSeparate(a,b)},glStencilOpSeparate:function(a,b,c,d){H.stencilOpSeparate(a,b,c,d)},glTexImage2D:function(a,b,c,d,e,g,h,m,p){H.texImage2D(a,b,c,d,e,g,h,m,p?
sd(m,h,d,e,p):null)},glTexParameteri:function(a,b,c){H.texParameteri(a,b,c)},glTexSubImage2D:function(a,b,c,d,e,g,h,m,p){var t=null;p&&(t=sd(m,h,e,g,p));H.texSubImage2D(a,b,c,d,e,g,h,m,t)},glUniform1f:function(a,b){H.uniform1f(Y[a],b)},glUniform1i:function(a,b){H.uniform1i(Y[a],b)},glUniform2f:function(a,b,c){H.uniform2f(Y[a],b,c)},glUniform3f:function(a,b,c,d){H.uniform3f(Y[a],b,c,d)},glUniform4f:function(a,b,c,d,e){H.uniform4f(Y[a],b,c,d,e)},glUniform4fv:function(a,b,c){if(256>=4*b)for(var d=bd[4*
b-1],e=0;e<4*b;e+=4)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2],d[e+3]=D[c+(4*e+12)>>2];else d=D.subarray(c>>2,c+16*b>>2);H.uniform4fv(Y[a],d)},glUniformMatrix4fv:function(a,b,c,d){if(256>=16*b)for(var e=bd[16*b-1],g=0;g<16*b;g+=16)e[g]=D[d+4*g>>2],e[g+1]=D[d+(4*g+4)>>2],e[g+2]=D[d+(4*g+8)>>2],e[g+3]=D[d+(4*g+12)>>2],e[g+4]=D[d+(4*g+16)>>2],e[g+5]=D[d+(4*g+20)>>2],e[g+6]=D[d+(4*g+24)>>2],e[g+7]=D[d+(4*g+28)>>2],e[g+8]=D[d+(4*g+32)>>2],e[g+9]=D[d+(4*g+36)>>2],e[g+10]=D[d+(4*g+40)>>
2],e[g+11]=D[d+(4*g+44)>>2],e[g+12]=D[d+(4*g+48)>>2],e[g+13]=D[d+(4*g+52)>>2],e[g+14]=D[d+(4*g+56)>>2],e[g+15]=D[d+(4*g+60)>>2];else e=D.subarray(d>>2,d+64*b>>2);H.uniformMatrix4fv(Y[a],!!c,e)},glUseProgram:function(a){H.useProgram(X[a])},glVertexAttribPointer:function(a,b,c,d,e,g){H.vertexAttribPointer(a,b,c,!!d,e,g)},glViewport:function(a,b,c,d){H.viewport(a,b,c,d)},gmtime:function(a){a=new Date(1E3*w[a>>2]);w[12771532]=a.getUTCSeconds();w[12771533]=a.getUTCMinutes();w[12771534]=a.getUTCHours();
w[12771535]=a.getUTCDate();w[12771536]=a.getUTCMonth();w[12771537]=a.getUTCFullYear()-1900;w[12771538]=a.getUTCDay();w[12771541]=0;w[12771540]=0;w[12771539]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;w[12771542]=td;return 51086128},localtime:function(a){ud();a=new Date(1E3*w[a>>2]);w[12771532]=a.getSeconds();w[12771533]=a.getMinutes();w[12771534]=a.getHours();w[12771535]=a.getDate();w[12771536]=a.getMonth();w[12771537]=a.getFullYear()-1900;w[12771538]=a.getDay();var b=new Date(a.getFullYear(),
0,1);w[12771539]=(a.getTime()-b.getTime())/864E5|0;w[12771541]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();b=b.getTimezoneOffset();a=(c!=b&&a.getTimezoneOffset()==Math.min(b,c))|0;w[12771540]=a;a=w[yd()+(a?4:0)>>2];w[12771542]=a;return 51086128},memory:xa,mktime:function(a){ud();var b=new Date(w[a+20>>2]+1900,w[a+16>>2],w[a+12>>2],w[a+8>>2],w[a+4>>2],w[a>>2],0),c=w[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),
6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),m=Math.min(h,g);0>c?w[a+32>>2]=Number(g!=h&&m==d):0<c!=(m==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?m:g)-d)));w[a+24>>2]=b.getDay();w[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;return b.getTime()/1E3|0},nanosleep:function(a,b){if(0===a)return zb(28),-1;var c=w[a>>2];a=w[a+4>>2];if(0>a||999999999<a||0>c)return zb(28),-1;0!==b&&(w[b>>2]=0,w[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((fa||n)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-
c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},pthread_create:function(){return 6},pthread_detach:function(){},pthread_equal:function(a,b){return a==b},pthread_mutexattr_destroy:function(){},pthread_mutexattr_init:function(){},pthread_mutexattr_settype:function(){},sched_yield:function(){return 0},sem_destroy:function(){},sem_init:function(){},sem_post:function(){},setTempRet0:function(){},strftime:Ed,strftime_l:function(a,b,c,d){return Ed(a,b,c,d)},system:function(){zb(6);return-1},table:ya,
time:function(a){var b=Date.now()/1E3|0;a&&(w[a>>2]=b);return b}},Kd=function(){function a(a){k.asm=a.exports;cb("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return hb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);u(a)})}var d={env:Jd,wasi_unstable:Jd};bb("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(va||
"function"!==typeof WebAssembly.instantiateStreaming||db()||"function"!==typeof fetch)return c(b);fetch(eb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();k.asm=Kd;var ib=k.___wasm_call_ctors=function(){return k.asm.__wasm_call_ctors.apply(null,arguments)},Hd=k._free=function(){return k.asm.free.apply(null,arguments)};
k._main=function(){return k.asm.main.apply(null,arguments)};var Aa=k._malloc=function(){return k.asm.malloc.apply(null,arguments)};k.___errno_location=function(){return k.asm.__errno_location.apply(null,arguments)};var yd=k.__get_tzname=function(){return k.asm._get_tzname.apply(null,arguments)},xd=k.__get_daylight=function(){return k.asm._get_daylight.apply(null,arguments)},wd=k.__get_timezone=function(){return k.asm._get_timezone.apply(null,arguments)};
k._setThrew=function(){return k.asm.setThrew.apply(null,arguments)};var Gd=k.__ZSt18uncaught_exceptionv=function(){return k.asm._ZSt18uncaught_exceptionv.apply(null,arguments)};k.stackSave=function(){return k.asm.stackSave.apply(null,arguments)};var Ga=k.stackAlloc=function(){return k.asm.stackAlloc.apply(null,arguments)};k.stackRestore=function(){return k.asm.stackRestore.apply(null,arguments)};k.__growWasmMemory=function(){return k.asm.__growWasmMemory.apply(null,arguments)};
k.dynCall_ii=function(){return k.asm.dynCall_ii.apply(null,arguments)};k.dynCall_vi=function(){return k.asm.dynCall_vi.apply(null,arguments)};k.dynCall_iii=function(){return k.asm.dynCall_iii.apply(null,arguments)};k.dynCall_iiiiii=function(){return k.asm.dynCall_iiiiii.apply(null,arguments)};k.dynCall_vii=function(){return k.asm.dynCall_vii.apply(null,arguments)};k.dynCall_viii=function(){return k.asm.dynCall_viii.apply(null,arguments)};
k.dynCall_iiii=function(){return k.asm.dynCall_iiii.apply(null,arguments)};k.dynCall_iiiii=function(){return k.asm.dynCall_iiiii.apply(null,arguments)};k.dynCall_iij=function(){return k.asm.dynCall_iij.apply(null,arguments)};k.dynCall_iif=function(){return k.asm.dynCall_iif.apply(null,arguments)};k.dynCall_iid=function(){return k.asm.dynCall_iid.apply(null,arguments)};k.dynCall_iijii=function(){return k.asm.dynCall_iijii.apply(null,arguments)};
k.dynCall_iifii=function(){return k.asm.dynCall_iifii.apply(null,arguments)};k.dynCall_iidii=function(){return k.asm.dynCall_iidii.apply(null,arguments)};k.dynCall_fi=function(){return k.asm.dynCall_fi.apply(null,arguments)};k.dynCall_v=function(){return k.asm.dynCall_v.apply(null,arguments)};k.dynCall_viiii=function(){return k.asm.dynCall_viiii.apply(null,arguments)};k.dynCall_fiff=function(){return k.asm.dynCall_fiff.apply(null,arguments)};
k.dynCall_fii=function(){return k.asm.dynCall_fii.apply(null,arguments)};k.dynCall_viiiii=function(){return k.asm.dynCall_viiiii.apply(null,arguments)};k.dynCall_di=function(){return k.asm.dynCall_di.apply(null,arguments)};k.dynCall_vid=function(){return k.asm.dynCall_vid.apply(null,arguments)};k.dynCall_i=function(){return k.asm.dynCall_i.apply(null,arguments)};k.dynCall_iiff=function(){return k.asm.dynCall_iiff.apply(null,arguments)};
k.dynCall_iiif=function(){return k.asm.dynCall_iiif.apply(null,arguments)};k.dynCall_iiiff=function(){return k.asm.dynCall_iiiff.apply(null,arguments)};k.dynCall_iiiiiii=function(){return k.asm.dynCall_iiiiiii.apply(null,arguments)};k.dynCall_viiff=function(){return k.asm.dynCall_viiff.apply(null,arguments)};k.dynCall_vifff=function(){return k.asm.dynCall_vifff.apply(null,arguments)};k.dynCall_viiiiii=function(){return k.asm.dynCall_viiiiii.apply(null,arguments)};
k.dynCall_ji=function(){return k.asm.dynCall_ji.apply(null,arguments)};k.dynCall_viij=function(){return k.asm.dynCall_viij.apply(null,arguments)};k.dynCall_iiijii=function(){return k.asm.dynCall_iiijii.apply(null,arguments)};k.dynCall_iiiiiiffffiiiffffi=function(){return k.asm.dynCall_iiiiiiffffiiiffffi.apply(null,arguments)};k.dynCall_iiiiiiiiffffiiiffffi=function(){return k.asm.dynCall_iiiiiiiiffffiiiffffi.apply(null,arguments)};k.dynCall_viff=function(){return k.asm.dynCall_viff.apply(null,arguments)};
k.dynCall_viiiiiii=function(){return k.asm.dynCall_viiiiiii.apply(null,arguments)};k.dynCall_viiiiiiii=function(){return k.asm.dynCall_viiiiiiii.apply(null,arguments)};k.dynCall_viiiiiiiii=function(){return k.asm.dynCall_viiiiiiiii.apply(null,arguments)};k.dynCall_viiffi=function(){return k.asm.dynCall_viiffi.apply(null,arguments)};k.dynCall_vif=function(){return k.asm.dynCall_vif.apply(null,arguments)};k.dynCall_jiji=function(){return k.asm.dynCall_jiji.apply(null,arguments)};
k.dynCall_iidiiii=function(){return k.asm.dynCall_iidiiii.apply(null,arguments)};k.dynCall_viijii=function(){return k.asm.dynCall_viijii.apply(null,arguments)};k.dynCall_iiiiiiiii=function(){return k.asm.dynCall_iiiiiiiii.apply(null,arguments)};k.dynCall_iiiiij=function(){return k.asm.dynCall_iiiiij.apply(null,arguments)};k.dynCall_iiiiid=function(){return k.asm.dynCall_iiiiid.apply(null,arguments)};k.dynCall_iiiiijj=function(){return k.asm.dynCall_iiiiijj.apply(null,arguments)};
k.dynCall_iiiiiiii=function(){return k.asm.dynCall_iiiiiiii.apply(null,arguments)};k.dynCall_iiiiiijj=function(){return k.asm.dynCall_iiiiiijj.apply(null,arguments)};k.asm=Kd;k.getMemory=function(a){if(Ta)var b=Aa(a);else b=w[12771528],a=b+a+15&-16,a>y.length&&u(),w[12771528]=a;return b};k.addRunDependency=bb;k.removeRunDependency=cb;k.FS_createFolder=Bc;k.FS_createPath=Cc;k.FS_createDataFile=Ec;k.FS_createPreloadedFile=Ic;k.FS_createLazyFile=Hc;k.FS_createLink=Fc;k.FS_createDevice=S;
k.FS_unlink=pc;k.calledRun=Ld;var Ld;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ab=function Md(){Ld||Nd();Ld||(ab=Md)};
function Nd(a){function b(){if(!Ld&&(Ld=!0,k.calledRun=!0,!v)){Ta=!0;k.noFSInit||zc||(zc=!0,yc(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?S("/dev","stdin",k.stdin):oc("/dev/tty","/dev/stdin"),k.stdout?S("/dev","stdout",null,k.stdout):oc("/dev/tty","/dev/stdout"),k.stderr?S("/dev","stderr",null,k.stderr):oc("/dev/tty1","/dev/stderr"),tc("/dev/stdin","r"),tc("/dev/stdout","w"),tc("/dev/stderr","w"));Na(Pa);Xb=!1;Na(Qa);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(Od){var b=
a,d=k._main;b=b||[];var e=b.length+1,g=Ga(4*(e+1));w[g>>2]=Fa(da);for(var h=1;h<e;h++)w[(g>>2)+h]=Fa(b[h-1]);w[(g>>2)+e]=0;try{var m=d(e,g);Id(m,!0)}catch(p){p instanceof pa||("SimulateInfiniteLoop"==p?wa=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),l("exception thrown: "+b),ea(1,p)))}finally{}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),Sa.unshift(b);Na(Sa)}}a=a||ca;if(!(0<Za)){if(k.preRun)for("function"==typeof k.preRun&&
(k.preRun=[k.preRun]);k.preRun.length;)Ua();Na(Oa);0<Za||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);b()},1)):b())}}k.run=Nd;function Id(a,b){if(!b||!wa||0!==a){if(!wa&&(v=!0,k.onExit))k.onExit(a);ea(a,new pa(a))}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var Od=!0;k.noInitialRun&&(Od=!1);wa=!0;Nd();
