var e;var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.la||(h.la=0,h.Va=0);h.la++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.L?h.D[a].loaded=c.loaded:(d.L=!0,h.D||(h.D={}),h.D[a]={loaded:c.loaded,total:f});var g=f=c=0,k;for(k in h.D){var m=h.D[k];c+=m.total;f+=m.loaded;g++}c=Math.ceil(c*h.la/g);h.setStatus&&h.setStatus("Downloading data... ("+f+"/"+c+")")}else!h.D&&h.setStatus&&h.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){h.Va++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);b.prototype.Ta=c;c=a.files;for(var d=
0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();h.removeRunDependency("datafile_Sample3.data")}b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;h.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.Ta.subarray(this.start,this.end))},finish:function(a){var b=this;h.FS_createPreloadedFile(this.name,null,a,!0,!0,function(){h.removeRunDependency("fp "+b.name)},function(){b.audio?h.removeRunDependency("fp "+b.name):l("Preloading file "+b.name+
" failed")},!1,!0);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].audio)).open("GET",d[f].filename);h.addRunDependency("datafile_Sample3.data");h.Ka||(h.Ka={});h.Ka["Sample3.data"]={Bb:!1};m?(c(m),m=null):k=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=h.locateFile?h.locateFile("Sample3.data",""):"Sample3.data",g=a.Ob,k=null,m=h.getPreloadedPackage?h.getPreloadedPackage(f,g):null;m||b(f,
g,function(a){k?(k(a),k=null):m=a},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))})({files:[{start:0,audio:0,end:122,filename:"/testImport.xml"}],remote_package_size:122,package_uuid:"5bb5e0fb-fbbe-40df-818f-f74bf7645c91"});var aa={},n;for(n in h)h.hasOwnProperty(n)&&(aa[n]=h[n]);var ba=[],ca="./this.program";function da(a,b){throw b;}var q=!1,u=!1,v=!1,ea=!1,fa=!1;q="object"===typeof window;u="function"===typeof importScripts;
v=(ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!q&&!u;fa=!q&&!v&&!u;var w="",x,ha,ia,ja,ka;
if(v)w=__dirname+"/",x=function(a,b){ja||(ja=require("fs"));ka||(ka=require("path"));a=ka.normalize(a);return ja.readFileSync(a,b?null:"utf8")},ia=function(a){a=x(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof la))throw a;}),process.on("unhandledRejection",y),da=function(a){process.exit(a)},
h.inspect=function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=typeof read&&(x=function(a){return read(a)}),ia=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(q||u)u?w=self.location.href:document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ha=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ma=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);for(n in aa)aa.hasOwnProperty(n)&&(h[n]=aa[n]);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);function na(a){oa||(oa={});oa[a]||(oa[a]=1,l(a))}var oa,pa;h.wasmBinary&&(pa=h.wasmBinary);var z;h.noExitRuntime&&(z=h.noExitRuntime);
"object"!==typeof WebAssembly&&l("no native wasm support detected");var A,qa=new WebAssembly.Table({initial:7320,maximum:7320,element:"anyfunc"}),C=!1;function assert(a,b){a||y("Assertion failed: "+b)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function ta(a){return a?sa(ua,a,void 0):""}
function va(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function xa(a){var b=wa(a)+1,c=ya(b);va(a,D,c,b);return c}function za(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,D,ua,Aa,E;
function Ba(a){buffer=a;h.HEAP8=D=new Int8Array(a);h.HEAP16=Aa=new Int16Array(a);h.HEAP32=E=new Int32Array(a);h.HEAPU8=ua=new Uint8Array(a);h.HEAPU16=new Uint16Array(a);h.HEAPU32=new Uint32Array(a);h.HEAPF32=new Float32Array(a);h.HEAPF64=new Float64Array(a)}var Ca=h.TOTAL_MEMORY||67108864;h.wasmMemory?A=h.wasmMemory:A=new WebAssembly.Memory({initial:Ca/65536});A&&(buffer=A.buffer);Ca=buffer.byteLength;Ba(buffer);E[30216]=5363904;
function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.m;"number"===typeof c?void 0===b.v?h.dynCall_v(c):h.dynCall_vi(c,b.v):c(void 0===b.v?null:b.v)}}}var Ea=[],Fa=[],Ga=[],Ha=[],Ia=[],La=!1;function Ma(){var a=h.preRun.shift();Ea.unshift(a)}var Na=Math.abs,Oa=Math.ceil,Pa=Math.floor,Qa=Math.min,F=0,Ra=null,Sa=null;function Ta(){F++;h.monitorRunDependencies&&h.monitorRunDependencies(F)}
function Ua(){F--;h.monitorRunDependencies&&h.monitorRunDependencies(F);if(0==F&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}h.preloadedImages={};h.preloadedAudios={};function y(a){if(h.onAbort)h.onAbort(a);ma(a);l(a);C=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Va(){var a=H;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var H="Sample3.wasm";if(!Va()){var Wa=H;H=h.locateFile?h.locateFile(Wa,w):w+Wa}function Xa(){try{if(pa)return new Uint8Array(pa);if(ia)return ia(H);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}
function Ya(){return pa||!q&&!u||"function"!==typeof fetch?new Promise(function(a){a(Xa())}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}var I,J;Fa.push({m:function(){Za()}});
function $a(a,b){e.b.ea=a;e.b.fa=b;if(e.b.m)if(0==a)e.b.A=function(){var a=Math.max(0,e.b.ob+b-K())|0;setTimeout(e.b.da,a)},e.b.method="timeout";else if(1==a)e.b.A=function(){e.requestAnimationFrame(e.b.da)},e.b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);u?(void 0===h.setImmediates&&(h.setImmediates=
[]),h.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}e.b.A=function(){setImmediate(e.b.da)};e.b.method="immediate"}}function K(){y()}
function ab(a,b,c,d,f){z=!0;assert(!e.b.m,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");e.b.m=a;e.b.v=d;var g="undefined"!==typeof d?function(){h.dynCall_vi(a,d)}:function(){h.dynCall_v(a)};var k=e.b.C;e.b.da=function(){if(!C)if(0<e.b.La.length){var a=Date.now(),b=e.b.La.shift();b.m(b.v);if(e.b.sa){var c=e.b.sa,d=0==c%1?c-1:Math.floor(c);e.b.sa=b.yb?d:(8*
c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");e.b.ub();k<e.b.C||setTimeout(e.b.da,0)}else k<e.b.C||(e.b.ka=e.b.ka+1|0,1==e.b.ea&&1<e.b.fa&&0!=e.b.ka%e.b.fa?e.b.A():(0==e.b.ea&&(e.b.ob=K()),"timeout"===e.b.method&&h.ja&&(l("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),e.b.method=
""),e.b.hb(g),k<e.b.C||e.b.A()))};f||(b&&0<b?$a(0,1E3/b):$a(1,1),e.b.A());if(c)throw"SimulateInfiniteLoop";}
e={b:{A:null,method:"",C:0,m:null,v:0,ea:0,fa:0,ka:0,La:[],pause:function(){e.b.A=null;e.b.C++},resume:function(){e.b.C++;var a=e.b.ea,b=e.b.fa,c=e.b.m;e.b.m=null;ab(c,0,!1,e.b.v,!0);$a(a,b);e.b.A()},ub:function(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=e.b.sa,c=e.b.Ab;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}},hb:function(a){if(!(C||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof la)return;b&&"object"===typeof b&&b.stack&&l("exception thrown: "+
[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}},M:!1,pa:!1,cb:[],workers:[],Da:function(){function a(){e.pa=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!e.Za){e.Za=!0;try{e.V=!0}catch(c){e.V=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}e.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:e.V?null:console.log("warning: no BlobBuilder");e.S="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Ja||"undefined"!==typeof e.S||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Ja=!0);h.preloadPlugins.push({canHandle:function(a){return!h.Ja&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(e.V)try{c=
new Blob([a],{type:e.ma(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:e.ma(b)}))}catch(t){na("Blob constructor present but fails: "+t+"; falling back to blob builder")}c||(c=new e.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=e.S.createObjectURL(c),p=new Image;p.onload=function(){assert(p.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=p.width;c.height=p.height;c.getContext("2d").drawImage(p,0,0);h.preloadedImages[b]=
c;e.S.revokeObjectURL(d);f&&f(a)};p.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};p.src=d}});h.preloadPlugins.push({canHandle:function(a){return!h.Kb&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){p||(p=!0,h.preloadedAudios[b]=c,f&&f(a))}function d(){p||(p=!0,h.preloadedAudios[b]=new Audio,g&&g())}var p=!1;if(e.V){try{var t=new Blob([a],{type:e.ma(b)})}catch(G){return d()}t=e.S.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",
function(){c(r)},!1);r.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,k=0;k<a.length;k++)for(f=f<<8|a[k],g+=8;6<=g;){var m=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[m]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");r.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(r)}};r.src=t;e.ib(function(){c(r)},1E4)}else return d()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",function(a){!e.pa&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&h.ja&&a==h.canvas)return h.ja;var f;if(b){var g={antialias:!1,alpha:!1,Hb:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof GL&&(f=GL.createContext(a,
g)))var m=GL.getContext(f).wb}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.ja=m,b&&GL.Ib(f),h.Vb=b,e.cb.forEach(function(a){a()}),e.Da());return m},zb:function(){},Aa:!1,W:void 0,I:void 0,requestFullscreen:function(a,b,c){function d(){e.M=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=e.exitFullscreen,e.W&&f.requestPointerLock(),e.M=!0,e.I?e.mb():e.R(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),e.I?e.nb():e.R(f));if(h.onFullScreen)h.onFullScreen(e.M);if(h.onFullscreen)h.onFullscreen(e.M)}e.W=a;e.I=b;e.Na=c;"undefined"===typeof e.W&&(e.W=!0);"undefined"===typeof e.I&&(e.I=!1);"undefined"===typeof e.Na&&(e.Na=null);var f=h.canvas;e.Aa||(e.Aa=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({Wb:c}):
g.requestFullscreen()},Ma:function(a,b,c){l("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");e.Ma=function(a,b,c){return e.requestFullscreen(a,b,c)};return e.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!e.M)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},G:0,Ua:function(a){var b=Date.now();if(0===e.G)e.G=
b+1E3/60;else for(;b+2>=e.G;)e.G+=1E3/60;setTimeout(a,Math.max(e.G-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=e.Ua;b(a)}},Qb:function(a){return function(){if(!C)return a.apply(null,arguments)}},K:!0,O:[],Mb:function(){e.K=!1},Pb:function(){e.K=!0;if(0<e.O.length){var a=e.O;e.O=[];a.forEach(function(a){a()})}},Rb:function(a){return e.requestAnimationFrame(function(){C||(e.K?a():e.O.push(a))})},ib:function(a,b){z=!0;return setTimeout(function(){C||
(e.K?a():e.O.push(a))},b)},Sb:function(a,b){z=!0;return setInterval(function(){C||e.K&&a()},b)},ma:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Wa:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},Xa:function(a){return a.movementY||
a.mozMovementY||a.webkitMovementY||0},Eb:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},$:0,aa:0,Y:0,Z:0,touches:{},Ea:{},xb:function(a){if(e.pa)"mousemove"!=a.type&&"mozMovementX"in a?e.Y=e.Z=0:
(e.Y=e.Wa(a),e.Z=e.Xa(a)),e.$+=e.Y,e.aa+=e.Z;else{var b=h.canvas.getBoundingClientRect(),c=h.canvas.width,d=h.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.Ub;if(void 0!==k)if(f=k.pageX-(f+b.left),g=k.pageY-(g+b.top),f*=c/b.width,g*=d/b.height,b={x:f,y:g},"touchstart"===a.type)e.Ea[k.identifier]=b,e.touches[k.identifier]=
b;else if("touchend"===a.type||"touchmove"===a.type)(a=e.touches[k.identifier])||(a=b),e.Ea[k.identifier]=a,e.touches[k.identifier]=b}else k=a.pageX-(f+b.left),a=a.pageY-(g+b.top),k*=c/b.width,a*=d/b.height,e.Y=k-e.$,e.Z=a-e.aa,e.$=k,e.aa=a}},Ra:function(a,b,c,d){var f=d?"":"al "+a;ha(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));f&&Ua(f)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});f&&Ta(f)},gb:[],ta:function(){var a=h.canvas;
e.gb.forEach(function(b){b(a.width,a.height)})},jb:function(a,b,c){e.R(h.canvas,a,b);c||e.ta()},Zb:0,Yb:0,mb:function(){e.R(h.canvas);e.ta()},nb:function(){e.R(h.canvas);e.ta()},R:function(a,b,c){b&&c?(a.vb=b,a.Ya=c):(b=a.vb,c=a.Ya);var d=b,f=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/f<h.forcedAspectRatio?d=Math.round(f*h.forcedAspectRatio):f=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}e.I?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):
(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Xb:{},Ia:0,Fb:function(){var a=e.Ia;e.Ia++;return a}};function bb(a,b){Ha.unshift({m:a,v:b})}function L(a){h.___errno_location&&(E[h.___errno_location()>>2]=a)}function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function M(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var hb=[];function ib(a,b){hb[a]={input:[],output:[],H:b};jb(a,kb)}
var kb={open:function(a){var b=hb[a.node.rdev];if(!b)throw new N(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.H.flush(a.tty)},flush:function(a){a.tty.H.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.H.Ba)throw new N(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.H.Ba(a.tty)}catch(m){throw new N(29);}if(void 0===k&&0===f)throw new N(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.H.qa)throw new N(60);try{for(var f=
0;f<d;f++)a.tty.H.qa(a.tty,b[c+f])}catch(g){throw new N(29);}d&&(a.node.timestamp=Date.now());return f}},mb={Ba:function(a){if(!a.input.length){var b=null;if(v){var c=Buffer.L?Buffer.L(256):new Buffer(256),d=0;try{d=ja.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=lb(b,!0)}return a.input.shift()},qa:function(a,b){null===b||10===b?(ma(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ma(sa(a.output,0)),a.output=[])}},nb={qa:function(a,b){null===b||10===b?(l(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(sa(a.output,0)),a.output=[])}},O={s:null,u:function(){return O.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.s||(O.s={dir:{node:{o:O.f.o,j:O.f.j,lookup:O.f.lookup,X:O.f.X,rename:O.f.rename,unlink:O.f.unlink,rmdir:O.f.rmdir,readdir:O.f.readdir,symlink:O.f.symlink},stream:{B:O.g.B}},file:{node:{o:O.f.o,j:O.f.j},stream:{B:O.g.B,read:O.g.read,write:O.g.write,ua:O.g.ua,Ga:O.g.Ga,ba:O.g.ba}},link:{node:{o:O.f.o,j:O.f.j,readlink:O.f.readlink},stream:{}},wa:{node:{o:O.f.o,j:O.f.j},stream:ob}});c=pb(a,b,c,d);16384===(c.mode&61440)?
(c.f=O.s.dir.node,c.g=O.s.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=O.s.file.node,c.g=O.s.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=O.s.link.node,c.g=O.s.link.stream):8192===(c.mode&61440)&&(c.f=O.s.wa.node,c.g=O.s.wa.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},Cb:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},Db:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},ya:function(a,
b){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))},fb:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Sa=4096;b.blocks=Math.ceil(b.size/b.Sa);return b},j:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.fb(a,b.size)},lookup:function(){throw qb[44];},X:function(a,b,c,d){return O.createNode(a,
b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=P(b,c)}catch(g){}if(d)for(var f in d.c)throw new N(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=P(a,b),d;for(d in c.c)throw new N(55);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&
61440))throw new N(28);return a.link}},g:{read:function(a,b,c,d,f){var g=a.node.c;if(f>=a.node.h)return 0;a=Math.min(a.node.h-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===D.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===f)return a.c=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(f+d<=a.h)return a.c.set(b.subarray(c,
c+d),f),d}O.ya(a,f+d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.c[f+g]=b[c+g];a.h=Math.max(a.h,f+d);return d},B:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new N(28);return b},ua:function(a,b,c){O.ya(a.node,b+c);a.node.h=Math.max(a.node.h,b+c)},Ga:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new N(43);c=a.node.c;if(k&2||c.buffer!==b.buffer){if(0<f||f+d<a.node.h)c.subarray?c=c.subarray(f,f+
d):c=Array.prototype.slice.call(c,f,f+d);a=!0;f=b.buffer==D.buffer;d=rb(d);if(!d)throw new N(48);(f?D:b).set(c,d)}else a=!1,d=c.byteOffset;return{Nb:d,Qa:a}},ba:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new N(43);if(f&2)return 0;O.g.write(a,b,0,d,c,!1);return 0}}},sb=null,tb={},ub=[],vb=1,R=null,wb=!0,S={},N=null,qb={};
function T(a,b){a=gb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={za:!0,ra:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ra)throw new N(32);a=cb(a.split("/").filter(function(a){return!!a}),!1);var f=sb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=P(f,a[d]);c=M(c+"/"+a[d]);f.N&&(!g||g&&b.za)&&(f=f.N.root);if(!g||b.U)for(g=0;40960===(f.mode&61440);)if(f=xb(c),c=gb(db(c),f),f=T(c,{ra:b.ra}).node,40<g++)throw new N(32);}return{path:c,node:f}}
function U(a){for(var b;;){if(a===a.parent)return a=a.u.Ha,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function yb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function zb(a){var b=yb(a.parent.id,a.name);a.F=R[b];R[b]=a}function P(a,b){var c;if(c=(c=Ab(a,"x"))?c:a.f.lookup?0:2)throw new N(c,a);for(c=R[yb(a.id,b)];c;c=c.F){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.lookup(a,b)}
function pb(a,b,c,d){Bb||(Bb=function(a,b,c,d){a||(a=this);this.parent=a;this.u=a.u;this.N=null;this.id=vb++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=d},Bb.prototype={},Object.defineProperties(Bb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},bb:{get:function(){return 16384===(this.mode&61440)}},ab:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Bb(a,b,c,d);zb(a);return a}var Cb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Eb(a,b){try{return P(a,b),20}catch(c){}return Ab(a,"wx")}
function Fb(a){var b=4096;for(a=a||0;a<=b;a++)if(!ub[a])return a;throw new N(33);}function Gb(a,b){Hb||(Hb=function(){},Hb.prototype={},Object.defineProperties(Hb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Hb,d;for(d in a)c[d]=a[d];a=c;b=Fb(b);a.fd=b;return ub[b]=a}var ob={open:function(a){a.g=tb[a.node.rdev].g;a.g.open&&a.g.open(a)},B:function(){throw new N(70);}};function jb(a,b){tb[a]={g:b}}
function Ib(a,b){var c="/"===b,d=!b;if(c&&sb)throw new N(10);if(!c&&!d){var f=T(b,{za:!1});b=f.path;f=f.node;if(f.N)throw new N(10);if(16384!==(f.mode&61440))throw new N(54);}b={type:a,Lb:{},Ha:b,eb:[]};a=a.u(b);a.u=b;b.root=a;c?sb=a:f&&(f.N=b,f.u&&f.u.eb.push(b))}function Jb(a,b,c){var d=T(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new N(28);var f=Eb(d,a);if(f)throw new N(f);if(!d.f.X)throw new N(63);return d.f.X(d,a,b,c)}
function V(a,b){return Jb(a,(void 0!==b?b:511)&1023|16384,0)}function Kb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Jb(a,b|8192,c)}function Lb(a,b){if(!gb(a))throw new N(44);var c=T(b,{parent:!0}).node;if(!c)throw new N(44);b=fb(b);var d=Eb(c,b);if(d)throw new N(d);if(!c.f.symlink)throw new N(63);return c.f.symlink(c,b,a)}
function Mb(a){var b=T(a,{parent:!0}).node,c=fb(a),d=P(b,c);a:{try{var f=P(b,c)}catch(k){f=k.l;break a}var g=Ab(b,"wx");f=g?g:16384===(f.mode&61440)?31:0}if(f)throw new N(f);if(!b.f.unlink)throw new N(63);if(d.N)throw new N(10);try{S.willDeletePath&&S.willDeletePath(a)}catch(k){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.f.unlink(b,c);b=yb(d.parent.id,d.name);if(R[b]===d)R[b]=d.F;else for(b=R[b];b;){if(b.F===d){b.F=d.F;break}b=b.F}try{if(S.onDeletePath)S.onDeletePath(a)}catch(k){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function xb(a){a=T(a).node;if(!a)throw new N(44);if(!a.f.readlink)throw new N(28);return gb(U(a.parent),a.f.readlink(a))}function Nb(a,b){var c;"string"===typeof a?c=T(a,{U:!0}).node:c=a;if(!c.f.j)throw new N(63);c.f.j(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Ob(a,b,c,d){if(""===a)throw new N(44);if("string"===typeof b){var f=Cb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=M(a);try{g=T(a,{U:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(g){if(b&128)throw new N(20);}else g=Jb(a,c,0),f=!0;if(!g)throw new N(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new N(54);if(!f&&(c=g?40960===(g.mode&61440)?32:
16384===(g.mode&61440)&&("r"!==Db(b)||b&512)?31:Ab(g,Db(b)):44))throw new N(c);if(b&512){c=g;var k;"string"===typeof c?k=T(c,{U:!0}).node:k=c;if(!k.f.j)throw new N(63);if(16384===(k.mode&61440))throw new N(31);if(32768!==(k.mode&61440))throw new N(28);if(c=Ab(k,"w"))throw new N(c);k.f.j(k,{size:0,timestamp:Date.now()})}b&=-641;d=Gb({node:g,path:U(g),flags:b,seekable:!0,position:0,g:g.g,tb:[],error:!1},d);d.g.open&&d.g.open(d);!h.logReadFiles||b&1||(Pb||(Pb={}),a in Pb||(Pb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{S.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),S.onOpenFile(a,g))}catch(m){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Qb(a){if(null===a.fd)throw new N(8);a.na&&(a.na=null);try{a.g.close&&a.g.close(a)}catch(b){throw b;}finally{ub[a.fd]=null}a.fd=null}
function Rb(a,b,c){if(null===a.fd)throw new N(8);if(!a.seekable||!a.g.B)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.g.B(a,b,c);a.tb=[]}
function Sb(a,b,c,d,f,g){if(0>d||0>f)throw new N(28);if(null===a.fd)throw new N(8);if(0===(a.flags&2097155))throw new N(8);if(16384===(a.node.mode&61440))throw new N(31);if(!a.g.write)throw new N(28);a.flags&1024&&Rb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new N(70);b=a.g.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(m){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
m.message)}return b}function Tb(){N||(N=function(a,b){this.node=b;this.lb=function(a){this.l=a};this.lb(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(function(a){qb[a]=new N(a);qb[a].stack="<generic error, no stack>"}))}var Ub;function Vb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Wb(a,b,c,d){a=M(("string"===typeof a?a:U(a))+"/"+b);return V(a,Vb(c,d))}
function Xb(a,b){a="string"===typeof a?a:U(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=M(a+"/"+c);try{V(d)}catch(f){}a=d}}return d}function Yb(a,b,c,d){a=M(("string"===typeof a?a:U(a))+"/"+b);c=Vb(c,d);return Jb(a,(void 0!==c?c:438)&4095|32768,0)}
function Zb(a,b,c,d,f,g){a=b?M(("string"===typeof a?a:U(a))+"/"+b):a;d=Vb(d,f);f=Jb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Nb(f,d|146);a=Ob(f,"w");Sb(a,c,0,c.length,0,g);Qb(a);Nb(f,d)}return f}
function W(a,b,c,d){a=M(("string"===typeof a?a:U(a))+"/"+b);b=Vb(!!c,!!d);W.Fa||(W.Fa=64);var f=W.Fa++<<8|0;jb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,k=0;k<f;k++){try{var m=c()}catch(B){throw new N(29);}if(void 0===m&&0===g)throw new N(6);if(null===m||void 0===m)break;g++;b[d+k]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(r){throw new N(29);}f&&(a.node.timestamp=
Date.now());return g}});return Kb(a,b,f)}function $b(a,b,c){a=M(("string"===typeof a?a:U(a))+"/"+b);return Lb(c,a)}
function ac(a){if(a.ab||a.bb||a.link||a.c)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(x)try{a.c=lb(x(a.url),!0),a.h=a.c.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||L(29);return b}
function bc(a,b,c,d,f){function g(){this.oa=!1;this.T=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Ca(a/this.chunkSize|0)[b]}};g.prototype.kb=function(a){this.Ca=a};g.prototype.va=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var k=this;k.kb(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof k.T[a]){var Q=k.T;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var m=new XMLHttpRequest;m.open("GET",c,!1);b!==g&&m.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(m.responseType="arraybuffer");m.overrideMimeType&&
m.overrideMimeType("text/plain; charset=x-user-defined");m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);d=void 0!==m.response?new Uint8Array(m.response||[]):lb(m.responseText||"",!0);Q[a]=d}if("undefined"===typeof k.T[a])throw Error("doXHR failed!");return k.T[a]});if(a||!b)g=b=1,g=b=this.Ca(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Pa=b;this.Oa=g;this.oa=!0};if("undefined"!==
typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.oa||this.va();return this.Pa}},chunkSize:{get:function(){this.oa||this.va();return this.Oa}}});var m=void 0}else m=c,k=void 0;var p=Yb(a,b,d,f);k?p.c=k:m&&(p.c=null,p.url=m);Object.defineProperties(p,{h:{get:function(){return this.c.length}}});var t={};Object.keys(p.g).forEach(function(a){var b=
p.g[a];t[a]=function(){if(!ac(p))throw new N(29);return b.apply(null,arguments)}});t.read=function(a,b,c,d,f){if(!ac(p))throw new N(29);a=a.node.c;if(f>=a.length)return 0;d=Math.min(a.length-f,d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};p.g=t;return p}
function cc(a,b,c,d,f,g,k,m,p,t){function r(c){function Q(c){t&&t();m||Zb(a,b,c,d,f,p);g&&g();Ua(B)}var r=!1;h.preloadPlugins.forEach(function(a){!r&&a.canHandle(G)&&(a.handle(c,G,Q,function(){k&&k();Ua(B)}),r=!0)});r||Q(c)}e.Da();var G=b?gb(M(a+"/"+b)):a,B="cp "+G;Ta(B);"string"==typeof c?e.Ra(c,function(a){r(a)},k):r(c)}var X={},Bb,Hb,Pb,dc={},Y=0;function Z(){Y+=4;return E[Y-4>>2]}function ec(a){void 0===a&&(a=Z());a=ub[a];if(!a)throw new N(8);return a}var fc={};
function hc(){if(!ic){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca},b;for(b in fc)a[b]=fc[b];var c=[];for(b in a)c.push(b+"="+a[b]);ic=c}return ic}var ic;function jc(a){return 0===a%4&&(0!==a%100||0===a%400)}function kc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var lc=[31,29,31,30,31,30,31,31,30,31,30,31],mc=[31,28,31,30,31,30,31,31,30,31,30,31];
function nc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(jc(a.getFullYear())?lc:mc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function oc(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function m(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=nc(new Date(a.i+1900,0,1),a.ia);var b=m(new Date(a.getFullYear()+1,0,4));return 0>=k(m(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var t=E[d+40>>2];d={rb:E[d>>2],qb:E[d+4>>2],ga:E[d+8>>2],P:E[d+12>>2],J:E[d+16>>2],i:E[d+20>>2],ha:E[d+24>>2],ia:E[d+28>>2],Tb:E[d+32>>2],pb:E[d+36>>2],sb:t?
ta(t):""};c=ta(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var G="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
B="January February March April May June July August September October November December".split(" ");t={"%a":function(a){return G[a.ha].substring(0,3)},"%A":function(a){return G[a.ha]},"%b":function(a){return B[a.J].substring(0,3)},"%B":function(a){return B[a.J]},"%C":function(a){return g((a.i+1900)/100|0,2)},"%d":function(a){return g(a.P,2)},"%e":function(a){return f(a.P,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return g(a.ga,2)},
"%I":function(a){a=a.ga;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.P+kc(jc(a.i+1900)?lc:mc,a.J-1),3)},"%m":function(a){return g(a.J+1,2)},"%M":function(a){return g(a.qb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.ga&&12>a.ga?"AM":"PM"},"%S":function(a){return g(a.rb,2)},"%t":function(){return"\t"},"%u":function(a){return a.ha||7},"%U":function(a){var b=new Date(a.i+1900,0,1),c=0===b.getDay()?b:nc(b,7-b.getDay());a=new Date(a.i+1900,a.J,a.P);return 0>k(c,a)?
g(Math.ceil((31-c.getDate()+(kc(jc(a.getFullYear())?lc:mc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=m(new Date(a.i+1900,0,4)),c=m(new Date(a.i+1901,0,4)),d=nc(new Date(a.i+1900,0,1),a.ia);return 0>k(d,b)?"53":0>=k(c,d)?"01":g(Math.ceil((b.getFullYear()<a.i+1900?a.ia+32-b.getDate():a.ia+1-b.getDate())/7),2)},"%w":function(a){return a.ha},"%W":function(a){var b=new Date(a.i,0,1),c=1===b.getDay()?b:nc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.i+1900,a.J,
a.P);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(kc(jc(a.getFullYear())?lc:mc,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.i+1900).toString().substring(2)},"%Y":function(a){return a.i+1900},"%z":function(a){a=a.pb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.sb},"%%":function(){return"%"}};for(r in t)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=lb(c,!1);if(r.length>b)return 0;
D.set(r,a);return r.length-1}h.requestFullScreen=function(a,b,c){l("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");h.requestFullScreen=h.requestFullscreen;e.Ma(a,b,c)};h.requestFullscreen=function(a,b,c){e.requestFullscreen(a,b,c)};h.requestAnimationFrame=function(a){e.requestAnimationFrame(a)};h.setCanvasSize=function(a,b,c){e.jb(a,b,c)};h.pauseMainLoop=function(){e.b.pause()};h.resumeMainLoop=function(){e.b.resume()};h.getUserMedia=function(){e.getUserMedia()};
h.createContext=function(a,b,c,d){return e.createContext(a,b,c,d)};v?K=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?K=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?K=function(){return performance.now()}:K=Date.now;Tb();R=Array(4096);Ib(O,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");jb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Kb("/dev/null",259);ib(1280,mb);ib(1536,nb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(v)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){y("random_device")});W("/dev","random",b);W("/dev","urandom",b);V("/dev/shm");
V("/dev/shm/tmp")})();V("/proc");V("/proc/self");V("/proc/self/fd");Ib({u:function(){var a=pb("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=ub[+c];if(!b)throw new N(8);a={parent:null,u:{Ha:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");h.FS_createFolder=Wb;h.FS_createPath=Xb;h.FS_createDataFile=Zb;h.FS_createPreloadedFile=cc;h.FS_createLazyFile=bc;h.FS_createLink=$b;h.FS_createDevice=W;h.FS_unlink=Mb;
function lb(a,b){var c=Array(wa(a)+1);a=va(a,c,0,c.length);b&&(c.length=a);return c}
var rc={__cxa_allocate_exception:function(a){return rb(a)},__cxa_atexit:function(){return bb.apply(null,arguments)},__cxa_throw:function(a){"uncaught_exception"in pc?pc.L++:pc.L=1;throw a;},__lock:function(){},__map_file:function(){L(63);return-1},__syscall195:function(a,b){Y=b;try{var c=ta(Z());a:{var d=Z();try{var f=T(c,{U:!0}).node;if(!f)throw new N(44);if(!f.f.o)throw new N(63);var g=f.f.o(f)}catch(m){if(m&&m.node&&M(c)!==M(U(m.node))){var k=-54;break a}throw m;}E[d>>2]=g.dev;E[d+4>>2]=0;E[d+
8>>2]=g.ino;E[d+12>>2]=g.mode;E[d+16>>2]=g.nlink;E[d+20>>2]=g.uid;E[d+24>>2]=g.gid;E[d+28>>2]=g.rdev;E[d+32>>2]=0;J=[g.size>>>0,(I=g.size,1<=+Na(I)?0<I?(Qa(+Pa(I/4294967296),4294967295)|0)>>>0:~~+Oa((I-+(~~I>>>0))/4294967296)>>>0:0)];E[d+40>>2]=J[0];E[d+44>>2]=J[1];E[d+48>>2]=4096;E[d+52>>2]=g.blocks;E[d+56>>2]=g.atime.getTime()/1E3|0;E[d+60>>2]=0;E[d+64>>2]=g.mtime.getTime()/1E3|0;E[d+68>>2]=0;E[d+72>>2]=g.ctime.getTime()/1E3|0;E[d+76>>2]=0;J=[g.ino>>>0,(I=g.ino,1<=+Na(I)?0<I?(Qa(+Pa(I/4294967296),
4294967295)|0)>>>0:~~+Oa((I-+(~~I>>>0))/4294967296)>>>0:0)];E[d+80>>2]=J[0];E[d+84>>2]=J[1];k=0}return k}catch(m){return"undefined"!==typeof X&&m instanceof N||y(m),-m.l}},__syscall221:function(a,b){Y=b;try{var c=ec();switch(Z()){case 0:var d=Z();return 0>d?-28:Ob(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Z(),c.flags|=d,0;case 12:return d=Z(),Aa[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return L(28),-1;default:return-28}}catch(f){return"undefined"!==
typeof X&&f instanceof N||y(f),-f.l}},__syscall39:function(a,b){Y=b;try{var c=ta(Z()),d=Z();a=c;a=M(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));V(a,d);return 0}catch(f){return"undefined"!==typeof X&&f instanceof N||y(f),-f.l}},__syscall5:function(a,b){Y=b;try{var c=ta(Z()),d=Z(),f=Z();return Ob(c,d,f).fd}catch(g){return"undefined"!==typeof X&&g instanceof N||y(g),-g.l}},__syscall54:function(a,b){Y=b;try{var c=ec(),d=Z();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-59;case 21519:if(!c.tty)return-59;var f=Z();return E[f>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=f=Z();if(!c.g.$a)throw new N(59);return c.g.$a(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:y("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof X&&g instanceof N||y(g),-g.l}},__syscall91:function(a,b){Y=b;try{var c=Z(),d=Z();if(-1===c||0===d)var f=-28;else{var g=dc[c];if(g&&d===g.Gb){var k=ub[g.fd],m=g.flags,p=new Uint8Array(ua.subarray(c,c+d));k&&k.g.ba&&
k.g.ba(k,p,0,d,m);dc[c]=null;g.Qa&&qc(g.Jb)}f=0}return f}catch(t){return"undefined"!==typeof X&&t instanceof N||y(t),-t.l}},__unlock:function(){},abort:function(){y()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(v||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=K();else return L(28),-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_cancel_main_loop:function(){e.b.pause();e.b.m=null},emscripten_get_sbrk_ptr:function(){return 120864},
emscripten_memcpy_big:function(a,b,c){ua.set(ua.subarray(b,b+c),a)},emscripten_resize_heap:function(a){if(2147418112<a)return!1;for(var b=Math.max(D.length,16777216);b<a;)536870912>=b?b=za(2*b):b=Math.min(za((3*b+2147483648)/4),2147418112);a:{try{A.grow(b-buffer.byteLength+65535>>16);Ba(A.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},emscripten_set_main_loop:ab,environ_get:function(a,b){var c=0;hc().forEach(function(d,f){var g=b+c;f=E[a+4*f>>2]=g;for(g=0;g<d.length;++g)D[f++>>0]=d.charCodeAt(g);
D[f>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=hc();E[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});E[b>>2]=d;return 0},fd_close:function(a){try{var b=ec(a);Qb(b);return 0}catch(c){return"undefined"!==typeof X&&c instanceof N||y(c),c.l}},fd_read:function(a,b,c,d){try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=E[b+(8*g+4)>>2],m=f,p=E[b+8*g>>2],t=k,r=void 0,G=D;if(0>t||0>r)throw new N(28);if(null===m.fd)throw new N(8);if(1===(m.flags&2097155))throw new N(8);if(16384===
(m.node.mode&61440))throw new N(31);if(!m.g.read)throw new N(28);var B="undefined"!==typeof r;if(!B)r=m.position;else if(!m.seekable)throw new N(70);var Q=m.g.read(m,G,p,t,r);B||(m.position+=Q);var Ja=Q;if(0>Ja){var eb=-1;break a}a+=Ja;if(Ja<k)break}eb=a}E[d>>2]=eb;return 0}catch(Ka){return"undefined"!==typeof X&&Ka instanceof N||y(Ka),Ka.l}},fd_seek:function(a,b,c,d,f){try{var g=ec(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Rb(g,a,d);J=[g.position>>>0,(I=g.position,
1<=+Na(I)?0<I?(Qa(+Pa(I/4294967296),4294967295)|0)>>>0:~~+Oa((I-+(~~I>>>0))/4294967296)>>>0:0)];E[f>>2]=J[0];E[f+4>>2]=J[1];g.na&&0===a&&0===d&&(g.na=null);return 0}catch(k){return"undefined"!==typeof X&&k instanceof N||y(k),k.l}},fd_write:function(a,b,c,d){try{a:{for(var f=ec(a),g=a=0;g<c;g++){var k=Sb(f,D,E[b+8*g>>2],E[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}E[d>>2]=m;return 0}catch(p){return"undefined"!==typeof X&&p instanceof N||y(p),p.l}},memory:A,nanosleep:function(a,b){if(0===
a)return L(28),-1;var c=E[a>>2];a=E[a+4>>2];if(0>a||999999999<a||0>c)return L(28),-1;0!==b&&(E[b>>2]=0,E[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((q||u)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},pthread_equal:function(a,b){return a==b},pthread_mutexattr_destroy:function(){},pthread_mutexattr_init:function(){},pthread_mutexattr_settype:function(){},sched_yield:function(){return 0},setTempRet0:function(){},
strftime_l:function(a,b,c,d){return oc(a,b,c,d)},table:qa},sc=function(){function a(a){h.asm=a.exports;Ua("wasm-instantiate")}function b(b){a(b.instance)}function c(a){return Ya().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){l("failed to asynchronously prepare wasm: "+a);y(a)})}var d={env:rc,wasi_unstable:rc};Ta("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(f){return l("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(pa||
"function"!==typeof WebAssembly.instantiateStreaming||Va()||"function"!==typeof fetch)return c(b);fetch(H,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,d).then(b,function(a){l("wasm streaming compile failed: "+a);l("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();h.asm=sc;var Za=h.___wasm_call_ctors=function(){return h.asm.__wasm_call_ctors.apply(null,arguments)},qc=h._free=function(){return h.asm.free.apply(null,arguments)};
h._main=function(){return h.asm.main.apply(null,arguments)};var rb=h._malloc=function(){return h.asm.malloc.apply(null,arguments)};h.___errno_location=function(){return h.asm.__errno_location.apply(null,arguments)};h.__get_tzname=function(){return h.asm._get_tzname.apply(null,arguments)};h.__get_daylight=function(){return h.asm._get_daylight.apply(null,arguments)};h.__get_timezone=function(){return h.asm._get_timezone.apply(null,arguments)};
h._setThrew=function(){return h.asm.setThrew.apply(null,arguments)};var pc=h.__ZSt18uncaught_exceptionv=function(){return h.asm._ZSt18uncaught_exceptionv.apply(null,arguments)};h.stackSave=function(){return h.asm.stackSave.apply(null,arguments)};var ya=h.stackAlloc=function(){return h.asm.stackAlloc.apply(null,arguments)};h.stackRestore=function(){return h.asm.stackRestore.apply(null,arguments)};h.__growWasmMemory=function(){return h.asm.__growWasmMemory.apply(null,arguments)};
h.dynCall_iii=function(){return h.asm.dynCall_iii.apply(null,arguments)};h.dynCall_ii=function(){return h.asm.dynCall_ii.apply(null,arguments)};h.dynCall_vi=function(){return h.asm.dynCall_vi.apply(null,arguments)};h.dynCall_iiiiii=function(){return h.asm.dynCall_iiiiii.apply(null,arguments)};h.dynCall_vii=function(){return h.asm.dynCall_vii.apply(null,arguments)};h.dynCall_viii=function(){return h.asm.dynCall_viii.apply(null,arguments)};
h.dynCall_iiii=function(){return h.asm.dynCall_iiii.apply(null,arguments)};h.dynCall_iij=function(){return h.asm.dynCall_iij.apply(null,arguments)};h.dynCall_iif=function(){return h.asm.dynCall_iif.apply(null,arguments)};h.dynCall_iid=function(){return h.asm.dynCall_iid.apply(null,arguments)};h.dynCall_iiiii=function(){return h.asm.dynCall_iiiii.apply(null,arguments)};h.dynCall_iijii=function(){return h.asm.dynCall_iijii.apply(null,arguments)};
h.dynCall_iifii=function(){return h.asm.dynCall_iifii.apply(null,arguments)};h.dynCall_iidii=function(){return h.asm.dynCall_iidii.apply(null,arguments)};h.dynCall_v=function(){return h.asm.dynCall_v.apply(null,arguments)};h.dynCall_i=function(){return h.asm.dynCall_i.apply(null,arguments)};h.dynCall_fi=function(){return h.asm.dynCall_fi.apply(null,arguments)};h.dynCall_di=function(){return h.asm.dynCall_di.apply(null,arguments)};h.dynCall_ji=function(){return h.asm.dynCall_ji.apply(null,arguments)};
h.dynCall_viiii=function(){return h.asm.dynCall_viiii.apply(null,arguments)};h.dynCall_vid=function(){return h.asm.dynCall_vid.apply(null,arguments)};h.dynCall_jiji=function(){return h.asm.dynCall_jiji.apply(null,arguments)};h.dynCall_iidiiii=function(){return h.asm.dynCall_iidiiii.apply(null,arguments)};h.dynCall_viijii=function(){return h.asm.dynCall_viijii.apply(null,arguments)};h.dynCall_iiiiiiiii=function(){return h.asm.dynCall_iiiiiiiii.apply(null,arguments)};
h.dynCall_iiiiiii=function(){return h.asm.dynCall_iiiiiii.apply(null,arguments)};h.dynCall_iiiiij=function(){return h.asm.dynCall_iiiiij.apply(null,arguments)};h.dynCall_iiiiid=function(){return h.asm.dynCall_iiiiid.apply(null,arguments)};h.dynCall_iiiiijj=function(){return h.asm.dynCall_iiiiijj.apply(null,arguments)};h.dynCall_iiiiiiii=function(){return h.asm.dynCall_iiiiiiii.apply(null,arguments)};h.dynCall_iiiiiijj=function(){return h.asm.dynCall_iiiiiijj.apply(null,arguments)};
h.dynCall_viiiiii=function(){return h.asm.dynCall_viiiiii.apply(null,arguments)};h.dynCall_viiiii=function(){return h.asm.dynCall_viiiii.apply(null,arguments)};h.asm=sc;h.getMemory=function(a){if(La)var b=rb(a);else b=E[30216],a=b+a+15&-16,a>D.length&&y(),E[30216]=a;return b};h.addRunDependency=Ta;h.removeRunDependency=Ua;h.FS_createFolder=Wb;h.FS_createPath=Xb;h.FS_createDataFile=Zb;h.FS_createPreloadedFile=cc;h.FS_createLazyFile=bc;h.FS_createLink=$b;h.FS_createDevice=W;h.FS_unlink=Mb;
h.calledRun=tc;var tc;function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function uc(){tc||vc();tc||(Sa=uc)};
function vc(a){function b(){if(!tc&&(tc=!0,h.calledRun=!0,!C)){La=!0;h.noFSInit||Ub||(Ub=!0,Tb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?W("/dev","stdin",h.stdin):Lb("/dev/tty","/dev/stdin"),h.stdout?W("/dev","stdout",null,h.stdout):Lb("/dev/tty","/dev/stdout"),h.stderr?W("/dev","stderr",null,h.stderr):Lb("/dev/tty1","/dev/stderr"),Ob("/dev/stdin","r"),Ob("/dev/stdout","w"),Ob("/dev/stderr","w"));Da(Fa);wb=!1;Da(Ga);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(wc){var b=
a,d=h._main;b=b||[];var f=b.length+1,g=ya(4*(f+1));E[g>>2]=xa(ca);for(var k=1;k<f;k++)E[(g>>2)+k]=xa(b[k-1]);E[(g>>2)+f]=0;try{var m=d(f,g);if(!z||0!==m){if(!z&&(C=!0,h.onExit))h.onExit(m);da(m,new la(m))}}catch(p){p instanceof la||("SimulateInfiniteLoop"==p?z=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),l("exception thrown: "+b),da(1,p)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),Ia.unshift(b);Da(Ia)}}a=a||ba;
if(!(0<F)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ma();Da(Ea);0<F||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=vc;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var wc=!0;h.noInitialRun&&(wc=!1);z=!0;vc();
