var e;var h;h||(h=typeof Module !== 'undefined' ? Module : {});var l={},m;for(m in h)h.hasOwnProperty(m)&&(l[m]=h[m]);var p=[],aa="./this.program";function u(a,b){throw b;}var v=!1,w=!1,x=!1,ba=!1,ca=!1;v="object"===typeof window;w="function"===typeof importScripts;x=(ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!v&&!w;ca=!v&&!x&&!w;var y="",da,ea,z,fa,ha;
if(x)y=__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},z=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),p=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",A),u=function(a){process.exit(a)},
h.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),z=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?p=scriptArgs:"undefined"!=typeof arguments&&(p=arguments),"function"===typeof quit&&(u=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(v||w)w?y=self.location.href:document.currentScript&&(y=document.currentScript.src),y=0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},w&&(z=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=h.print||console.log.bind(console),B=h.printErr||console.warn.bind(console);for(m in l)l.hasOwnProperty(m)&&(h[m]=l[m]);l=null;h.arguments&&(p=h.arguments);h.thisProgram&&(aa=h.thisProgram);h.quit&&(u=h.quit);function ka(a){la||(la={});la[a]||(la[a]=1,B(a))}var la,ma;h.wasmBinary&&(ma=h.wasmBinary);var C;h.noExitRuntime&&(C=h.noExitRuntime);
"object"!==typeof WebAssembly&&B("no native wasm support detected");var oa,pa=new WebAssembly.Table({initial:2966,maximum:2966,element:"anyfunc"}),D=!1;function assert(a,b){a||A("Assertion failed: "+b)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function sa(a){return a?ra(ta,a,void 0):""}
function ua(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function wa(a){var b=va(a)+1,c=xa(b);ua(a,E,c,b);return c}var buffer,E,ta,ya,F,za=h.TOTAL_MEMORY||16777216;h.wasmMemory?oa=h.wasmMemory:oa=new WebAssembly.Memory({initial:za/65536,maximum:za/65536});oa&&(buffer=oa.buffer);za=buffer.byteLength;var H=buffer;
buffer=H;h.HEAP8=E=new Int8Array(H);h.HEAP16=ya=new Int16Array(H);h.HEAP32=F=new Int32Array(H);h.HEAPU8=ta=new Uint8Array(H);h.HEAPU16=new Uint16Array(H);h.HEAPU32=new Uint32Array(H);h.HEAPF32=new Float32Array(H);h.HEAPF64=new Float64Array(H);F[19032]=5319168;function Aa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.l;"number"===typeof c?void 0===b.v?h.dynCall_v(c):h.dynCall_vi(c,b.v):c(void 0===b.v?null:b.v)}}}var Ba=[],Ca=[],Da=[],Ea=[],Fa=[];
function Ga(){var a=h.preRun.shift();Ba.unshift(a)}var Ha=Math.abs,Ia=Math.ceil,Ja=Math.floor,Ka=Math.min,I=0,La=null,Ma=null;function Na(){I++;h.monitorRunDependencies&&h.monitorRunDependencies(I)}function Oa(){I--;h.monitorRunDependencies&&h.monitorRunDependencies(I);if(0==I&&(null!==La&&(clearInterval(La),La=null),Ma)){var a=Ma;Ma=null;a()}}h.preloadedImages={};h.preloadedAudios={};
function A(a){if(h.onAbort)h.onAbort(a);ja(a);B(a);D=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Pa(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="Sample2.wasm";if(!Pa()){var Qa=J;J=h.locateFile?h.locateFile(Qa,y):y+Qa}
function Ra(){try{if(ma)return new Uint8Array(ma);if(z)return z(J);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}function Sa(){return ma||!v&&!w||"function"!==typeof fetch?new Promise(function(a){a(Ra())}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ra()})}var L,N;Ca.push({l:function(){Ta()}});function Ua(a,b){Ea.unshift({l:a,v:b})}
function Va(a){h.___errno_location&&(F[h.___errno_location()>>2]=a)}function Wa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function O(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wa(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Xa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Za(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function $a(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wa(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ab=[];function bb(a,b){ab[a]={input:[],output:[],F:b};cb(a,db)}
var db={open:function(a){var b=ab[a.node.rdev];if(!b)throw new P(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.F.flush(a.tty)},flush:function(a){a.tty.F.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.F.ua)throw new P(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.F.ua(a.tty)}catch(n){throw new P(29);}if(void 0===k&&0===f)throw new P(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.F.la)throw new P(60);try{for(var f=
0;f<d;f++)a.tty.F.la(a.tty,b[c+f])}catch(g){throw new P(29);}d&&(a.node.timestamp=Date.now());return f}},fb={ua:function(a){if(!a.input.length){var b=null;if(x){var c=Buffer.ea?Buffer.ea(256):new Buffer(256),d=0;try{d=fa.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=eb(b,!0)}return a.input.shift()},la:function(a,b){null===b||10===b?(ja(ra(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(ra(a.output,0)),a.output=[])}},gb={la:function(a,b){null===b||10===b?(B(ra(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(ra(a.output,0)),a.output=[])}},Q={o:null,u:function(){return Q.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.o||(Q.o={dir:{node:{m:Q.f.m,s:Q.f.s,lookup:Q.f.lookup,R:Q.f.R,rename:Q.f.rename,unlink:Q.f.unlink,rmdir:Q.f.rmdir,readdir:Q.f.readdir,symlink:Q.f.symlink},stream:{B:Q.g.B}},file:{node:{m:Q.f.m,s:Q.f.s},stream:{B:Q.g.B,read:Q.g.read,write:Q.g.write,pa:Q.g.pa,wa:Q.g.wa,X:Q.g.X}},link:{node:{m:Q.f.m,s:Q.f.s,readlink:Q.f.readlink},stream:{}},qa:{node:{m:Q.f.m,s:Q.f.s},stream:hb}});c=ib(a,b,c,d);16384===(c.mode&61440)?
(c.f=Q.o.dir.node,c.g=Q.o.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=Q.o.file.node,c.g=Q.o.file.stream,c.h=0,c.c=null):40960===(c.mode&61440)?(c.f=Q.o.link.node,c.g=Q.o.link.stream):8192===(c.mode&61440)&&(c.f=Q.o.qa.node,c.g=Q.o.qa.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},mb:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.h;++c)b.push(a.c[c]);return b}return a.c},nb:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.h):new Uint8Array(a.c):new Uint8Array},ra:function(a,
b){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.h&&a.c.set(c.subarray(0,a.h),0))},Qa:function(a,b){if(a.h!=b)if(0==b)a.c=null,a.h=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(new ArrayBuffer(b));c&&a.c.set(c.subarray(0,Math.min(b,a.h)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.h=b}},f:{m:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.h:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Fa=4096;b.blocks=Math.ceil(b.size/b.Fa);return b},s:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.Qa(a,b.size)},lookup:function(){throw jb[44];},R:function(a,b,c,d){return Q.createNode(a,
b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=kb(b,c)}catch(g){}if(d)for(var f in d.c)throw new P(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},unlink:function(a,b){delete a.c[b]},rmdir:function(a,b){var c=kb(a,b),d;for(d in c.c)throw new P(55);delete a.c[b]},readdir:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&
61440))throw new P(28);return a.link}},g:{read:function(a,b,c,d,f){var g=a.node.c;if(f>=a.node.h)return 0;a=Math.min(a.node.h-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.h=d;if(0===a.h&&0===f)return a.c=new Uint8Array(b.subarray(c,c+d)),a.h=d;if(f+d<=a.h)return a.c.set(b.subarray(c,c+d),f),d}Q.ra(a,f+
d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.c[f+g]=b[c+g];a.h=Math.max(a.h,f+d);return d},B:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.h);if(0>b)throw new P(28);return b},pa:function(a,b,c){Q.ra(a.node,b+c);a.node.h=Math.max(a.node.h,b+c)},wa:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new P(43);c=a.node.c;if(k&2||c.buffer!==b.buffer){if(0<f||f+d<a.node.h)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,
f,f+d);a=!0;f=b.buffer==E.buffer;d=lb(d);if(!d)throw new P(48);(f?E:b).set(c,d)}else a=!1,d=c.byteOffset;return{xb:d,Ea:a}},X:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new P(43);if(f&2)return 0;Q.g.write(a,b,0,d,c,!1);return 0}}},mb=null,nb={},R=[],ob=1,pb=null,qb=!0,rb={},P=null,jb={};
function S(a,b){a=$a("/",a);b=b||{};if(!a)return{path:"",node:null};var c={sa:!0,ma:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ma)throw new P(32);a=Wa(a.split("/").filter(function(a){return!!a}),!1);var f=mb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=kb(f,a[d]);c=O(c+"/"+a[d]);f.S&&(!g||g&&b.sa)&&(f=f.S.root);if(!g||b.ha)for(g=0;40960===(f.mode&61440);)if(f=sb(c),c=$a(Xa(c),f),f=S(c,{ma:b.ma}).node,40<g++)throw new P(32);}return{path:c,node:f}}
function tb(a){for(var b;;){if(a===a.parent)return a=a.u.ya,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function ub(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pb.length}function vb(a){var b=ub(a.parent.id,a.name);a.Pa=pb[b];pb[b]=a}function kb(a,b){var c;if(c=(c=wb(a,"x"))?c:a.f.lookup?0:2)throw new P(c,a);for(c=pb[ub(a.id,b)];c;c=c.Pa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.lookup(a,b)}
function ib(a,b,c,d){xb||(xb=function(a,b,c,d){a||(a=this);this.parent=a;this.u=a.u;this.S=null;this.id=ob++;this.name=b;this.mode=c;this.f={};this.g={};this.rdev=d},xb.prototype={},Object.defineProperties(xb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new xb(a,b,c,d);vb(a);return a}
var yb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function wb(a,b){if(qb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ab(a,b){try{return kb(a,b),20}catch(c){}return wb(a,"wx")}
function Bb(a){var b=4096;for(a=a||0;a<=b;a++)if(!R[a])return a;throw new P(33);}function Cb(a,b){Db||(Db=function(){},Db.prototype={},Object.defineProperties(Db.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Db,d;for(d in a)c[d]=a[d];a=c;b=Bb(b);a.fd=b;return R[b]=a}var hb={open:function(a){a.g=nb[a.node.rdev].g;a.g.open&&a.g.open(a)},B:function(){throw new P(70);}};function cb(a,b){nb[a]={g:b}}
function Eb(a,b){var c="/"===b,d=!b;if(c&&mb)throw new P(10);if(!c&&!d){var f=S(b,{sa:!1});b=f.path;f=f.node;if(f.S)throw new P(10);if(16384!==(f.mode&61440))throw new P(54);}b={type:a,vb:{},ya:b,Oa:[]};a=a.u(b);a.u=b;b.root=a;c?mb=a:f&&(f.S=b,f.u&&f.u.Oa.push(b))}function Fb(a,b,c){var d=S(a,{parent:!0}).node;a=Za(a);if(!a||"."===a||".."===a)throw new P(28);var f=Ab(d,a);if(f)throw new P(f);if(!d.f.R)throw new P(63);return d.f.R(d,a,b,c)}function T(a,b){Fb(a,(void 0!==b?b:511)&1023|16384,0)}
function Gb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Fb(a,b|8192,c)}function Hb(a,b){if(!$a(a))throw new P(44);var c=S(b,{parent:!0}).node;if(!c)throw new P(44);b=Za(b);var d=Ab(c,b);if(d)throw new P(d);if(!c.f.symlink)throw new P(63);c.f.symlink(c,b,a)}function sb(a){a=S(a).node;if(!a)throw new P(44);if(!a.f.readlink)throw new P(28);return $a(tb(a.parent),a.f.readlink(a))}
function Ib(a,b,c,d){if(""===a)throw new P(44);if("string"===typeof b){var f=yb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=O(a);try{g=S(a,{ha:!(b&131072)}).node}catch(n){}}f=!1;if(b&64)if(g){if(b&128)throw new P(20);}else g=Fb(a,c,0),f=!0;if(!g)throw new P(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new P(54);if(!f&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==zb(b)||b&512)?31:wb(g,zb(b)):44))throw new P(c);if(b&512){c=g;var k;"string"===typeof c?k=S(c,{ha:!0}).node:k=c;if(!k.f.s)throw new P(63);if(16384===(k.mode&61440))throw new P(31);if(32768!==(k.mode&61440))throw new P(28);if(c=wb(k,"w"))throw new P(c);k.f.s(k,{size:0,timestamp:Date.now()})}b&=-641;d=Cb({node:g,path:tb(g),flags:b,seekable:!0,position:0,g:g.g,cb:[],error:!1},d);d.g.open&&d.g.open(d);!h.logReadFiles||b&1||(Jb||(Jb={}),a in Jb||(Jb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{rb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),rb.onOpenFile(a,g))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function Kb(a,b,c){if(null===a.fd)throw new P(8);if(!a.seekable||!a.g.B)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.g.B(a,b,c);a.cb=[]}
function Lb(){P||(P=function(a,b){this.node=b;this.Va=function(a){this.j=a};this.Va(a);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(function(a){jb[a]=new P(a);jb[a].stack="<generic error, no stack>"}))}var Mb;function Nb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ob(a,b,c){a=O("/dev/"+a);var d=Nb(!!b,!!c);Pb||(Pb=64);var f=Pb++<<8|0;cb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,k=0;k<f;k++){try{var n=b()}catch(G){throw new P(29);}if(void 0===n&&0===g)throw new P(6);if(null===n||void 0===n)break;g++;c[d+k]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(t){throw new P(29);}f&&(a.node.timestamp=Date.now());return g}});
Gb(a,d,f)}var Pb,U={},xb,Db,Jb,Qb={},W=0;function X(){W+=4;return F[W-4>>2]}function Y(a){void 0===a&&(a=X());a=R[a];if(!a)throw new P(8);return a}function Z(){A()}
function Rb(a,b){e.b.Z=a;e.b.$=b;if(e.b.l)if(0==a)e.b.A=function(){var a=Math.max(0,e.b.Ya+b-Z())|0;setTimeout(e.b.Y,a)},e.b.method="timeout";else if(1==a)e.b.A=function(){e.requestAnimationFrame(e.b.Y)},e.b.method="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);w?(void 0===h.setImmediates&&(h.setImmediates=[]),
h.setImmediates.push(a),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}e.b.A=function(){setImmediate(e.b.Y)};e.b.method="immediate"}}
function Sb(a,b,c,d,f){C=!0;assert(!e.b.l,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");e.b.l=a;e.b.v=d;var g="undefined"!==typeof d?function(){h.dynCall_vi(a,d)}:function(){h.dynCall_v(a)};var k=e.b.C;e.b.Y=function(){if(!D)if(0<e.b.Ba.length){var a=Date.now(),b=e.b.Ba.shift();b.l(b.v);if(e.b.na){var c=e.b.na,d=0==c%1?c-1:Math.floor(c);e.b.na=b.jb?d:(8*
c+(d+.5))/9}console.log('main loop blocker "'+b.name+'" took '+(Date.now()-a)+" ms");e.b.eb();k<e.b.C||setTimeout(e.b.Y,0)}else k<e.b.C||(e.b.ga=e.b.ga+1|0,1==e.b.Z&&1<e.b.$&&0!=e.b.ga%e.b.$?e.b.A():(0==e.b.Z&&(e.b.Ya=Z()),"timeout"===e.b.method&&h.fa&&(B("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),e.b.method=
""),e.b.Sa(g),k<e.b.C||e.b.A()))};f||(b&&0<b?Rb(0,1E3/b):Rb(1,1),e.b.A());if(c)throw"SimulateInfiniteLoop";}
e={b:{A:null,method:"",C:0,l:null,v:0,Z:0,$:0,ga:0,Ba:[],pause:function(){e.b.A=null;e.b.C++},resume:function(){e.b.C++;var a=e.b.Z,b=e.b.$,c=e.b.l;e.b.l=null;Sb(c,0,!1,e.b.v,!0);Rb(a,b);e.b.A()},eb:function(){if(h.setStatus){var a=h.statusMessage||"Please wait...",b=e.b.na,c=e.b.lb;b?b<c?h.setStatus(a+" ("+(c-b)+"/"+c+")"):h.setStatus(a):h.setStatus("")}},Sa:function(a){if(!(D||h.preMainLoop&&!1===h.preMainLoop())){try{a()}catch(b){if(b instanceof ia)return;b&&"object"===typeof b&&b.stack&&B("exception thrown: "+
[b,b.stack]);throw b;}h.postMainLoop&&h.postMainLoop()}}},J:!1,ka:!1,Na:[],workers:[],Ka:function(){function a(){e.ka=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!e.La){e.La=!0;try{e.O=!0}catch(c){e.O=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}e.BlobBuilder="undefined"!=typeof MozBlobBuilder?
MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:e.O?null:console.log("warning: no BlobBuilder");e.N="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Aa||"undefined"!==typeof e.N||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Aa=!0);h.preloadPlugins.push({canHandle:function(a){return!h.Aa&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(e.O)try{c=
new Blob([a],{type:e.ia(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:e.ia(b)}))}catch(r){ka("Blob constructor present but fails: "+r+"; falling back to blob builder")}c||(c=new e.BlobBuilder,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=e.N.createObjectURL(c),q=new Image;q.onload=function(){assert(q.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=q.width;c.height=q.height;c.getContext("2d").drawImage(q,0,0);h.preloadedImages[b]=
c;e.N.revokeObjectURL(d);f&&f(a)};q.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};q.src=d}});h.preloadPlugins.push({canHandle:function(a){return!h.ub&&a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){q||(q=!0,h.preloadedAudios[b]=c,f&&f(a))}function d(){q||(q=!0,h.preloadedAudios[b]=new Audio,g&&g())}var q=!1;if(e.O){try{var r=new Blob([a],{type:e.ia(b)})}catch(K){return d()}r=e.N.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",
function(){c(t)},!1);t.onerror=function(){if(!q){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,k=0;k<a.length;k++)for(f=f<<8|a[k],g+=8;6<=g;){var n=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[n]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");t.src=
"data:audio/x-"+b.substr(-3)+";base64,"+d;c(t)}};t.src=r;e.Ta(function(){c(t)},1E4)}else return d()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),
document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",function(a){!e.ka&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),a.preventDefault())},!1))}},createContext:function(a,b,c,d){if(b&&h.fa&&a==h.canvas)return h.fa;var f;if(b){var g={antialias:!1,alpha:!1,rb:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof GL&&(f=GL.createContext(a,
g)))var n=GL.getContext(f).gb}else n=a.getContext("2d");if(!n)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.fa=n,b&&GL.sb(f),h.Eb=b,e.Na.forEach(function(a){a()}),e.Ka());return n},kb:function(){},ta:!1,P:void 0,G:void 0,requestFullscreen:function(a,b,c){function d(){e.J=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=e.exitFullscreen,e.P&&f.requestPointerLock(),e.J=!0,e.G?e.Wa():e.M(f)):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),e.G?e.Xa():e.M(f));if(h.onFullScreen)h.onFullScreen(e.J);if(h.onFullscreen)h.onFullscreen(e.J)}e.P=a;e.G=b;e.Da=c;"undefined"===typeof e.P&&(e.P=!0);"undefined"===typeof e.G&&(e.G=!1);"undefined"===typeof e.Da&&(e.Da=null);var f=h.canvas;e.ta||(e.ta=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({Fb:c}):
g.requestFullscreen()},Ca:function(a,b,c){B("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");e.Ca=function(a,b,c){return e.requestFullscreen(a,b,c)};return e.requestFullscreen(a,b,c)},exitFullscreen:function(){if(!e.J)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0},D:0,Ga:function(a){var b=Date.now();if(0===e.D)e.D=
b+1E3/60;else for(;b+2>=e.D;)e.D+=1E3/60;setTimeout(a,Math.max(e.D-b,0))},requestAnimationFrame:function(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=e.Ga;b(a)}},zb:function(a){return function(){if(!D)return a.apply(null,arguments)}},I:!0,K:[],wb:function(){e.I=!1},yb:function(){e.I=!0;if(0<e.K.length){var a=e.K;e.K=[];a.forEach(function(a){a()})}},Ab:function(a){return e.requestAnimationFrame(function(){D||(e.I?a():e.K.push(a))})},Ta:function(a,b){C=!0;return setTimeout(function(){D||
(e.I?a():e.K.push(a))},b)},Bb:function(a,b){C=!0;return setInterval(function(){D||e.I&&a()},b)},ia:function(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]},getUserMedia:function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)},Ha:function(a){return a.movementX||a.mozMovementX||a.webkitMovementX||0},Ia:function(a){return a.movementY||
a.mozMovementY||a.webkitMovementY||0},ob:function(a){switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}return b},V:0,W:0,T:0,U:0,touches:{},va:{},ib:function(a){if(e.ka)"mousemove"!=a.type&&"mozMovementX"in a?e.T=e.U=0:
(e.T=e.Ha(a),e.U=e.Ia(a)),e.V+=e.T,e.W+=e.U;else{var b=h.canvas.getBoundingClientRect(),c=h.canvas.width,d=h.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;if("touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type){var k=a.Db;if(void 0!==k)if(f=k.pageX-(f+b.left),g=k.pageY-(g+b.top),f*=c/b.width,g*=d/b.height,b={x:f,y:g},"touchstart"===a.type)e.va[k.identifier]=b,e.touches[k.identifier]=
b;else if("touchend"===a.type||"touchmove"===a.type)(a=e.touches[k.identifier])||(a=b),e.va[k.identifier]=a,e.touches[k.identifier]=b}else k=a.pageX-(f+b.left),a=a.pageY-(g+b.top),k*=c/b.width,a*=d/b.height,e.T=k-e.V,e.U=a-e.W,e.V=k,e.W=a}},hb:function(a,b,c,d){var f=d?"":"al "+a;ea(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));f&&Oa()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});f&&Na()},Ra:[],oa:function(){var a=h.canvas;
e.Ra.forEach(function(b){b(a.width,a.height)})},Ua:function(a,b,c){e.M(h.canvas,a,b);c||e.oa()},Ib:0,Hb:0,Wa:function(){e.M(h.canvas);e.oa()},Xa:function(){e.M(h.canvas);e.oa()},M:function(a,b,c){b&&c?(a.fb=b,a.Ja=c):(b=a.fb,c=a.Ja);var d=b,f=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/f<h.forcedAspectRatio?d=Math.round(f*h.forcedAspectRatio):f=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||
document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*g)}e.G?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):
(a.style.removeProperty("width"),a.style.removeProperty("height"))))},Gb:{},za:0,pb:function(){var a=e.za;e.za++;return a}};var Tb={};function Ub(){if(!Vb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa},b;for(b in Tb)a[b]=Tb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Vb=c}return Vb}var Vb;function Wb(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Xb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Yb=[31,29,31,30,31,30,31,31,30,31,30,31],Zb=[31,28,31,30,31,30,31,31,30,31,30,31];function $b(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Wb(a.getFullYear())?Yb:Zb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function ac(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=$b(new Date(a.i+1900,0,1),a.da);var b=n(new Date(a.getFullYear()+1,0,4));return 0>=k(n(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=F[d+40>>2];d={ab:F[d>>2],$a:F[d+4>>2],aa:F[d+8>>2],L:F[d+12>>2],H:F[d+16>>2],i:F[d+20>>2],ba:F[d+24>>2],da:F[d+28>>2],Cb:F[d+32>>2],Za:F[d+36>>2],bb:r?
sa(r):""};c=sa(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in r)c=c.replace(new RegExp(t,"g"),r[t]);var K="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
G="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return K[a.ba].substring(0,3)},"%A":function(a){return K[a.ba]},"%b":function(a){return G[a.H].substring(0,3)},"%B":function(a){return G[a.H]},"%C":function(a){return g((a.i+1900)/100|0,2)},"%d":function(a){return g(a.L,2)},"%e":function(a){return f(a.L,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return g(a.aa,2)},
"%I":function(a){a=a.aa;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.L+Xb(Wb(a.i+1900)?Yb:Zb,a.H-1),3)},"%m":function(a){return g(a.H+1,2)},"%M":function(a){return g(a.$a,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.aa&&12>a.aa?"AM":"PM"},"%S":function(a){return g(a.ab,2)},"%t":function(){return"\t"},"%u":function(a){return a.ba||7},"%U":function(a){var b=new Date(a.i+1900,0,1),c=0===b.getDay()?b:$b(b,7-b.getDay());a=new Date(a.i+1900,a.H,a.L);return 0>k(c,a)?
g(Math.ceil((31-c.getDate()+(Xb(Wb(a.getFullYear())?Yb:Zb,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.i+1900,0,4)),c=n(new Date(a.i+1901,0,4)),d=$b(new Date(a.i+1900,0,1),a.da);return 0>k(d,b)?"53":0>=k(c,d)?"01":g(Math.ceil((b.getFullYear()<a.i+1900?a.da+32-b.getDate():a.da+1-b.getDate())/7),2)},"%w":function(a){return a.ba},"%W":function(a){var b=new Date(a.i,0,1),c=1===b.getDay()?b:$b(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.i+1900,a.H,
a.L);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(Xb(Wb(a.getFullYear())?Yb:Zb,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%y":function(a){return(a.i+1900).toString().substring(2)},"%Y":function(a){return a.i+1900},"%z":function(a){a=a.Za;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.bb},"%%":function(){return"%"}};for(t in r)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),r[t](d)));t=eb(c,!1);if(t.length>b)return 0;
E.set(t,a);return t.length-1}Lb();pb=Array(4096);Eb(Q,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");cb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Gb("/dev/null",259);bb(1280,fb);bb(1536,gb);Gb("/dev/tty",1280);Gb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(x)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){A("random_device")});Ob("random",b);Ob("urandom",b);T("/dev/shm");
T("/dev/shm/tmp")})();T("/proc");T("/proc/self");T("/proc/self/fd");Eb({u:function(){var a=ib("/proc/self","fd",16895,73);a.f={lookup:function(a,c){var b=R[+c];if(!b)throw new P(8);a={parent:null,u:{ya:"fake"},f:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
x?Z=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Z=dateNow:"object"===typeof performance&&performance&&"function"===typeof performance.now?Z=function(){return performance.now()}:Z=Date.now;h.requestFullScreen=function(a,b,c){B("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");h.requestFullScreen=h.requestFullscreen;e.Ca(a,b,c)};h.requestFullscreen=function(a,b,c){e.requestFullscreen(a,b,c)};
h.requestAnimationFrame=function(a){e.requestAnimationFrame(a)};h.setCanvasSize=function(a,b,c){e.Ua(a,b,c)};h.pauseMainLoop=function(){e.b.pause()};h.resumeMainLoop=function(){e.b.resume()};h.getUserMedia=function(){e.getUserMedia()};h.createContext=function(a,b,c,d){return e.createContext(a,b,c,d)};function eb(a,b){var c=Array(va(a)+1);a=ua(a,c,0,c.length);b&&(c.length=a);return c}
var dc={__cxa_allocate_exception:function(a){return lb(a)},__cxa_atexit:function(){return Ua.apply(null,arguments)},__cxa_throw:function(a){"uncaught_exception"in bc?bc.ea++:bc.ea=1;throw a;},__lock:function(){},__map_file:function(){Va(63);return-1},__syscall195:function(a,b){W=b;try{var c=sa(X());a:{var d=X();try{var f=S(c,{ha:!0}).node;if(!f)throw new P(44);if(!f.f.m)throw new P(63);var g=f.f.m(f)}catch(n){if(n&&n.node&&O(c)!==O(tb(n.node))){var k=-54;break a}throw n;}F[d>>2]=g.dev;F[d+4>>2]=0;
F[d+8>>2]=g.ino;F[d+12>>2]=g.mode;F[d+16>>2]=g.nlink;F[d+20>>2]=g.uid;F[d+24>>2]=g.gid;F[d+28>>2]=g.rdev;F[d+32>>2]=0;N=[g.size>>>0,(L=g.size,1<=+Ha(L)?0<L?(Ka(+Ja(L/4294967296),4294967295)|0)>>>0:~~+Ia((L-+(~~L>>>0))/4294967296)>>>0:0)];F[d+40>>2]=N[0];F[d+44>>2]=N[1];F[d+48>>2]=4096;F[d+52>>2]=g.blocks;F[d+56>>2]=g.atime.getTime()/1E3|0;F[d+60>>2]=0;F[d+64>>2]=g.mtime.getTime()/1E3|0;F[d+68>>2]=0;F[d+72>>2]=g.ctime.getTime()/1E3|0;F[d+76>>2]=0;N=[g.ino>>>0,(L=g.ino,1<=+Ha(L)?0<L?(Ka(+Ja(L/4294967296),
4294967295)|0)>>>0:~~+Ia((L-+(~~L>>>0))/4294967296)>>>0:0)];F[d+80>>2]=N[0];F[d+84>>2]=N[1];k=0}return k}catch(n){return"undefined"!==typeof U&&n instanceof P||A(n),-n.j}},__syscall221:function(a,b){W=b;try{var c=Y();switch(X()){case 0:var d=X();return 0>d?-28:Ib(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=X(),c.flags|=d,0;case 12:return d=X(),ya[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return Va(28),-1;default:return-28}}catch(f){return"undefined"!==
typeof U&&f instanceof P||A(f),-f.j}},__syscall39:function(a,b){W=b;try{var c=sa(X()),d=X();a=c;a=O(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));T(a,d);return 0}catch(f){return"undefined"!==typeof U&&f instanceof P||A(f),-f.j}},__syscall5:function(a,b){W=b;try{var c=sa(X()),d=X(),f=X();return Ib(c,d,f).fd}catch(g){return"undefined"!==typeof U&&g instanceof P||A(g),-g.j}},__syscall54:function(a,b){W=b;try{var c=Y(),d=X();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-59;case 21519:if(!c.tty)return-59;var f=X();return F[f>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=f=X();if(!c.g.Ma)throw new P(59);return c.g.Ma(c,d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:A("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof U&&g instanceof P||A(g),-g.j}},__syscall91:function(a,b){W=b;try{var c=X(),d=X();if(-1===c||0===d)var f=-28;else{var g=Qb[c];if(g&&d===g.qb){var k=R[g.fd],n=g.flags,q=new Uint8Array(ta.subarray(c,c+d));k&&k.g.X&&
k.g.X(k,q,0,d,n);Qb[c]=null;g.Ea&&cc(g.tb)}f=0}return f}catch(r){return"undefined"!==typeof U&&r instanceof P||A(r),-r.j}},__unlock:function(){},abort:function(){A()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a&&(x||"undefined"!==typeof dateNow||"object"===typeof performance&&performance&&"function"===typeof performance.now))a=Z();else return Va(28),-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_cancel_main_loop:function(){e.b.pause();e.b.l=null},emscripten_get_sbrk_ptr:function(){return 76128},
emscripten_memcpy_big:function(a,b,c){ta.set(ta.subarray(b,b+c),a)},emscripten_resize_heap:function(){A("OOM")},emscripten_set_main_loop:Sb,environ_get:function(a,b){var c=0;Ub().forEach(function(d,f){var g=b+c;f=F[a+4*f>>2]=g;for(g=0;g<d.length;++g)E[f++>>0]=d.charCodeAt(g);E[f>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=Ub();F[a>>2]=c.length;var d=0;c.forEach(function(a){d+=a.length+1});F[b>>2]=d;return 0},fd_close:function(a){try{var b=Y(a);if(null===b.fd)throw new P(8);
b.ja&&(b.ja=null);try{b.g.close&&b.g.close(b)}catch(c){throw c;}finally{R[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof U&&c instanceof P||A(c),c.j}},fd_read:function(a,b,c,d){try{a:{for(var f=Y(a),g=a=0;g<c;g++){var k=F[b+(8*g+4)>>2],n=f,q=F[b+8*g>>2],r=k,t=void 0,K=E;if(0>r||0>t)throw new P(28);if(null===n.fd)throw new P(8);if(1===(n.flags&2097155))throw new P(8);if(16384===(n.node.mode&61440))throw new P(31);if(!n.g.read)throw new P(28);var G="undefined"!==typeof t;if(!G)t=
n.position;else if(!n.seekable)throw new P(70);var na=n.g.read(n,K,q,r,t);G||(n.position+=na);var V=na;if(0>V){var M=-1;break a}a+=V;if(V<k)break}M=a}F[d>>2]=M;return 0}catch(Ya){return"undefined"!==typeof U&&Ya instanceof P||A(Ya),Ya.j}},fd_seek:function(a,b,c,d,f){try{var g=Y(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Kb(g,a,d);N=[g.position>>>0,(L=g.position,1<=+Ha(L)?0<L?(Ka(+Ja(L/4294967296),4294967295)|0)>>>0:~~+Ia((L-+(~~L>>>0))/4294967296)>>>0:0)];F[f>>
2]=N[0];F[f+4>>2]=N[1];g.ja&&0===a&&0===d&&(g.ja=null);return 0}catch(k){return"undefined"!==typeof U&&k instanceof P||A(k),k.j}},fd_write:function(a,b,c,d){try{a:{for(var f=Y(a),g=a=0;g<c;g++){var k=f,n=F[b+8*g>>2],q=F[b+(8*g+4)>>2],r=void 0,t=E;if(0>q||0>r)throw new P(28);if(null===k.fd)throw new P(8);if(0===(k.flags&2097155))throw new P(8);if(16384===(k.node.mode&61440))throw new P(31);if(!k.g.write)throw new P(28);k.flags&1024&&Kb(k,0,2);var K="undefined"!==typeof r;if(!K)r=k.position;else if(!k.seekable)throw new P(70);
var G=k.g.write(k,t,n,q,r,void 0);K||(k.position+=G);try{if(k.path&&rb.onWriteToFile)rb.onWriteToFile(k.path)}catch(M){console.log("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+M.message)}var na=G;if(0>na){var V=-1;break a}a+=na}V=a}F[d>>2]=V;return 0}catch(M){return"undefined"!==typeof U&&M instanceof P||A(M),M.j}},memory:oa,nanosleep:function(a,b){if(0===a)return Va(28),-1;var c=F[a>>2];a=F[a+4>>2];if(0>a||999999999<a||0>c)return Va(28),-1;0!==b&&(F[b>>2]=0,F[b+4>>2]=
0);b=(1E6*c+a/1E3)/1E3;if((v||w)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},pthread_equal:function(a,b){return a==b},pthread_mutexattr_destroy:function(){},pthread_mutexattr_init:function(){},pthread_mutexattr_settype:function(){},sched_yield:function(){return 0},setTempRet0:function(){},strftime_l:function(a,b,c,d){return ac(a,b,c,d)},table:pa},ec=function(){function a(a){h.asm=a.exports;Oa()}
function b(b){a(b.instance)}function c(a){return Sa().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){B("failed to asynchronously prepare wasm: "+a);A(a)})}var d={env:dc,wasi_unstable:dc};Na();if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(f){return B("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(ma||"function"!==typeof WebAssembly.instantiateStreaming||Pa()||"function"!==typeof fetch)return c(b);fetch(J,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,
d).then(b,function(a){B("wasm streaming compile failed: "+a);B("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();h.asm=ec;var Ta=h.___wasm_call_ctors=function(){return h.asm.__wasm_call_ctors.apply(null,arguments)},cc=h._free=function(){return h.asm.free.apply(null,arguments)};h._main=function(){return h.asm.main.apply(null,arguments)};var lb=h._malloc=function(){return h.asm.malloc.apply(null,arguments)};
h.___errno_location=function(){return h.asm.__errno_location.apply(null,arguments)};h.__get_tzname=function(){return h.asm._get_tzname.apply(null,arguments)};h.__get_daylight=function(){return h.asm._get_daylight.apply(null,arguments)};h.__get_timezone=function(){return h.asm._get_timezone.apply(null,arguments)};h._setThrew=function(){return h.asm.setThrew.apply(null,arguments)};var bc=h.__ZSt18uncaught_exceptionv=function(){return h.asm._ZSt18uncaught_exceptionv.apply(null,arguments)};
h.stackSave=function(){return h.asm.stackSave.apply(null,arguments)};var xa=h.stackAlloc=function(){return h.asm.stackAlloc.apply(null,arguments)};h.stackRestore=function(){return h.asm.stackRestore.apply(null,arguments)};h.__growWasmMemory=function(){return h.asm.__growWasmMemory.apply(null,arguments)};h.dynCall_iii=function(){return h.asm.dynCall_iii.apply(null,arguments)};h.dynCall_iiiii=function(){return h.asm.dynCall_iiiii.apply(null,arguments)};
h.dynCall_ii=function(){return h.asm.dynCall_ii.apply(null,arguments)};h.dynCall_vi=function(){return h.asm.dynCall_vi.apply(null,arguments)};h.dynCall_iiiiii=function(){return h.asm.dynCall_iiiiii.apply(null,arguments)};h.dynCall_vii=function(){return h.asm.dynCall_vii.apply(null,arguments)};h.dynCall_viii=function(){return h.asm.dynCall_viii.apply(null,arguments)};h.dynCall_iiii=function(){return h.asm.dynCall_iiii.apply(null,arguments)};
h.dynCall_iij=function(){return h.asm.dynCall_iij.apply(null,arguments)};h.dynCall_iif=function(){return h.asm.dynCall_iif.apply(null,arguments)};h.dynCall_iid=function(){return h.asm.dynCall_iid.apply(null,arguments)};h.dynCall_iijii=function(){return h.asm.dynCall_iijii.apply(null,arguments)};h.dynCall_iifii=function(){return h.asm.dynCall_iifii.apply(null,arguments)};h.dynCall_iidii=function(){return h.asm.dynCall_iidii.apply(null,arguments)};
h.dynCall_fi=function(){return h.asm.dynCall_fi.apply(null,arguments)};h.dynCall_v=function(){return h.asm.dynCall_v.apply(null,arguments)};h.dynCall_i=function(){return h.asm.dynCall_i.apply(null,arguments)};h.dynCall_di=function(){return h.asm.dynCall_di.apply(null,arguments)};h.dynCall_viiii=function(){return h.asm.dynCall_viiii.apply(null,arguments)};h.dynCall_vid=function(){return h.asm.dynCall_vid.apply(null,arguments)};h.dynCall_jiji=function(){return h.asm.dynCall_jiji.apply(null,arguments)};
h.dynCall_iidiiii=function(){return h.asm.dynCall_iidiiii.apply(null,arguments)};h.dynCall_viijii=function(){return h.asm.dynCall_viijii.apply(null,arguments)};h.dynCall_iiiiiiiii=function(){return h.asm.dynCall_iiiiiiiii.apply(null,arguments)};h.dynCall_iiiiiii=function(){return h.asm.dynCall_iiiiiii.apply(null,arguments)};h.dynCall_iiiiij=function(){return h.asm.dynCall_iiiiij.apply(null,arguments)};h.dynCall_iiiiid=function(){return h.asm.dynCall_iiiiid.apply(null,arguments)};
h.dynCall_iiiiijj=function(){return h.asm.dynCall_iiiiijj.apply(null,arguments)};h.dynCall_iiiiiiii=function(){return h.asm.dynCall_iiiiiiii.apply(null,arguments)};h.dynCall_iiiiiijj=function(){return h.asm.dynCall_iiiiiijj.apply(null,arguments)};h.dynCall_viiiiii=function(){return h.asm.dynCall_viiiiii.apply(null,arguments)};h.dynCall_viiiii=function(){return h.asm.dynCall_viiiii.apply(null,arguments)};h.asm=ec;var fc;
function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ma=function hc(){fc||ic();fc||(Ma=hc)};
function ic(a){function b(){if(!fc&&(fc=!0,!D)){h.noFSInit||Mb||(Mb=!0,Lb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Ob("stdin",h.stdin):Hb("/dev/tty","/dev/stdin"),h.stdout?Ob("stdout",null,h.stdout):Hb("/dev/tty","/dev/stdout"),h.stderr?Ob("stderr",null,h.stderr):Hb("/dev/tty1","/dev/stderr"),Ib("/dev/stdin","r"),Ib("/dev/stdout","w"),Ib("/dev/stderr","w"));Aa(Ca);qb=!1;Aa(Da);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(jc){var b=a,d=h._main;b=b||[];var f=b.length+1,
g=xa(4*(f+1));F[g>>2]=wa(aa);for(var k=1;k<f;k++)F[(g>>2)+k]=wa(b[k-1]);F[(g>>2)+f]=0;try{var n=d(f,g);if(!C||0!==n){if(!C&&(D=!0,h.onExit))h.onExit(n);u(n,new ia(n))}}catch(q){q instanceof ia||("SimulateInfiniteLoop"==q?C=!0:((b=q)&&"object"===typeof q&&q.stack&&(b=[q,q.stack]),B("exception thrown: "+b),u(1,q)))}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)b=h.postRun.shift(),Fa.unshift(b);Aa(Fa)}}a=a||p;if(!(0<I)){if(h.preRun)for("function"==
typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ga();Aa(Ba);0<I||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}h.run=ic;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var jc=!0;h.noInitialRun&&(jc=!1);C=!0;ic();
